### ISSUE TITLE
How to cooperate with themes?

### ISSUE THREAD

**Issue by CoMPaTech** [thomasloven/lovelace-card-mod#10]
Hi Thomas,

Great mod, maybe I didn't read through properly, but how would I go about the `--ha-card-background:` with regards to theming? I.e. having a dark and a light theme now messes up when switching on sundown.

Tnx

**Comment by thomasloven** [comment]
I don't understand your question.

If you wish to set a variable, it's 

```css
ha-card {
  --ha-card-background: blue;
}
```

If you want to use its value, it's:

```css
ha-card {
  background: var(--ha-card-background);
}
```

**Comment by CoMPaTech** [comment]
Just asking if/how the below would be possible, but I'm such a happy user with card-mod already that I can forgo theming and just stick to bright/or dark.

I was referring to using themes (https://www.home-assistant.io/components/frontend/). I have a bright daylight theme an a darker night version. But when I'd set (for example)

```
style: |
  ha-card {
    --ha-card-background: rgba(255,255,255,0.8);
    background-image: url('/local/someimage.png');
    background-size: cover;
```

to have nice white-see-through that would be very bright at night. Same works in reverse setting it `64,64,64` and then having dark spots at daytime. It's obvious because of the 'hardcoding' of the background, hence I was wondering if there would be some level of re-using theme settings.

**Comment by thomasloven** [comment]
Yes, my second example above would set the background of the card to whatever was set as `ha-card-background` in the current theme.

You could also add custom variables to your theme, like
```yaml
my-background: rgba(255,255,255,0.8)
```
in your light theme and
```yaml
my-background: rgba(128,128,128,0.8)
```
in your dark theme, and then do
```css
ha-card {
  --ha-card-background: var(--my-background);
}
```

**Comment by CoMPaTech** [comment]
Ok, tnx

**Comment by Sonusss** [comment]
Hi,
I'm re opening this because I find useful to be able to retrieve defined theme values for ha-cards
Otherwise we need to define specific cards for each theme used.
A little like your variable example but getting the theme defined variable.

**Comment by thomasloven** [comment]
What?

**Comment by Sonusss** [comment]
Sorry, my bad.
I didn't understood the concept at first ;-(
Thx for your nice job !
