### ISSUE TITLE
Last 2021.02 HomeAssistant breaks card mod

### ISSUE THREAD

**Issue by ilbarone87** [thomasloven/lovelace-card-mod#100]
After the last update seems that card mod is not loading anymore. Can be this to the change in python? Can you please advise on this?
Thanks

**Comment by KTibow** [comment]
Please try to find out for yourself, to decrease workload on the maintainers. Logs?
> card mod is not loading anymore

What exactly do you mean? How did you find this out?

**Comment by ilbarone87** [comment]
> Logs?

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:58:24 (2 occurrences)
Last logged: 9:40:43

[140644938590768] Received invalid command: lovelace/resources/create
[140644854814224] Received invalid command: lovelace/resources/create

I think this is the most relevant.

**Comment by KTibow** [comment]
This is a problem with HACS.

**Comment by ilbarone87** [comment]
> This is a problem with HACS.

Thanks. Solved.
