### ISSUE TITLE
font-size not working since 3.0.1 (2.0.3 working fine)

### ISSUE THREAD

**Issue by nenadmilano** [thomasloven/lovelace-card-mod#107]
My Home Assistant version: 2021.2.3

My lovelace configuration method (GUI or yaml):

              card_mod:
                style: |
                  ha-card {
                    font-size: 20px;
                  }

What I am doing:
changing the font size

What I expected to happen:
bigger font size

What happened instead:
font size stays the same

**Minimal** steps to reproduce:

              card_mod:
                style: |
                  ha-card {
                    font-size: 20px;
                  }

On card-mod 2.0.3 everything works fine.

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser 
-

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
What if instead you target `ha-card *` and use `!important`?

**Comment by nenadmilano** [comment]
> What if instead you target `ha-card *` and use `!important`?

Can you specify the „target ha-card *“ a bit more? Adding !important did not make the font bigger.
```
              card_mod:
                style: |
                  ha-card {
                    font-size: 25px !important;
                  }
```

**Comment by thomasloven** [comment]
Can't reproduce.

Do you have any other styles somewhere else?
Did you try refreshing?
What card are we talking about?

![image](https://user-images.githubusercontent.com/1299821/109390290-075ef280-7911-11eb-80dc-0305bd5637fa.png)
```yaml
type: entities
entities:
  - entity: light.kitchen_lights
  - entity: light.bed_light
  - entity: light.ceiling_lights
card_mod:
  style: |
    ha-card {
      font-size: 36px;
    }
```

**Comment by nenadmilano** [comment]
Interestingly I see the following error when I try to investigate with the Developer Tools in Chrome:
`Uncaught SyntaxError: Identifier 'e' has already been declared`

Could it be that the mod is not loaded properly? Do you need the whole error message? (quite long)

**Comment by thomasloven** [comment]
What other lovelace resources do you use?
How did you install them (and this)?
How did you add them to lovelace?

**Comment by nenadmilano** [comment]
First of all thanks for your quick responses, highly appreciated!

This is the content of my resources.yaml file, I manage my lovelace dashboard via YAML and not the GUI.
99% of my custom addons were installed / updated through HACS:

```
  - type: module
    url: /hacsfiles/weather-card/weather-card.js

  - type: js
    url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js

  - type: module
    url: /hacsfiles/button-card/button-card.js

  - type: module
    url: /hacsfiles/simple-thermostat/simple-thermostat.js

  - type: module
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js

  - type: js
    url: /local/custom-lovelace/lovelace-entity-markdown-card/entity-markdown.js

  - type: js
    url: /hacsfiles/text-divider-row/text-divider-row.js

  - type: module
    url: /hacsfiles/banner-card/banner-card.js

  - type: module
    url: /hacsfiles/circle-sensor-card/circle-sensor-card.js

  - type: js
    url: /hacsfiles/dual-gauge-card/dual-gauge-card.js

  - type: js
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js

  - type: js
    url: /hacsfiles/list-card/list-card.js

  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js

  - type: js
    url: /hacsfiles/upcoming-media-card/upcoming-media-card.js

  - type: js
    url: /hacsfiles/flex-table-card/flex-table-card.js

  - type: js
    url: /hacsfiles/lovelace-card-mod/card-mod.js

  - type: module
    url: /hacsfiles/lovelace-auto-entities/auto-entities.js

  - type: js
    url: /hacsfiles/bignumber-card/bignumber-card.js

  - type: js
    url: /hacsfiles/bignumber-card-v2/bignumber-card-v2.js

  - type: module
    url: /hacsfiles/atomic_calendar/atomic_calendar.js

  - type: js
    url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js

  - type: module
    url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js

  - type: module
    url: /hacsfiles/lovelace-rpi-monitor-card/rpi-monitor-card.js

  - type: module
    url: /hacsfiles/lovelace-layout-card/layout-card.js

  - type: module
    url: /hacsfiles/stack-in-card/stack-in-card.js

  - type: module
    url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js

  - type: module
    url: /hacsfiles/surveillance-card/surveillance-card.js?v=0
    
  - type: module
    url: /hacsfiles/lovelace-state-switch/state-switch.js
    
  - type: module
    url: /hacsfiles/bar-card/bar-card.js
      
  - type: module
    url: /hacsfiles/lovelace-thermostat-card/main.js
    
  - type: module
    url: /hacsfiles/kb-better-graph-colors/kb-better-graph-colors.js

  - url: /hacsfiles/lovelace-auto-reload-card/auto-reload-card.js
    type: module
```

**Comment by thomasloven** [comment]
Ah yes. That's what I was starting to realize.

Unless otherwise specified, always assume that a resource should be of type `module`.
`type: js` is only still around for compatibility reasons.

Change it to
```yaml
  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js
```
and everything should be fine.

Heck. Change all of them.

**Comment by nenadmilano** [comment]
Awsome, that worked out! Thank you very much!!
