### ISSUE TITLE
CSS styling inside HA app & Chromium (Linux) is broken

### ISSUE THREAD

**Issue by Lampyridae1984** [thomasloven/lovelace-card-mod#108]
My Home Assistant version:
- Home Assistant 2021.2.3
- Frontend 20210127.7
- Python 3.8.7
- OS 5.9.16

My lovelace configuration method (GUI or yaml):
- Both

What I am doing:
- Card background color, padding, border styling, text styling, icon styling etc.

Issue:
After updating to 3.0.1 and adding the line "card_mod:", all CSS styling is broken inside the official HA app and in Chromium (Linux).

Example:

```
card_mod:
  style: |
    ha-card {
      border: 4px solid #606060;
      border-radius: 30px;
      background-color: #404040;
      background: linear-gradient(135deg, #303030, #202020, #101010, #000000 100%);
      color: rgb(225,225,225);
      box-shadow: 2px 2px 2px #000000, -0px -0px 0px #00d2c6;
      text-shadow: 2px 2px 1px #000000;
    }
```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Sounds like a caching issue.
If you go back to just `style:` without `card_mod:` does it work?
Please make 100% sure your cache is cleared, and that your browser console says "CARD-MOD 3.0.2 IS INSTALLED"

**Comment by KTibow** [comment]
Did you try looking at the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins?

**Comment by Lampyridae1984** [comment]
> Sounds like a caching issue.
> If you go back to just `style:` without `card_mod:` does it work?
> Please make 100% sure your cache is cleared, and that your browser console says "CARD-MOD 3.0.2 IS INSTALLED"

I finally got it to work, not sure what the issue was. I had to clear my browser (google chrome) cache 5 times, manually clear the app cache, reinstall the app and reboot both devices (mobile and raspberry pi with display) to get all issues resolved. I've never had such a persistant cache issue before, sorry for wasting your time! :-(
