### ISSUE TITLE
Using card_mod: marker in yaml causes problems in Home Assistant official MobileApp

### ISSUE THREAD

**Issue by sstefanowski** [thomasloven/lovelace-card-mod#113]
**My Home Assistant version:** 
core-2021.2.3

**My lovelace configuration method (GUI or yaml):**
YAML

**What I am doing:**
I am setting custom background (JPG) on some cards with card_mod with the "new" pattern
When I use the "new" pattern:
```
card_mod:
    style: | 
        (...)
```
then the background is OK in WebBrowser (Chrome) but it's not rendered correctly in Mobile Application (Android version)

When I use "old" pattern (without card_mod:) just like 
```
style: |
   (...)
```
then it's OK. It is rendered correctly in both places Chrome Webbrowser on PC and in HA Mobile Application.

**What I expected to happen:**
When I use "card_mod:" declaration in YAML (to get benefits of the latest features) the card should also be rendered correctly in the official HA Mobile Application.

**What happened instead:**
When I use "card_mod:" declaration in YAML (to get benefits of the latest features) the card background (and layout) is not rendered correctly in the official HA Mobile Application.

Example screenshots. 

Official HA Mobile App on Android 
First Card with Header "Salon" is configured with "card_mod:" + "style:" YAML declaration. It's not OK. The second with header "Sypialnia" is configured with plain "style:" YAML declaration. This one OK.
<img src="https://user-images.githubusercontent.com/36473471/109733351-38644f00-7bbf-11eb-956a-f54348cea68d.jpg" width="40%">.

Chrome Web Browser on Windows PC (both cards are OK):
![WebBrowser](https://user-images.githubusercontent.com/36473471/109733355-39957c00-7bbf-11eb-9a0b-fb2115442262.jpg)

**Minimal** steps to reproduce:
Example of config causong a probem in HA Mobile App:
```
type: 'custom:banner-card'
entities:
(...)
heading: Salon
link: /lovelace/temperatura
card_mod:
  style: |
    ha-card {
      background: url("/local/Salon.jpg") center no-repeat;
      align-items: baseline;
      min-height: 250px;
    }
(...)
```

**Error messages from the browser console:** None
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
Did you clear your cache?

**Comment by sstefanowski** [comment]
Hello, I don't know how to refresh the cache in the native mobile app (ver 2021.2.2-full). After every change in frontend YAML it's immediately asking for refreshment in the Mobile App. After the refreshment, the background image and some other styling (like justification) were gone.

But,... this morning I changed the YAML again adding "card_mod:" declarations again and... it is working fine(!). I checked if Mobile App was updated over the night and it was not. What happened? 
I'm pretty sure I tried this several times also with some earlier versions of card-mod (3.0.X) and it was not working - so I decided to stay with a config with plain "style:" and without "card_mod:" declarations. I couldn't see the difference. Now, when @thomasloven declared that using "card_mod:" gives some advantages in processing I decided to raise the issue.

So, what happened overnight? Was this cache was refreshed automatically?
And most important how to force refreshment of the cache in the HA Mobile App without reinstalling it?

**Comment by thomasloven** [comment]
Yes. The cache was refreshed automatically. It happens randomly every now and then.

There's a button at the very bottom of the app settings to force a refresh, for future reference.

**Comment by sstefanowski** [comment]
Hmm,

I can't see any button in HA Android App Settings to "refresh the frontend cache". Do you think of internal HA App Settings Panel?
This is the very bottom of the Settings panel in my "latest" HA App.

<img src="https://user-images.githubusercontent.com/36473471/109807274-f28ea180-7c25-11eb-9f42-5aee977a1a21.jpg" width="30%">.

**Comment by thomasloven** [comment]
Oh.
Then the apps are more different than I thought.
This is what the iOS version looks like (in Swedish)
![image](https://user-images.githubusercontent.com/1299821/109823510-4a360880-7c38-11eb-88dd-86e027cfa337.png)

The bottommost button says "Reset frontend cache".

**Comment by sstefanowski** [comment]
I deep-dived into Mobile App docs and there is a way of cache refreshment in Android by force-stoping (in App Manager) and re-launching it:
https://companion.home-assistant.io/docs/troubleshooting/faqs/

_(...)Firstly, swipe down in the iOS Companion app to refresh your view. **In the Android app force stop the application and relaunch it.** (...)_

Sorry, again for false alarm...

**Comment by KTibow** [comment]
I think you might also be able to do it in Settings > Apps > Home Assistant and hit Clear Cache.
