### ISSUE TITLE
Markdown cards are flashing when using Jinja/Template

### ISSUE THREAD

**Issue by IDmedia** [thomasloven/lovelace-card-mod#114]
**My Home Assistant version:** 2021.2.3

**My lovelace configuration method (GUI or yaml):** yaml

**What I am doing:** Adding dynamic CSS (change color based on sensor value or adding a background based on a sensor's attribute). I have the same isuse on 3.0.7 with all cards that use jinja/templates in the CSS.
I had the same issue on 2.x, but then I used "config-template-card" that mitigated the issue. For some reason that doesn't work anymore after upgrading to version 3.0.7.

**What I expected to happen:** The markdown card should render properly on first load and update itself when the value changes, apart from that stay still/not flicker.

**What happened instead:**
Adding any Jinja/template seems to cause this issue: https://youtu.be/KV-wHj89J84
The markdown card flicker in both Chrome/Firefox on PC/Android. Refreshing the page from the HA menu seems to fix the issue untill it's refreshed using F5/CTRL+F5. Clearing cache does not resolve the problem. It also doesn't always load the css. As you can see from the video the flickering is caused by the CSS being re-rendered/lost in-between updates.

```yaml
type: vertical-stack
cards:
  - type: markdown
    card_mod:
      style:
        .: |
          ha-card ha-markdown { padding: 0px !important; }
        ha-markdown:
          $: |
            div {
              display: table;
              background: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.4)), url("{{ state_attr('sensor.tibber_power_producer', 'currentProducer').imageSrc }}") no-repeat;
              background-position: center top;
              min-height: 350px;
              color: white;
              font-size: 1.2em;
              padding: 20px;
              text-align: left;
              box-shadow: var( --ha-card-box-shadow, 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12));
            }
            h2 {
              text-align: center;
            }
            table {
              margin-top: 8px;
              border-spacing: 0 0.5em;
              border-top: 1px solid rgba(255, 255, 255, 0.4);
            }
            td:first-child {
              width: 80px;
              font-weight: bold;
              vertical-align: top;
            }
    content: |
      {% set attr = state_attr('sensor.tibber_power_producer', 'currentProducer') %}
      <div>
        <h2>{{ attr.name }}</h2>
        {{ attr.description }}
        <table width=100%>
        <tr>
          <td>Owner:</td>
            <td>{{ (attr['bullets'] | selectattr('title', 'equalto', 'Owner') | list)[0].description }}</td>
        </tr>
        <tr>
          <td>Source:</td>
          <td>{{ (attr['bullets'] | selectattr('title', 'equalto', 'Source') | list)[0].description }}</td>
        </tr>
        <tr>
          <td>Terms:</td>
          <td>{{ (attr['bullets'] | selectattr('title', 'equalto', 'Terms') | list)[0].description }}</td>
        </tr>
        </table>
      </div>
```

**Error messages from the browser console:** None as far as I can see
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by al-jimenez** [comment]
I am also having this issue and it has gotten worst since 2025.11.   NOTE: I do not think it is a card_mod issue, I think it is a rendering issue with HA Lovelace & browser, specifically the markdown card and Jinja templates.  Not sure where else to post this as nothing seems related.   Below is my code which has worked for years and started to flash the Jinja code as of 2025.11 but I saw rendering issue since back in 2021 all at startup, once the page completely loads if goes away.   Here is my code. 

 ```
type: markdown
content: >-
  {% set d = now().strftime('%-I:%M') %} {% set ampm = ( now().strftime('%p')) |
  replace('AM', 'am') | replace('PM', 'pm') %}</b>  <font size=6><b>  &nbsp; {{
  d  }}</font> {{ ampm }} <p> <font size=4>{{ now().timestamp() |
  timestamp_custom("%A %B %d, %Y") }}</font>
card_mod:
  style:
    .: |
      ha-markdown {
        text-align:center;
        line-height: 10px !important;
        padding-bottom: 0px !important;
      }
      ha-card {
        text-align: center;
        background: none !important;
        border: none !important;
        box-shadow: none !important;
        line-height: 5px;
        margin: -1px 0px !important;
      }
```


Any help or pointers anyone can point me to would be appreciated.  

Thanks, Al

**Comment by dcapslock** [comment]
@al-jimenez if I understand you correctly, you are getting Jinja showing in your markdown. I tried your config on both 3.4.6 and 4.0.0-beta.6 and it works fine. Does the issue happen if you remove card_mod? Are you using themes? It may be that card_mod causes markdown reload and somehow this causes a render issue. I have briefly checked the markdown code and can't see anything particular that would point to an issue.

Whemeber users have strange issues I recommend to check how you are loading card_mod. if you are using Frontend module, make sure that the URL matches EXACTLY what you have in Dashboard resource. Check [v4 instructions](https://github.com/thomasloven/lovelace-card-mod/tree/v4.0#performance-improvements) (also applicable to v3) for more information.

**Comment by dcapslock** [comment]
@al-jimenez also, users are reporting [issues](https://github.com/home-assistant/frontend/issues/27897) with markdown cards on older iPads. Maybe this is related to your issue?
