### ISSUE TITLE
Hello, regarding changing the popup background image, hope can help me out.

### ISSUE THREAD

**Issue by horacecar** [thomasloven/lovelace-card-mod#115]
I would like to know which variable to change the background image of the popup window(using browser mod). i have tried the variable below but still fail. once changed the background image, when click the popup, the background image will move, please see the video that i uploaded.

https://user-images.githubusercontent.com/44496483/110235408-c39c6680-7f6a-11eb-9b26-acec9df7f02c.mp4
![_20210307172952](https://user-images.githubusercontent.com/44496483/110235410-c5662a00-7f6a-11eb-9b79-063ad8c7d302.jpg)

          card_mod:
            style: |
              :host {
                --card-background-color: var(--background-image);
                  }

              ha-card {
                background: var(--background-image);
              }

**Comment by KTibow** [comment]
This should go in the forums.
