### ISSUE TITLE
Recent changes have broken the transparentblue theme

### ISSUE THREAD

**Issue by danielbrunt57** [thomasloven/lovelace-card-mod#117]
My Home Assistant version: 2020.3.3

My lovelace configuration method (GUI or yaml): GUI

What I am doing: 
Selecting transparentblue theme for a View.  
Also does not work if it's applied as a Profile or Card theme.
What has been broken is the 'on' color state for the icons.

What I expected to happen:
![image](https://user-images.githubusercontent.com/49846893/110711258-17e65700-81b4-11eb-8e43-e6f8982fad1a.png)

What happened instead:
![image](https://user-images.githubusercontent.com/49846893/110711183-f5ecd480-81b3-11eb-99de-0bee9b10fb09.png)

**Minimal** steps to reproduce:
Install transparentblue theme and activate.

```yaml
theme: transparentblue
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Fixed in 3.0.10
