### ISSUE TITLE
Card mod cant color icons for unavailable icons

### ISSUE THREAD

**Issue by comet424** [thomasloven/lovelace-card-mod#121]
so i running latest HA  
and i can not get card mod to display Blue 
for unavailable state...  the card is over written by green default.. i made a post on HA page 
but the was told to read here .. but i try to incorporate yours 
change  options: to  card_mod:   
but that didnt work before and still doesnt work 
i not sure if its a bug or what else i need to write.. picture is on there too to show color not working
and if its not a bug  my bad..    i sorry..  i been stuck a couple of weeks now

https://community.home-assistant.io/t/cant-seem-to-get-custom-card-icon-color-to-work-right/292961/7

**Comment by thomasloven** [comment]
# 1
![image](https://user-images.githubusercontent.com/1299821/112438994-de335580-8d48-11eb-9dbe-af445c7323bf.png)
# 2
![image](https://user-images.githubusercontent.com/1299821/112439176-15a20200-8d49-11eb-953e-29e9744bcc96.png)
# 3
![image](https://user-images.githubusercontent.com/1299821/112439111-0327c880-8d49-11eb-8158-480b9a5a93c1.png)
