### ISSUE TITLE
Card mod cant color icons for unavailable icons 

### ISSUE THREAD

**Issue by comet424** [thomasloven/lovelace-card-mod#123]
My Home Assistant version: 0.XX.X
2021.3.4
My lovelace configuration method (GUI or yaml):
both
![ha1](https://user-images.githubusercontent.com/75998611/112481846-d0cc9a00-8d4d-11eb-832d-2e51e851bb0c.PNG)
was able to add the pic  as you can see colors dont work for unavailable  to turn blue

What I am doing:
trying the change color of icon devices unavailable. 

What I expected to happen:
to change blue

What happened instead:
defaults to system  color     it only works with Fake unavailable devices not true unavailable devices
will only turn blue if its an actual device..  colors do work if its a not fake unavailable device

**Minimal** steps to reproduce:
copy and paste the code
and follow the link i provided.. sine that only way youll understand if this is a glitch bug or you havent provided right documentation  i dunno
https://community.home-assistant.io/t/cant-seem-to-get-custom-card-icon-color-to-work-right/292961/7
changing from options: to card_mod:  does absolutely nothing.. and from the link i provided  
you can then understand the issue since has pictures and the code which you cant do here
cuz your code only works for Fake unavailiable devices not true unavailable devices
tried different way of doing..  unless you can direct me to say its not a bug and how to work for true unavailiable devices
as like i stated   ..  do no know if this is a bug.. or if there is documentation that isnt provided to work around this issue
and this is not a help question for home assistatnt.. considering no one can help me fix  this error i having.
so you can see in the code  first one is setup right.. second entity is setup Fake mode...  but when truely unavailable it wont work

```yaml
# The least amount of code possible to reproduce my error
my card code is

Copy to clipboard
type: entities
entities:
 
  - entity: sensor.b_modem_state
    name: Modem State
    icon: 'mdi:laptop'
    card_mod: 
    style: |
      :host {
      --paper-item-icon-color: 
      {% if states(config.entity) == 'on' %} 
        yellow
      {% elif states(config.entity) == 'off' %}
        green
      {% else %}
        blue
      {% endif %}
      ;
      }  
  - entity: sensor.b_modem_state
    name: Modem State
    icon: 'mdi:laptop'
    card_mod: 
    style: |
      :host {
      --paper-item-icon-color: 
      {% if states(config.entity) == 'on' %} 
        yellow
      {% elif states(config.entity) == 'offf' %}
        green
      {% else %}
        blue
      {% endif %}
      ;
      }  
  # End of code
```

Error messages from the browser console:

no error message doesnt work properly  for unavailiable devices
unless you have more documentation that isnt docummented for me to copy and paste

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Unavailable entities probably don't use `--paper-item-icon-color`. You'll have to look up the correct variable to use.

Of try the special `--card-mod-icon-color` variable. https://github.com/thomasloven/lovelace-card-mod#changing-icons

**Comment by comet424** [comment]
ya i already tried that..
these 2  do not work.
--card-mod-icon-color
--paper-item-icon-color

where is a list of your variables  for me to try copy and paste in there
