### ISSUE TITLE
Usage support: apply CSS to card title

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-card-mod#133]
I try to apply some custom style to the title area of a (entities) card. Unfortunately this isn´t working, all style changes are "only" applied to the card below the title area.

![grafik](https://user-images.githubusercontent.com/13799156/123311303-4bf94400-d527-11eb-8c5b-4cf293ebaef6.png)

How to modify a card´s title? Basically I just want to center a cards title instead of having it aligned left.

Do I need to fake a title somehow to modify it or is there another, more easy way?

**Comment by thomasloven** [comment]
Github is for bug reports and feature requests, not usage support.
Ask in the community forums or check the links from the wiki.
