### ISSUE TITLE
'if config.entity is none' template doesn't work

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#134]
My Home Assistant version: 2021.6.6

My lovelace configuration method (GUI or yaml):
YAML
What I am doing:

trying to have a conditional badge, templating on existence of the config.entity

```
  - entity: sensor.state_badge
    card_mod:
      style: |
        :host {
          display: {% if config.entity is none %}none{%endif%}
        }
```
Also tried` {% if not config.entity %}` and `{% if config.entity not is defined %}`

What I expected to happen:

don't display the badge if the entity doesn't exist (yet)

What happened instead:

<img width="79" alt="Schermafbeelding 2021-06-29 om 10 00 31" src="https://user-images.githubusercontent.com/33354141/123767214-997b0580-d8c7-11eb-92c9-35a06acca0a3.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - entity: sensor.state_badge
    card_mod:
      style: |
        :host {
          display: {% if config.entity is none %}none{%endif%}
        }

# End of code
```

Error messages from the browser console:
```
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector')
```
---

though the above error also shows on correct badges, and I have reported that in another issue

please also see a [community post](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1927?u=mariusthvdb).

as an example:
```
    card_mod:
      style: |
        :host {
          display: {% if states('binary_sensor.updater') == 'off' %} none {% endif %}
        }
```

works perfectly.

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
`{% if config.entity is undefined %}none{%endif%}`

`{% if config.entity is not defined %}none{%endif%}`

**Comment by Mariusthvdb** [comment]
really sorry, but I did also try that, and it just doesn't work, resulting in a top level badge still being displayed (never mind the formatting)

<img width="76" alt="Schermafbeelding 2021-06-30 om 08 19 33" src="https://user-images.githubusercontent.com/33354141/123911324-f2a47100-d97b-11eb-95c8-273ee1372348.png">

this however does work:
```
{% if states(config.entity) == 'unknown' %} display: none {% endif %}
```

so unlike anywhere else in Jinja templates, with this card_mod, we somehow can not check for the states entity, but can only do so with the states state.

**Comment by adulovic** [comment]
Seems related, so I won't open a new issue...
Using card-mod in a theme, my error log gets filled with hundreds of
`ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'entity' when rendering`
Seems that this is generated for every row without an entity and I have many such rows.
Two examples that immediately come to mind: `- type: divider` and `- type: custom:template-entity-row`

**Comment by adulovic** [comment]
A simple solution to the OP's issue could be to set `display: none;` as a default, then use `if states(config.entity)` to change it to `display: block;` or whatever else he needs.

**Comment by Mariusthvdb** [comment]
Id rather use 
```
{% if states(config.entity) == 'unknown' %} display: none {% endif %}
```
which does work, but is avoiding the issue at hand (simply by the states() that always returns 'unknown' on non existing entity states. In this case that is the true issue, and I believe Thomas re-openend because of that.

About your issue, I fear it is another matter after all, simply because you get a template error (and in my case there is no error at all). You should probably check (and guard) your templates. Divider doesn't throw an error.

**Comment by Mariusthvdb** [comment]
no happening in my config anymore, should we close?

**Comment by Zerwin** [comment]
I had it still happen for me, but my solution was just to follow what was done here by ildar, even though I wasn't using rows but cards.
https://github.com/thomasloven/lovelace-card-mod/issues/180#issuecomment-1106890949

I noticed it even happened when I was using a blank dashboard and then tried adding a card. 
Maybe the template tries to apply also to cards in the editor ? Which would of course not have any config.entity

**Comment by ildar170975** [comment]
> Maybe the template tries to apply also to cards in the editor

Do not think so. I observed this error even for dashboards in yaml mode (i.e. not available to be edited in UI).
Also, I do not remember exactly whether these errors occurred on HA startup or after.

> to cards in the editor ? Which would of course not have any config.entity

Why? IMHO the "config.entity" variable works in a card opened in Editor too.

**Comment by Zerwin** [comment]
For me they occurred every time I opened the edit dashboard menu, and sometimes even just by opening a dashboard with cards in it.

> Why? IMHO the "config.entity" variable works in a card opened in Editor too.

I didn't mean a card that is opened in the editor, but pressing the edit dashboard -> Add card button, and then the list of cards that pop up, sorry if that was unclear. Some of these cards seemed to have triggered it for me, and I don't think these cards, which aren't even added to the dashboard yet, have any type of entity.

**Comment by skynet01** [comment]
I tried wrapping config.entity... in **_states(config.entity)_** and it's not working for me. Anyone know why I am getting this error? The code works fine and my fans rotate properly would be great to fix the error below.

Error:
`Template variable error: 'dict object' has no attribute 'entity' when rendering '@keyframe spin...`

Theme file:
```
  card-mod-row-yaml: |
    "*:first-child$": |
      @keyframes spin {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(359deg);
        }
      }
      state-badge {
            {% if config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 15 %}
                animation: spin 4s infinite linear;
            {%- elif config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 33 %}
                animation: spin 3s infinite linear;    
            {%- elif config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 67 %}
                animation: spin 1.5s infinite linear;
            {%- elif config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 100 %}
                animation: spin 0.75s infinite linear;    
            {%- else -%}
                animation-duration: 0s;
            {%- endif %}
      }
      
```

**Comment by Mariusthvdb** [comment]
this would be more for the community probably, since your having a templating question, but anyways, you'd be better off simplifying like:
```
            {% set fan = 'fan.luchtreiniger_woonkamer' %}
            {% set test = fan.startswith('fan.') and is_state(fan, 'on') %}
            {% if test %}
              {% if state_attr(fan, 'percentage') | int <= 15 %}
                animation: spin 4s infinite linear;
              {%- elif state_attr(fan, 'percentage') | int <= 33 %}
                animation: spin 3s infinite linear;    
              {%- elif state_attr(fan, 'percentage') | int <= 67 %}
                animation: spin 1.5s infinite linear;
              {%- else  %}
                animation: spin 0.75s infinite linear;    
              {% endif %}
            {%- else -%}
                animation: none;
            {%- endif %}
```
(ofc replace the verbose entity I used for testing with config.entity)
and then check the error. You didnt completely post the logged error, so that would help too

**Comment by ildar170975** [comment]
@skynet01 

I tested exactly same code you posted, just added `color`:
```
cm_test_test:

  card-mod-theme: cm_test_test

  card-mod-row-yaml: |
    "*:first-child$": |
      @keyframes spin {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(359deg);
        }
      }
      state-badge {
            {% if config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 15 %}
                animation: spin 4s infinite linear;
                color: cyan;
            {%- elif config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 33 %}
                animation: spin 3s infinite linear;    
                color: lightgreen;
            {%- elif config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 67 %}
                animation: spin 1.5s infinite linear;
                color: orange;
            {%- elif config.entity.startswith('fan.') and is_state(config.entity, 'on') and state_attr(config.entity, 'percentage') | int <= 100 %}
                animation: spin 0.75s infinite linear;    
                color: red;
            {%- else -%}
                animation-duration: 0s;
            {%- endif %}
      }
```
Test card:
```
type: entities
entities:
  - entity: input_number.test_level_1
    name: speed
  - type: section
  - entity: fan.virtual_fan_kitchen_test
  - type: attribute
    entity: fan.virtual_fan_kitchen_test
    attribute: percentage
  - type: custom:hui-element
    card_type: markdown
    content: |
      <=15 - cyan
      <=33 - lightgreen
      <=67 - orange
      <=100 - red
```
Test automation:
```
mode: single
trigger:
  - platform: state
    entity_id:
      - input_number.test_level_1
action:
  - service: fan.set_percentage
    data:
      percentage: >-
        {{ states('input_number.test_level_1') | int }}
    target:
      entity_id: fan.virtual_fan_kitchen_test
```
It works fine, no errors in Code Inspector:
![cm1](https://user-images.githubusercontent.com/71872483/221549576-dc1a062c-731b-438f-8848-80a0a6a7fd5e.gif)
HA 2023.2.5, Chrome, Win10

**Comment by skynet01** [comment]
Both codes do work and so does mine but when the theme loads (I load it through the theme)  I get the error in the logs.  I get the same error when using your code @Mariusthvdb as well (even though it does work).

`Template variable error: 'dict object' has no attribute 'entity' when rendering 'state-badge { animation: {% if is_state(config.entity,'on') %} {% set perc = state_attr(config.entity,'percentage')|int %} {% if perc <= 15 %} rotation 4s infinite linear, colorize 5s linear forwards 1; {%- elif perc <= 33 %} rotation 3s infinite linear, colorize 5s linear forwards 1; {%- elif perc <= 67 %} rotation 1.5s infinite linear, colorize 5s linear forwards 1; {%- else %} rotation 0.75s infinite linear, colorize 5s linear forwards 1; {% endif %} {% else %} none; {% endif %} } @keyframes rotation { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }'`

**Comment by ildar170975** [comment]
Fine, but seems you have not understood that `config.entity` may not work and hence can break your styles).
OK, find it by yourself.

**Comment by skynet01** [comment]
I saw that as well, I made modifications but I was still getting an error. So now both issues are fixed with Marius' help.

**Comment by Mariusthvdb** [comment]
this is even more fun:
```
              animation: {% if is_state(config.entity,'on') %}
                         {% set perc = state_attr(config.entity,'percentage')|int %}
                         {% set base = 'rotation infinite linear, colorize 5s linear forwards 1' %}
                         {% if perc <= 15 %} 4s {{base}};
                         {%- elif perc <= 33 %} 3s {{base}};
                         {%- elif perc <= 67 %} 1.5s {{ base}};
                         {%- else  %} 0.75s {{base}};
                         {% endif %}
                         {% else %} none;
                         {% endif %}
```

**Comment by skynet01** [comment]
Bonus: have the spinning slow down / speed up to the speed set instead of just switching between states 😂

**Comment by skynet01** [comment]
After the latest update the error seem to have came back again. Any ideas? 

```
2023-03-06 12:29:41.794 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'entity' when rendering 'state-badge {
      animation: {% if is_state(config.entity,'on') %}
                 {% set perc = state_attr(config.entity,'percentage')|int %}
                 {% if perc <= 15 %} rotation 4s infinite linear, colorize 5s linear forwards 1;
                 {%- elif perc <= 33 %} rotation 3s infinite linear, colorize 5s linear forwards 1;
                 {%- elif perc <= 67 %} rotation 1.5s infinite linear, colorize 5s linear forwards 1;
                 {%- else  %} rotation 0.75s infinite linear, colorize 5s linear forwards 1;
                 {% endif %}
      {% else %} none;
      {% endif %}
    }
    @keyframes rotation {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(360deg);
      }
    }'
```

**Comment by ildar170975** [comment]
Your style was applied to a card which does not have "config.entity" variable defined.

**Comment by skynet01** [comment]
anyway to update the above to fix it.

**Comment by ildar170975** [comment]
https://github.com/thomasloven/lovelace-card-mod/issues/257#issuecomment-1446227419

**Comment by skynet01** [comment]
Thank you, surrounding it with if statement fixed it. Don't know why I didn't think of that. Thank you so much for the help!

**Comment by thomasloven** [comment]
Could someone update me on the status of this one?

Looking at it now, the code in the first post is missing a `;`.

**Comment by Mariusthvdb** [comment]
As said earlier : not seeing this anymore
