### ISSUE TITLE
Changes to card-mod-more-info-yaml stopped working

### ISSUE THREAD

**Issue by v-alvex** [thomasloven/lovelace-card-mod#136]
Home Assistant version: 2021.7.0

**Card mod theme** changes to ha-more-info-dialog, stopped applying to more-info dialogs after the last HA updates, as they used to.
They now only apply to custom browser mod's popups.
[https://github.com/thomasloven/lovelace-card-mod/wiki/Card-mod-Themes#special-theme-variables](url)

```yaml
  card-mod-more-info-yaml: |
    .: |  
        .mdc-top-app-bar {
            display: none !important;
        }  
    $: |
      .mdc-dialog {
        backdrop-filter: blur(5px);
        box-shadow: 0px 0px 0px 0px;
        padding-top: 40px
            
      }
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
          box-shadow: 0px 0px 0px 0px;
          border-radius: 15px;        
        }
    .: |
        :host {
          --secondary-background-color: none;
        }   
```

Error messages from the browser console:

Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at HTMLElement.e.showDialog (card-mod.js:5)
    at o (app.62541dd1.js:34265)
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by hankanman** [comment]
Can confirm this is still an issue in 2021.9.6
![Screenshot 2021-09-12 152849](https://user-images.githubusercontent.com/3953290/132991580-803e8d1e-0013-474b-a764-be4df2c292b5.png)

**Comment by shahonseven** [comment]
I have the same problem

**Comment by thomasloven** [comment]
Cannot reproduce in version 3.4.0.
Please check and open a new issue if the problem persists.
