### ISSUE TITLE
HACS not acceting custom repo

### ISSUE THREAD

**Issue by pw44** [thomasloven/lovelace-card-mod#138]
Hi,

tried to add https://github.com/thomasloven/lovelace-card-mod to HACS repositories, not luck.

Any hint?

**Comment by LittleBigDev** [comment]
Same for me.
I'll wait for update in this issue :)

**Comment by thomasloven** [comment]
HACS doesn't accept custom repos that are already in the default repo.
Check under "Frontend".

**Comment by LittleBigDev** [comment]
@thomasloven thanks for your answer

I'm not able to find your add on under "Frontend". What keyword should I look for ?

**Comment by LittleBigDev** [comment]
Ok sorry. I WAS NOT able. Like.. 3 hours ago.

Now I checked again and I was able to find your repo (I searched "card-mod").
