### ISSUE TITLE
Styling of rows with custom types stopped working

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#146]
My Home Assistant version: 2020.10.6

My lovelace configuration method (GUI or yaml): GUI, yaml

What I am doing:
Trying to apply a style to a row (Entities card) with:
- `config-template-card` 
- `restriction-card`
- `fold-entity-row`.

What I expected to happen:
Styles are applied.
Earlier it worked:
- for `config-template-card`- https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1328
- for `restriction-card` - no example
- for `fold-entity-row` - https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1192

What happened instead:
No styles applied.

**Minimal** steps to reproduce - for `config-template-card`:
```
type: entities
title: config-template (row)
entities:
  - type: custom:config-template-card
    entities:
      - sun.sun
    row:
      entity: sun.sun
      name: config-template
    style: |
      :host {
        color: green;
      }
  - type: custom:config-template-card
    entities:
      - sun.sun
    row:
      entity: sun.sun
      name: config-template
    style:
      hui-text-entity-row:
        $: |
          hui-generic-entity-row .text-content {
            color: orange;
          }
```
![image](https://user-images.githubusercontent.com/71872483/138599848-5a4fbecf-ecaa-4468-85a5-9bfaf8ead6bf.png)

Error messages from the browser console:
none

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Same is with styling `fold-entity-row` - stopped working.
This code used to change value's color.
```
type: entities
entities:
  - type: custom:fold-entity-row
    card_mod:
      style:
        hui-text-entity-row:
          $:
            hui-generic-entity-row: |
              .text-content.pointer {
                color: red;
              }
        '#items':
          hui-text-entity-row:
            $:
              hui-generic-entity-row: |
                .text-content.pointer {
                  color: red;
                }
    head:
      entity: sun.sun
      name: common color
    padding: 15
    open: true
    entities:
      - entity: sun.sun
        name: common color
      - entity: sun.sun
        name: common color
```
![изображение](https://user-images.githubusercontent.com/71872483/140614324-f850d055-6ac0-47cb-b4f8-df69bffc3728.png)

**Comment by DavidFW1960** [comment]
Is there a workaround for this? I am using decluttering card and template as well and it's disappeared. It's the one you helped me with a long time ago and now it's blank.

**Comment by ildar170975** [comment]
Hi David, DM me about this card, will see if I can help

**Comment by ildar170975** [comment]
Solved the problem at least for `restriction-card`:
```
      - type: entities
        entities:
          - type: custom:restriction-card
            row: true
            card:
              entity: sun.sun
              name: hui-simple-entity-row
              secondary_info: last-changed
            card_mod:
              style:
                hui-simple-entity-row $:
                  hui-generic-entity-row $: |
                    .text-content:not(.info) {
                      color: magenta;
                    }
```
![image](https://user-images.githubusercontent.com/71872483/231251728-0b4eb3e3-2e95-4b6a-9b86-e01a3ba657b5.png)

Gonna check it for `config-template-card` & `fold-entity-row` then.

**Comment by ildar170975** [comment]
Solved for `fold-entity-row` (case described [here](https://github.com/thomasloven/lovelace-card-mod/issues/146#issuecomment-962464924)):
```
  - type: entities
    entities:
      - type: custom:fold-entity-row
        card_mod:
          style:
            div#head :first-child:
              $ hui-generic-entity-row $: |
                .info {
                  color: red;
                }
            div#items :first-child:
              $ hui-generic-entity-row $: |
                .info {
                  color: cyan;
                }
        head:
          entity: sun.sun
        padding: 15
        open: true
        entities:
          - entity: sun.sun
            name: common color
          - entity: zone.home
            name: common color
          - entity: sensor.processor_use
            card_mod:
              style:
                hui-generic-entity-row $: |
                  .info {
                    color: magenta !important;
                  }
          - entity: input_boolean.test_boolean
            name: common color
```
![image](https://user-images.githubusercontent.com/71872483/231294968-6499c7d3-63e8-452f-8196-25ae20ee6a80.png)

**Comment by ildar170975** [comment]
So, currently cannot solve the 1st case with `config-template-card` ([here](https://github.com/thomasloven/lovelace-card-mod/issues/146#issue-1034437822))

**Comment by ildar170975** [comment]
Closing the issue.

The example from the 1st post with `config-template-card` works:
```
type: entities
title: config-template (row)
entities:
  - type: custom:config-template-card
    entities:
      - sun.sun
    row:
      entity: sun.sun
      name: config-template
    card_mod:
      style: |
        :host {
          color: red;
        }
  - type: custom:config-template-card
    entities:
      - sun.sun
    row:
      entity: sun.sun
      name: config-template
    card_mod:
      style:
        div#card :first-child $ hui-generic-entity-row $: |
          .info {
            color: orange;
          }
```
![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/19bfdd28-3f31-4617-904d-4f7e2421de72)

**Comment by KameDomotics** [comment]
I used this code to color only the sensor value, now it doesn't work anymore and the text remains white.
(I used it in card entities)

```

    card_mod:
      style: |
        .text-content {
          color: rgb(128, 200, 132);
          
        }
```

Is there a solution to get it working again?
Thanks
