### ISSUE TITLE
card_mod style stopped working

### ISSUE THREAD

**Issue by PierreScerri** [thomasloven/lovelace-card-mod#150]
Hi

Style stopped working after updating to HA 2021.11.0.
Tried both methods shown.

The button 'Pay 0.18€' used to be red.  The other buttons in this card had formatting that has also stopped working.

![Screenshot 2021-11-04 at 12 43 06](https://user-images.githubusercontent.com/34303331/140307845-13b0483d-a46e-4bbb-a1ba-23270505212f.png)
![Screenshot 2021-11-04 at 12 42 44](https://user-images.githubusercontent.com/34303331/140307861-b4fdcd33-4f9b-4131-8535-2aa6586676bd.png)

What am i missing?

**Comment by tteck** [comment]
Going back to version 3.0.12 fixed this issue for me.

**Comment by PierreScerri** [comment]
Actually, I just refereshed the browser and and restarted HA and it is now fine.
