### ISSUE TITLE
Style syntax ignored when a theme is set

### ISSUE THREAD

**Issue by vulcablack** [thomasloven/lovelace-card-mod#155]
My Home Assistant version: 2021.11.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Setting active state color for button icons

What I expected to happen: Color to change when entity is active

What happened instead: Nothing, when "theme" is set

**Minimal** steps to reproduce:

- type: button
   entity: group.office
   tap_action:
     action: navigate
     navigation_path: office
    hold_action:
      action: toggle
    name: Office
    show_name: false
    theme: Dark Mono
    style: |
      :host {
        {%if is_state('group.office', 'on') %} 
           --state-icon-active-color: #1a8cff;
         {% endif %};
        }

Error messages from the browser console: Object { code: "template_error", message: "TemplateSyntaxError: expected token 'end of statement block', got 'if'" }

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Try ```yaml
card_mod:
  style: |
    ...``` instead.

**Comment by ildar170975** [comment]
> * type: button

I think you should not use `:host` for button.
Use ha-card instead.
