### ISSUE TITLE
Test command does not work on Raspberry PI

### ISSUE THREAD

**Issue by matteobrusa** [thomasloven/lovelace-card-mod#156]
My Home Assistant version: core-2021.10.6

What I am doing:
Starting the docker demo on a Raspberry Pi

What I expected to happen:
The server becomes available on port 8125

What happened instead:

$ docker-compose up
Starting test_test_1 ... done
Attaching to test_test_1
test_1  | standard_init_linux.go:228: exec user process caused: exec format error
test_test_1 exited with code 1

**Minimal** steps to reproduce:
git clone the repo, move to the test folder, run the above command.

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Sounds like a problem with your docker setup.
I do not recommend using a raspberry pi for developing the card-mod plugin, though...
