### ISSUE TITLE
NotSupportedError: Cannot define multiple custom elements with the same tag name

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-card-mod#161]
My Home Assistant version: 2021.11.5

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Loading a view containing mod-card elements after upgrading to Card-Mod v3.1.1

What I expected to happen: Nothing in HA log

What happened instead: An error is logged to the HA log file

**Minimal** steps to reproduce:

```yaml
type: custom:mod-card
...
```

Error messages from the browser console:
This is from HA log file:
```
Logger: frontend.js.latest.202111090
Source: components/system_log/__init__.py:190
First occurred: 11:05:47 (19 occurrences)
Last logged: 11:49:27

http://ha:8123/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524310:6:32933 NotSupportedError: Cannot define multiple custom elements with the same tag name
http://ha:8123/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:34168 NotSupportedError: Cannot define multiple custom elements with the same tag name
http://ha:8123/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:0 NotSupportedError: CustomElementRegistry.define: 'mod-card' has already been defined as a custom element
```

I am not 100 % sure if this was introduced with card-mod v3.1.x - but I think so.

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by dsegantx** [comment]
I did remove it from Configuration -> LovelaceDashboards -> Resources and restarted and error went away.

So my experience says yes remove it.
