### ISSUE TITLE
Stuck at "Loading Data"

### ISSUE THREAD

**Issue by vantop77** [thomasloven/lovelace-card-mod#164]
My Home Assistant version: 2021.11.4

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Home page (lovelace dashboard is not opening). Stuck at loading data on computer browser and android app.
I am not sure the problem is coming from "Lovelace-card-mod" but the browser console is mentioning it.
What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
lovelace:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://192.168.0.30:8123/config/www/community/lovelace-card-mod/card-mod.js
:8123/lovelace:1 Uncaught (in promise) {code: 'unknown_error', message: 'Invalid JSON in response'}
Promise.catch (async)
d @ core.2fe29b5a.js:1
subscribe @ core.2fe29b5a.js:1
h @ core.2fe29b5a.js:1
(anonymous) @ core.2fe29b5a.js:1
Promise.then (async)
(anonymous) @ core.2fe29b5a.js:1
(anonymous) @ core.2fe29b5a.js:1
(anonymous) @ core.2fe29b5a.js:1
```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
I'm not sure this is actually related to card-mod either. Is it still an issue?

**Comment by vantop77** [comment]
Nope, it is not an issue any more, it was easier for restoring from backup than resolving it
