### ISSUE TITLE
Elements in mod-card isn't updated

### ISSUE THREAD

**Issue by Farfar** [thomasloven/lovelace-card-mod#17]
When using mod-card, the elements inside isn't updated when HomeAssistant refreshes entities.
Tested with identical cards placed independently and inside a mod-card within the same view. The independent card will update entities, graphs and such, but within the mod-card everything is static.

**Comment by Krocko** [comment]
I have the same problem.
Did you found a solution?

**Comment by Farfar** [comment]
> I have the same problem.
> Did you found a solution?

No I ended up using vertical style card instead since it was a vertical stack I needed to modify the style for.
