### ISSUE TITLE
TOP SECRET

### ISSUE THREAD

**Issue by idoaflalo** [thomasloven/lovelace-card-mod#170]
I see what you did here 😂

https://github.com/thomasloven/lovelace-card-mod/blob/94d4fbcb3d550caa1eaf4471db803c0dbdb3ea6f/src/card-mod.ts#L191

**Comment by tomlut** [comment]
I don't get it.

**Comment by tomlut** [comment]
Now I get it.

**Comment by susanacf90** [comment]
> I see what you did here 😂
> 
> https://github.com/thomasloven/lovelace-card-mod/blob/94d4fbcb3d550caa1eaf4471db803c0dbdb3ea6f/src/card-mod.ts#L191

I admire your patience on checking the whole code for kicks. 😂
