### ISSUE TITLE
error when using as frontend module: name "mod-card" has already been used with this registry

### ISSUE THREAD

**Issue by ktownsend-personal** [thomasloven/lovelace-card-mod#174]
My Home Assistant version: 2021.12.8

My lovelace configuration method (GUI or yaml): yaml

What I am doing: configuring card-mod as frontend module

What I expected to happen: no errors

What happened instead:
This error in browser, plus a corresponding log entry:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mod-card" has already been used with this registry
    at http://homeassistant:8123/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:10674
```
**Minimal** steps to reproduce:
* Install card-mod 3.1.1 via HACS
* edit configuration.yaml to load card-mod as frontend module
* observe error message in browser console when reloading dashboard

```yaml
# The least amount of code possible to reproduce my error
frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url: /hacsfiles/lovelace-card-mod/card-mod.js
# End of code
```

Error messages from the browser console:
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mod-card" has already been used with this registry
    at http://homeassistant:8123/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:10674

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by allflame** [comment]
I'm having this issue when using mixed mode configuration, e.g.
```
lovelace:
  mode: storage
  resources:
    ...
    /hacsfiles/lovelace-card-mod/card-mod.js
    ...
  dashboards:
    my-dashborad:
      mode: yaml
```
IF i switch to complete manual mode, problem disappears

Maybe this helps

**Comment by michapr** [comment]
I have same issue (with same link in error message).
And I do not used "mixed configuration" (all in manual mode).

Thanks for help!

**Comment by Stooovie** [comment]
Same issue

**Comment by florianec** [comment]
I have the same error but it seems "expected" 

> The error can be safely ignored. I'll make sure it's removed for the next release.

_Originally posted by @thomasloven in https://github.com/thomasloven/lovelace-card-mod/issues/159#issuecomment-975350355_

**Comment by thomasloven** [comment]
Should be gone now.

**Comment by ktownsend-personal** [comment]
@thomasloven thank you. It appears resolved for me.

**Comment by shred86** [comment]
Unfortunately still receiving this same exact error. This is with using a [lovelace design](https://github.com/matt8707/hass-config) by matt0707.

card-mod was installed through HACS. The only slight difference I see is:
````
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
````
This is defined in include/themes.yaml instead of the configuration.yaml file, but as far as I know, that shouldn’t matter.
