### ISSUE TITLE
Change font-size and numbers of decimals

### ISSUE THREAD

**Issue by AndersHub** [thomasloven/lovelace-card-mod#178]
I don't understand if I shall choose Card-mod or template then I want to change font-size and decimals in an Entity card. And I have tried both methods but no success so far. Just in this example, I try to get the "average" attribute from Nordpool. I can i.e change color but not size and round to 3 decimals. 
I will appreciate an answer with recommendations and code.

**Comment by ildar170975** [comment]
> change font-size

https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1186



> round to 3 decimals

Create template sensor for the attribute.

Close the issue if you are satisfied with the proposed solutions.
