### ISSUE TITLE
#enhancement - Add Support for one click "Add to Lovelace" link in HACS

### ISSUE THREAD

**Issue by cdrom1028** [thomasloven/lovelace-card-mod#18]
Please add support for one click "Add to Lovelace" link in HACS. 

I recently set up a new HassOS test instance VM and I noticed HACS was added by default. I needed to get card-mod installed but for what ever reason, it was quite a bit more difficult than setting up most of my other plugins. With these other plugins a Link was provided via HACKS that added the entry into the "resources:" config of Lovelace and made the install effortless.

With HomeAssistant growing so quickly, this functionality would be awesome to add especially for new users. Additionally many of the popular plugins already support the "add to Lovelace" function.

FYI: the proper url listed in the install guide [here](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#3-import-the-plugin-in-your-lovelace-config) is wrong as the module is no longer card-modder.js

**Comment by thomasloven** [comment]
The card used in the install guide is an example and is unrelated to lovelace-card-mod.
