### ISSUE TITLE
Question: Use conditional row in entities card with card-mod

### ISSUE THREAD

**Issue by loeffelpan** [thomasloven/lovelace-card-mod#182]
I'm trying to use your card-mod with an entities card displaying an conditional row.
Styling doesn't work. I think this is because there is no `ha-card` in those rows (like in conditional card as well).
For any card without `ha-card` you provide `custom:mod-card` to create that object and make styling possible.

Any way to do that for rows without `ha-card`?
Or any other workaround?

**Comment by ildar170975** [comment]
community thread -> 1st post -> link at the bottom -> post with examples -> link for conditional row

It is better to ask similar questions a the community thread first and leave Github for bugs and FRs

**Comment by loeffelpan** [comment]
Okay, I will use community thread in future.
Thanks for your help.
