### ISSUE TITLE
mod-card not installed through hacs

### ISSUE THREAD

**Issue by JesseWebDotCom** [thomasloven/lovelace-card-mod#19]
Looks like the hacs install does not install mod-card (which I attempted to use to change a horizontal-stack style).  How should I proceed?

**Comment by Teryeahh** [comment]
Same here. will you fix this @thomasloven ? or should we manually download it?

**Comment by thomasloven** [comment]
What makes you say that?

**Comment by JesseWebDotCom** [comment]
Here are the steps I took:
- Installed card mod through HAC 
- Added card-mod.js as a module in my Lovelace file
- Added the exact example from the Mod-Card README section

Which results in the error **Custom element doesn't exist: mod-card.**

**Comment by JesseWebDotCom** [comment]
Also, these are the files that get installed through HACS (under www/community/lovelace-card-mod/):
- card-mod.js
- card-mod.js.gz
- web pack.config.js
- web pack.config.js.gz

Note: This is the first time I'm using your mod-card.  Perhaps the documentation is wrong or I'm doing something wrong.

**Comment by Teryeahh** [comment]
![Screenshot_2019-12-31-11-00-31-444_io homeassistant companion android](https://user-images.githubusercontent.com/38291038/71617755-ceb47380-2bbc-11ea-94f6-e4f6ac243451.jpg)
Hi.

I'm also getting an error like you see on the pic. Followed the instructions.

**Comment by dannyhanes** [comment]
A couple little things I noticed as well. 

**No Option to to Lovelace Config**
<img width="443" alt="Screen Shot 2020-01-02 at 11 13 36 AM" src="https://user-images.githubusercontent.com/3778687/71677507-048a6100-2d51-11ea-8459-bf1e1e514c22.png">

**Looks Like Incorrect Type Listed in HACS**
<img width="540" alt="Screen Shot 2020-01-02 at 11 13 41 AM" src="https://user-images.githubusercontent.com/3778687/71677576-2daaf180-2d51-11ea-9033-82450da5063d.png">

**Comment by thomasloven** [comment]
@Teryeahh 
That's a completely different error from what's discussed here.
The error message is very clear. Indentation matters.

**Comment by thomasloven** [comment]
@JesseWebDotCom Please post anything you found in the browser log while you stepped through the troubleshooting guide linked from the readme.

**Comment by IanAdd** [comment]
I had this problem and found the solution to be:
The README.MD page says add:
resources:
  - url: /local/card-mod.js
    type: module
DO NOT DO THIS
Instead add the following which is shown at the end of the HACS install page - NB make everything lowercase!
- url:	 /hacsfiles/lovelace-card-mod/card-mod.js	
  type: module

Worked for me, hope it does for others.

**Comment by JesseWebDotCom** [comment]
> I had this problem and found the solution to be:
> The README.MD page says add:
> resources:
> 
> * url: /local/card-mod.js
>   type: module
>   DO NOT DO THIS
>   Instead add the following which is shown at the end of the HACS install page - NB make everything lowercase!
> * url:	 /hacsfiles/lovelace-card-mod/card-mod.js
>   type: module
> 
> Worked for me, hope it does for others.

This solved the issue for me, thanks.  FWIW - I didn't see the solution in the README.MD however.

**Comment by thomasloven** [comment]
In general, when using HACS, follow the instructions for HACS instead of the other ones.
