### ISSUE TITLE
Please remove 

### ISSUE THREAD

**Issue by Blacksli** [thomasloven/lovelace-card-mod#190]
https://github.com/thomasloven/lovelace-card-mod/blob/a27ed519d98edf28ef10ea0c9f1673c495be199b/src/card-mod.ts#L191

**Comment by thomasloven** [comment]
It seemed like a fun idea.
I was wrong, and I am sorry.

Please update to 3.1.4.

**Comment by genestealer** [comment]
[If your frontend looks weird today Community Post](https://community.home-assistant.io/t/if-your-frontend-looks-weird-today/407225)

**Comment by daaf84** [comment]
I did update to 3.1.4 Still wonky tiles :(

**Comment by Blacksli** [comment]
> I did update to 3.1.4 Still wonky tiles :(

Clear your browser cache

**Comment by thomasloven** [comment]
Apparently some other plugins include card-mod, like minimalist-ui. That could be interfering.

**Comment by daaf84** [comment]
> Apparently some other plugins include card-mod, like minimalist-ui. That could be interfering.

As we speak, there is a hot fix for minimalist -ui. That did the trick. Thanks.

**Comment by emufan** [comment]
> It seemed like a fun idea.

It was a fun idea. Like to see more of this! ♥

**Comment by ervinpagon** [comment]
I don't use minimalist-ui, but I stil have wonky tiles after update card-mod to 3.1.4

**Comment by markusg1234** [comment]
> I don't use minimalist-ui, but I stil have wonky tiles after update card-mod to 3.1.4

I needed to re-download card-mod V3.1.4 in HACS Frontend to fix.

**Comment by ervinpagon** [comment]
I re-download 3 times, made 3 reboots of HA, problem is still there

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#clearing-cache

**Comment by ervinpagon** [comment]
I also cleared cache. The problem is on computer, iphone and ipad

**Comment by thomasloven** [comment]
While you have the developers console open anyway, what version of card-mod does it tell you is installed?

**Comment by ervinpagon** [comment]
Where do I get version of card-mod?

**Comment by thomasloven** [comment]
It's printed in the development console - the one the instructions I linked and you said you'd followed tells you to open.

**Comment by ervinpagon** [comment]
If I click on card-mod lovelace and select Information …  it is written 3.1.4 version

**Comment by thomasloven** [comment]
... and if you check in the browser development console it says... ?

**Comment by ervinpagon** [comment]
Card-mod 3.0.13 is installed

**Comment by ervinpagon** [comment]
Fixed … removed card-mod.js and copied that one from git-hub

**Comment by ildar170975** [comment]
@Blacksli 
I guess the issue may be closed?
