### ISSUE TITLE
MY DASHBOARD LOOKS WEIRD TODAY

### ISSUE THREAD

**Issue by thomasloven** [thomasloven/lovelace-card-mod#192]
Please update card-mod to 3.1.4.

I thought it seemed like a fun idea, but I was wrong.

I'm sorry.

**Comment by ThaGhost-NL** [comment]
Hahaha, you got me off quard with this one. Just tinkering my dashboard this evening and suddenly all tiles were off. Like eh?! What the hell, need some sleep, perhaps a beer to much. Thanks for the good laugh!

**Comment by XJ-09** [comment]
I was changing my layout today and suddenly everything shifted. Was really thinking "where the (...) did I just mess up!?" 😂
Luckily I didn't restore my backup yet. Thanks for the laugh (at the end) anyway!

**Comment by kongjudas** [comment]
00:47 My pulse is back down to 104.

**Comment by NMe84** [comment]
I appreciate April Fools jokes but if you make one, at least make one that only affects your own cards rather than the entirety of Home Assistant or make clear in some other way that it's coming from your mod. People taking this badly are not necessarily people who can't take a joke but people who have spent ages tinkering with HA to get it just right and who have little way of knowing what screwed up this time, causing them to spend a lot of time trying to figure out yet another weird thing happening.

**Comment by ildar170975** [comment]
Actually, this was predicted: https://github.com/thomasloven/lovelace-card-mod/issues/170
I suggest people to monitor GitHub sometimes )))

**Comment by paranoidi** [comment]
I was just about to start making backup of SD card and try restoring backup since everything broke down in the middle of UI tweaking. Only thing that saved me from that was thought that maybe I should try updating everything. Not cool.

Mistakes were made ... it happens.

**Comment by NMe84** [comment]
> Actually, this was predicted: #170 I suggest people to monitor GitHub sometimes )))

Ah yes, because monitoring every random ticket or commit for every single piece of vendor code someone might be using is a reasonable expectation to have of users. Taking some amount of care is always useful but at some point you're just gonna have to trust the developers of the software you're using.

**Comment by mark007** [comment]
This one had me haha I was rebooting HA, restarting phones haha got me nicely.

**Comment by PiotrMachowski** [comment]
Pics...? 😃😃😃

**Comment by genestealer** [comment]
[[If your frontend looks weird today](https://community.home-assistant.io/t/if-your-frontend-looks-weird-today/407225)](https://community.home-assistant.io/t/if-your-frontend-looks-weird-today/407225/17)

**Comment by Sloth-on-meth** [comment]
@thomasloven mate, it's funny. People who are mad should check the date. Not your fault. Hell, even google did something similar in the past

**Comment by RobMatteson** [comment]
I... see nothing wrong. Is it that I'm UTC -5 and the trick doesn't kick in until midnight on April 1?

**Comment by ruaandeysel** [comment]
@thomasloven Nice April fools joke :)

I updated to 3.1.4 but still facing issues with the tilted / misalignment

**Comment by peledzius** [comment]
> I updated to 3.1.4 but still facing issues with the tilted / misalignment

Clear cache.

**Comment by ildar170975** [comment]
> but at some point you're just gonna have to trust the developers of the software you're using.

I totally agree. But - I think that HA is a joint work - some people are creating SW, some are testing. Users should be interested in the final result, and issues on GitHub are a good place either to report a bug/FR or to learn smth or to help others.

**Comment by susanacf90** [comment]
I didn't notice anything until just now, maybe because it's 4.30AM on the 1st of April. I do read the release notes (because lazy ass me didn't use to do it until something broke and she didn't have backups) so I was curious as to what was messed up. I spent a while wondering are the tiles tilted or am I too tired and seeing things? That was funny. 😂

**Comment by nibblerrick** [comment]
I like it. No need for excuses. Nice one!

**Comment by michaelarnauts** [comment]
Try not to worry about it. I think it's a fun joke, and a gentle reminder for everybody that stuff in HACS isn't verified or code reviewed.

You are doing a great job with your integrations!

**Comment by rasssta** [comment]
Must say that I laughed a bit at the joke when noticing it :D 

However my HASS RPI crashed at 03:00, CPU went through the roof. Not sure if it's related. Rebooted it (hard) and CPU kept rising until I upgraded to the new version.

**Comment by Pirol62** [comment]
Already executed the update to 3.1.4 but still have one weird element:
![image|48x500](upload://oBTGgNbuUSV4gFxk2EdqEXQcuXh.png)
After clearing the cache it just changes it's direction

**Comment by ruaandeysel** [comment]
> Already executed the update to 3.1.4 but still have one weird element:
> ![image](https://user-images.githubusercontent.com/48820003/161204722-f610fe62-4b35-4ed5-8b5e-3e1e051c1319.png)
> After clearing the cache it just changes it's direction

I cleared the cache, closed and re-opened the browser. Issue fixed

**Comment by Pirol62** [comment]
thanks @ruaandeysel . That fixed it.

**Comment by Knodd** [comment]
I loved this joke but I didn't realize it was a joke until i saw a notice about a HACS update and checked it.
Next year (if you dare), maybe have the integration post a notification about April's fool (or flood the log with 100 lines of "April's fool!!!") to avoid people rolling back backups or going completely nuts googling.

I also appreciate the reminder that my smart home is exposed to many kinds of potential threats when installing custom integrations.

Thank you for all the great work you do for HA!

**Comment by qbushome** [comment]
Nice joke, but it took only 2 seconds to realize what was happening. So no harm done.

Looking forward to next year !

**Comment by SmarterHomeLife** [comment]
You got me as well @thomasloven when I first woke up this morning and grabbed my phone I thought my eyes weren't focussing properly!!  As noted above it was a very good reminder to be mindful of the things we install in HA.

No apologies necessary in my opinion and thank you for your continued work on this and your other amazing contrbutions to this community that allow us ALL to have better looking dashboards!

**Comment by fusionstream** [comment]
That was funny. Hahaha. Maybe store a cookie though so after the first refresh everything will be hunky dory (everyone gets a chuckle and production systems aren't broken). Cheers. Thanks for the laughs.

**Comment by guelinator** [comment]
This "prank" has showed many people, that home assistant is not a seriously meant project, but a playground for pranksters.
There are some serious things inside home assistant, like doors, alarm systems, and this prank has show that everybody with a github account, can fuck with your system.

i think this prank has done serious harm to home assistant...

**Comment by Sloth-on-meth** [comment]
@guelinator please, get over yourself. Companies like google have done this type of stuff in the past too. It's a harmless April fool's joke that had some unwanted side effects. @thomasloven don't listen to these people

**Comment by Electronlibre2012** [comment]
> Please update card-mod to 3.1.4.
> 
> I thought it seemed like a fun idea, but I was wrong.
> 
> I'm sorry.

@thomasloven dont be sorry lol, its a joke, and i found its a good one...some persons have no humor...bad for them lol, but some have, and you make me smile today, 15 secondes after thinking "what the hell today with my dashboard???" ...realize we are the ...1st April lol...go to HACS and see your update and note...

Have fun, life is short!

and thanks @thomasloven for his great work!

Nice day all

**Comment by guelinator** [comment]
> @guelinator please, get over yourself. Companies like google have done this type of stuff in the past too. It's a harmless April fool's joke that had some unwanted side effects. @thomasloven don't listen to these people

i think it really has show how vulnerable such open source projects are.....

**Comment by SmarterHomeLife** [comment]
Wow!  All you've shown here @guelinator is that you don't understand 'open source' at all...

**Comment by NMe84** [comment]
> @guelinator please, get over yourself. Companies like google have done this type of stuff in the past too. It's a harmless April fool's joke that had some unwanted side effects. @thomasloven don't listen to these people

Companies with Google did not cause people to recover backups and they did not cause people's system performance to tank. The fact that there is a joke is not the issue, the execution of it was terribly poor and though it may not have affected you in a bad way it did affect others. Who are you to tell others their issues are invalid just because you didn't experience them?

**Comment by Sloth-on-meth** [comment]
> > @guelinator please, get over yourself. Companies like google have done this type of stuff in the past too. It's a harmless April fool's joke that had some unwanted side effects. @thomasloven don't listen to these people
> 
> Companies like Google did not cause people to recover backups and they did not cause people's system performance to tank. The fact that there is a joke is not the issue, the execution of it was terribly poor and though it may not have affected you in a bad way it did affect others. Who are you to tell others their issues are invalid just because you didn't experience them?

Because they are invalid. It's an April fools joke. It's free software. Touch grass

**Comment by thomasloven** [comment]
Now now.

I messed up. I admit this.
I am truly sorry for any inconvenience this caused that I did not foresee.

But *no issues are invalid*. I do not want anyone telling anyone so to defend me.
There's nothing further I can do now, but I deserve the hard words as well as the laughs.

**Comment by Sloth-on-meth** [comment]
It's fine. It's only an April fools joke. Whoever's angry about this needs to go outside haha

**Comment by NMe84** [comment]
> Now now.
> 
> I messed up. I admit this. I am truly sorry for any inconvenience this caused that I did not foresee.
> 
> But _no issues are invalid_. I do not want anyone telling anyone so to defend me. There's nothing further I can do now to change things, but I deserve the hard words as well as the laughs.

Just for clarity: I'm not saying you are handling this badly. You owned up to what happened, pushed a fix and published it just about everywhere. And I do appreciate jokes, despite how much other people here seem to want to paint me as an overly sensitive ass. I just hope that the next joke is a little bit more self-contained to your own cards.

Don't let the people who had problems get you down to much, and that includes me. And don't let it stop you from doing fun stuff in the future either, because the idea wasn't bad at all.

**Comment by ildar170975** [comment]
So much negative. 
This is not a nuclear station. It is just a UI stuff.

**Comment by sdotter** [comment]
haha i could laugh about it... maybe it was just too subtle... 
Anyway still like card mod a lot!

**Comment by GarSys** [comment]
Thank you Thomas for all the coding you do and for this April Fools joke. I love it. And it is so easily fixed.

**Comment by Pirol62** [comment]
No, it was not that easy fixed in the end. Clearing the cache means, that all HA settings were deleted, means that all browser_mod identification tags changed, that I had to identify each device in HA and reconfigure the devices in the configuration.yaml and so on..... 
It looked quite funny but I needed some time, to bring all browser_mod related stuff to work again.
That wasn't funny.

**Comment by GarSys** [comment]
All I had to do was install the update, refresh the browser, and both my instances (at home and at work) straightened themselves out (pun intended).  It is very unfortunate that it was not that easy for you.

**Comment by michaelarnauts** [comment]
> No, it was not that easy fixed in the end. Clearing the cache means, that all HA settings were deleted, means that all browser_mod identification tags changed, that I had to identify each device in HA and reconfigure the devices in the configuration.yaml and so on..... It looked quite funny but I needed some time, to bring all browser_mod related stuff to work again. That part wasn't funny.

Clearing cache is enough, I think you also cleared cookies and local settings. I just had to refresh the page, and force close the mobile app. But that's the same as a normal update of something in HACS.

**Comment by thomasloven** [comment]
Or if not, the tricks mentioned here https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#clearing-cache

**Comment by Pirol62** [comment]
Sorry, but a simple clear did not work, but the link is new to me. Thanks @thomasloven

**Comment by MrThiemann** [comment]
Amazing !!! 
thank you for pointing out the "dangers"! you can see how fast this can happen!
We talked a lot about it on Discord too! For me it remains exciting to what extent anyone can access the core through such manipulations...?!?
was definitely a cool action! 🤝

**Comment by thomasloven** [comment]
Just for clarity and for the people who feel they missed out.

Here's what I meant to happen:
Wonky crooked cards. Harmless fun for the entire family.
![cards](https://user-images.githubusercontent.com/1299821/161330343-e680c1bc-78f3-4b1d-802f-fc1d6f60b226.png)
Up to three degrees of randomly applied rotation, meaning on a 4K screen with a card in panel mode stretched as far as it could go, a control could move up to 104 pixels (about one inch) out of place vertically. But that's an extreme case.


What I did not anticipate:
The effect stacks in the automations page when many ha-card elements are used in parallell.
![Automations](https://user-images.githubusercontent.com/1299821/161330371-27a43880-b7e8-4d6d-bb31-183f28a1ece7.png)

Also, apparently the rotation can cause bad performance on some devices.

What I absolutely did not anticipate:
Common browser behavior means applying a transform to an element makes it throw the render stacking rules to the wind, making context and dropdown menus unusable.
![menus](https://user-images.githubusercontent.com/1299821/161330385-199222d5-a8f8-4bc1-b39d-ff6e7d5b2290.png)
I learned a lot from this one... maybe it can be useful in more constructive ways...

I understand people being really upset about the last two things, and ask you to consider that *bugs*. It really was not my intent in any way.
Part of the problem is that card-mod has grown more powerful since I came up with the idea. I should have done more testing along the way.

**Comment by scidoner** [comment]
Mate, this was hilarious once I found out it was the cause. I wasn't stupid enough to go poking around restoring backups or spending hours trying to fix the problem (I knew I had changed something) and when I saw this in the change log I was amused!

Still, you got me - and to be honest I thought it was a recent Chrome bug as that is the only browser I end up using on all my devices!

**Comment by CrallH** [comment]
@thomasloven I think the prank was both fun and a really good learning for my own setup! I have handled customs just as regular addons, but they are not regular! We need to actually focus more on the security flaws we intentionally install on our systems. No hate from me, only love! Keep up the good work!

**Comment by tiancom** [comment]
> Please update card-mod to 3.1.4.
> 
> I thought it seemed like a fun idea, but I was wrong.
> 
> I'm sorry.

Are you sure it's just a funny? today 4.1

**Comment by thomasloven** [comment]
This was two years ago.
If you haven't updated in that time, you're on your own.
