### ISSUE TITLE
April 1 joke rendered input_select-s USELESS - jokes are not for live controlling systems

### ISSUE THREAD

**Issue by lmagyar** [thomasloven/lovelace-card-mod#193]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When input_select pop-up list is rendered downward, it is behind everything. Nothing can be changed in the system, great idea.

![image](https://user-images.githubusercontent.com/5061219/161206032-d8f850e9-17eb-4c9d-8b9f-647cb62dd67e.png)

When it rendered upward, it is OK:
![image](https://user-images.githubusercontent.com/5061219/161206062-99447dd7-8feb-4740-b9b0-484d964ef9f9.png)

This happens on Win Chrome, Win Firefox (vanilla install), Win Edge, Android app, Android Chrome, so this is not a client malfunction, this is coming from HA itself.

At the same time this happens also, that's why I think it is an April 1 joke, gone wrong (note, each card is rotated):
![image](https://user-images.githubusercontent.com/5061219/161206320-6f29322f-b374-45ad-9199-9825b4e8f426.png)

### Describe the behavior you expected

No **** jokes.

### Steps to reproduce the issue

1. try to access any input_select

### What version of Home Assistant Core has the issue?

2022.3.8

### In which browser are you experiencing the issue with?

Chrome 99.0.4844.84, Firefox 98.0.2, Edge 99.0.1150.55

### Which operating system are you using to run this browser?

Android 8.0.0, Win 7

**Comment by lmagyar** [comment]
Copied from https://github.com/home-assistant/frontend/issues/12185

**Comment by arallsopp** [comment]
Looks like a duplicate of #192

Please update card-mod to 3.1.4

**Comment by homonto** [comment]
I LOVE TODAY'S JOKE - IT MADE ME MAD BUT THAT IS WHAT FUN IS ABOUT! LOVELY ;-)

**Comment by ukmgranger** [comment]
Love it!  I'm amazed that I stumbled across this so quickly!!  Very funny though!!!

**Comment by mbrihed** [comment]
Love it. We need more fun and gave me a good laugh this morning.

**Comment by Sloth-on-meth** [comment]
What's with the entitlement? It's just a joke, calm your shit

**Comment by Electronlibre2012** [comment]
looooooool love you @thomasloven ...make me smile today...and more when i read other are angry...... :)

**Comment by lmagyar** [comment]
Rotating card is fun, **making input_selects unusable is not fun**, it makes 1000s of real systems unusable.

It is strange, how developers can't understand the real problem behind this.

This is a typical example of a one-liner, that is harmless, do it, and then everything is got f### up. See New Horizons story: test system unavailable, code change is "harmless", let's upload it anyway, a few hours later the probe ~1bkm away from you disappears... You have only a few days before it reaches Pluto... That was a "harmless one-liner", nearly destroying billions of dollars and thousands of people's lifetime work. That's why never make untested "harmless" modifications.

**Comment by Sloth-on-meth** [comment]
Thát is a MARS ROVER. This is home assistant. please pull your head out of your ass

**Comment by skynet01** [comment]
Love the joke! We need more of this in HA. He even released a patch right away, why all the hate 
Just don't use Home Assistant for one day, tomorrow it will be gone 😄

**Comment by TheLastProject** [comment]
If you are using this software in critical systems, why aren't you paying the developer for a support contract? The license is clear:

```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```

**Comment by ildar170975** [comment]
I think that everyone needs some fun these horrible days.
Please do not be so angry. This is April 1)))

**Comment by ildar170975** [comment]
Also, I think that the most upset person is Thomas.
Probably he is upset of complains and anger of some people. 
I want to express my support and gratitude to Thomas Loven for his amazing work!
Please keep your good work!

**Comment by killtux** [comment]
@thomasloven  damn. we had a power outage for several ours. then power came back but whole internet and network crashed. after hours of seraching i figured out the main network switch forgot its configuration for link trunking and some kind of loopback happend and made the network crash every time.
after spinning up the VM's (i was now 2 o'lock)  i noticed that odd look in HA and HA reportet a DB error because of the outage. i thought something crashed and it didnt recover from a fresh reboot so i dumped the whole machine and made a recover from an old backup but lost all historical sensor data.

2 hours for nothing and lost data for nothing. i am really pissed, cant find anything funny on this.

**Comment by thomasloven** [comment]
> Also, I think that the most upset person is Thomas. Probably he is upset of complains and anger of some people. I want to express my support and gratitude to Thomas Loven for his amazing work! Please keep your good work!


Thanks.
So far the people laughing seem to outweigh the ones who got problems, and those also seem to understand that there was no ill intent.
I understand my reputation has been damaged and will NOT do anything like this again (knowingly N.B.).
But I've been teaching my kids that a good April fools joke ends with the fool laughing, and I hope the people with problems will be able to laugh too once this is all over. If that's laughing *at* me rather than *with* me - so be it.

**Comment by thomasloven** [comment]
> 2 hours and lost data for nothing. i am really pissed. cant find anything funny on this.

I'm really sorry about that. But this did NOT cause a DB error.

**Comment by killtux** [comment]
> > 2 hours and lost data for nothing. i am really pissed. cant find anything funny on this.
> 
> I'm really sorry about that. But this did NOT cause a DB error.

db looks fine, i think it just stated that it was not gracefully shut down or something. but since the dashboard look that way i thought something in lovelace got damaged since i had some design errors half a year ago because of a typo/bad yaml.

so i thought the only way was to revert to a backup where this didnt happen and then noticed it just happend any and the recovery wasnt necessary at all :(

**Comment by emufan** [comment]
I love the joke, Thomas!

**Comment by Telectroboy** [comment]
Very Nice! Really like this Joke !!!

Makes me smile :) Can we keep it for ever? And next year you adjust everything straight ^^

Thanks for the fun

**Comment by homonto** [comment]
the most funny thing for me was, that the "white bars" on my lovelace were only visible on macos - nothing on android or ios 

I did not notice anything not working - just the outlook of the lovelace but in fact, is something WAS not working then... maybe too far 

anyway, it is very "normal" in IT but also in life: when 1 shit happens, there is an avalanche - but up to restoring the HA from backup? I would have waited a bit ;-)

**Comment by caiosweet** [comment]
A brilliant idea! 😂🎣🐟

**Comment by ukmgranger** [comment]
> I understand my reputation has been damaged and will NOT do anything like this again (knowingly N.B.). 

Thats a shame!

**Comment by arallsopp** [comment]
> I understand my reputation has been damaged and will NOT do anything like this again (knowingly N.B.)

Mate, you provide the enthusiast community with a great number of no-cost open source aftermarket add-ons to a piece of "as is" no-cost tinkerware provided without any guarantee of fitness for purpose.

Anyone using it does so at their own risk, and I'd be horrified if this recent spat discouraged you from continued development in any way. The community owes you a lot, and paradoxically its only when things misbehave that some will realise quite how important your contributions are.

Its a mis-step. You've remediated as best you can. Its all good.

**Comment by LRvdLinden** [comment]
> > Also, I think that the most upset person is Thomas. Probably he is upset of complains and anger of some people. I want to express my support and gratitude to Thomas Loven for his amazing work! Please keep your good work!
> 
> Thanks. So far the people laughing seem to outweigh the ones who got problems, and those also seem to understand that there was no ill intent. I understand my reputation has been damaged and will NOT do anything like this again (knowingly N.B.). I've been teaching my kids that a good April fools joke ends with the fool laughing, and while I may have failed here I still hope the people with problems will be able to laugh too once this is all over. If that's laughing _at_ me rather than _with_ me - so be it.

I can personally laugh at this. I find the work you do valuable and therefore the joke is also acceptable. Thanks for your hard work and keep it up!

**Comment by AcidSleeper** [comment]
Had to update and see what everyone was so "HAPPY" about. 
Tilting my experience! =)

Downgraded after that to 3.1.1 but still the same even deleting cookies and using another browser. So somthing is funky here aswell.

**Comment by thomasloven** [comment]
Downgrading won't help. Updating to 1.3.4 will - or waiting until tomorrow.
This has been lying in wait for almost an entire year.

**Comment by AcidSleeper** [comment]
> Downgrading won't help. Updating to 1.3.4 will - or waiting until tomorrow. This has been lying in wait for almost an entire year.

Just Upgrading didnt fix it, neither just deleting the cookie for HA. Had to do a cleansweep of cookies and the restart browser. Now its look normal again! ;(

**Comment by oramirite** [comment]
What an interesting situation! I knew that someone's live system was going to have problems. Rarely does a joke like this go off without accidentally causing someone collateral damage. This can be a lesson for so many people involved. Including the author! When you're in a power position of having contributed a large part of the fabric of an ecosystem, a harmless joke will never actually be harmless. Your code touches too many systems across the world for you to take account for everything.

I see both sides of the argument here. This software is free and open source. You are using it without any expectations of anything. Legally, anyway...

But there's an interesting reality we must all face. This is used to control homes. What if that drop-down was bugged out for a setup someone had to disarm their alarm? Or even a panic button during a robbery?

Regardless of how much some of you would like to rail on others for "not having a sense of humor", there's an extremely slim chance that, given the way HA is meant to be integrated into a person's life, that it could have caused major issues.

Yes, again, this is open source software. But it's also HOME CONTROL software. This is a software package ACTIVELY ENCOURAGED by it's authors and also Thomas here to CONTROL THEIR HOMES. This can include devices that are capable of causing physical harm.

So this whole argument about "not using the software for mission-critical purposes" is kinda BS. The software exists to control critical things in your home.

All of that said, I'm glad Thomas did this :) What's funny is, I DO pay attention to my install process... I saw the warning 30 minutes before April 1st even came, so I just decided I wasn't gonna see the joke and upgraded anyway :P

None of this takes away from the great work Thomas has contributed to the community. And I don't think this has "damaged" his reputation at all. However I don't think there is necessarily any good "lessons" for the users here. If any other HA developer chose to do something malicious like this, then we'd all be very screwed. Knowing this doesn't really even help. The only thing that would help would be to stop using HA altogether, which is kind of a shitty takeaway from this whole situation.

I dunno. Fascinating!

**Comment by homonto** [comment]
> I don't think this has "damaged" his reputation at all.

true
we can all learn from that... joke ;-)

**Comment by spacegaier** [comment]
> Two words: F*** Y**
> 

Seriously? Please change your tone!

**Comment by homonto** [comment]
> Two words: F*** Y**
> 
> Not funny in productive systems...

you are an idiot ;-)

**Comment by thomasloven** [comment]
> Not funny in productive systems...


I understand you probably don't feel like helping me right now, but would you mind posting a screenshot of your system? Through this day (and what a day) I have had a hard time understanding just how breaking this could be.

**Comment by homonto** [comment]
> > Not funny in productive systems...
> 
> I understand you probably don't feel like helping me right now, but would you mind posting a screenshot of your system? Through this day (and what a day) I have had a hard time understanding just how breaking this could be.

Thomas, yo cannot talk to idiot: he will take you to his level, and on that level he is a master!

**Comment by thomasloven** [comment]
Please refrain from name calling. From both sides.

**Comment by clickme83** [comment]
> Seriously? Please change your tone!

Sorry, i spent hours over hours to figure out what's happening before I saw this "issue" breaking the Automation Page.. I'm tracking my pv-system with HA and NEED a system without glitches.

> I understand you probably don't feel like helping me right now, but would you mind posting a screenshot of your system? 

I already updated card-mod, did an unplanned restart of HA and no glitches left.

**Comment by thomasloven** [comment]
Yes. I did not anticipate the way the effect could stack up in the automations editor or how the menus in the integrations page would switch render stacking. That was unfortunate and I've learned a lot today...

I'm glad you got it working again at least.

**Comment by lmagyar** [comment]
Issue solved, closing.
