### ISSUE TITLE
Trying to replace card-modder with card-mod on popup-card

### ISSUE THREAD

**Issue by TheStigh** [thomasloven/lovelace-card-mod#20]
Hi @thomasloven I know popup-card is deprecated but for now it's widely used in my HA.
I've started the process of replacing card-modder with card-mod in my setup, and the only thing missing are changing the popup-cards.

Tried also with **ha-card**, but still it doesn't apply the new CSS.

Old config:

      camera.bmw_530i_xdrive:
        title: Sist kjente lokasjon
        large: false
        card:
          type: custom:card-modder
          card:
            type: picture-entity
            entity: camera.bmw_530i_xdrive         
          style:
            border-radius: 0px
        style:                 
          border-radius: 15px
          background-color: rgba(100,100,100,0.3)
          box-shadow: 0px 0px 10px 10px rgba(57,128,228);

 New config:

     camera.bmw_530i_xdrive:
        style: |
          :host {
            border-radius: 15px;
            background-color: rgba(100,100,100,0.3);
            box-shadow: 0px 0px 10px 10px rgba(57,128,228);
          }
        title: Sist kjente lokasjon
        large: false
        card:
          type: picture-entity
          entity: camera.bmw_530i_xdrive  

I hope you will still assist me in achieving this even if popup-card is deprecated.

**Comment by thomasloven** [comment]
popup-card (and browser_mod which now is a complete replacement on popup-card) has it's own `style` parameter, which is not related to card-modder or card-mod. Leave that like before.
