### ISSUE TITLE
Styles may NOT be applied to Conditional row/element

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#201]
My Home Assistant version: 2022.5.4
Chrome, Win10.
Safary, OS X 10.15.1.

My lovelace configuration method (GUI or yaml): storage/yaml

What I am doing:
Applying a style to conditional row inside Entities card.

What I expected to happen:
The style is applied always. 

What happened instead:
The style sometimes is not applied.

The problem was also described in the Community card-mod thread:
- for a conditional row inside Entities card - https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1845?u=ildar_gabdullin
- for a conditional element inside Picture elements card - https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2253?u=ildar_gabdullin

**Minimal** steps to reproduce:
1. Create a new card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_boolean.test_boolean
  - type: entities
    entities:
      - sun.sun
      - type: conditional
        conditions:
          - entity: input_boolean.test_boolean
            state: 'on'
        row:
          entity: sun.sun
          icon: 'mdi:desk-lamp'
          name: Nählicht Lampe
        card_mod:
          style:
            hui-text-entity-row $: |
              hui-generic-entity-row {
                text-indent: 45px;
                color: red;
              }
      - entity: sun.sun
```
2. Refresh the page.
3. Set the toggle to OFF.
4. Check if the conditional row is NOT displayed:
![изображение](https://user-images.githubusercontent.com/71872483/169626304-90e70028-d68d-4ec8-81f9-b01db79acdd0.png)
5. Set the toggle to ON.
6. Refresh the page.
7. Check if the conditional row is displayed and properly styled:
![изображение](https://user-images.githubusercontent.com/71872483/169626391-8fcc0c97-5615-424c-a63d-261f12ef78f7.png)

So far it should work fine. Now a problem part:

8. Set the toggle to OFF.
9. Check if the conditional row is NOT displayed.
10. Refresh the page.
11. Set the toggle to ON.
12. Check if the conditional row is displayed and properly styled.
What I see is - the **row is NOT styled**:
![изображение](https://user-images.githubusercontent.com/71872483/169626500-a4b59078-2f06-45a2-afb3-2a09a3b13973.png)
13. Refresh the page.
14. Check if the conditional row is displayed and properly styled.
What I see - the **row IS styled**.

Error messages from the browser console:
No.
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [] Have made sure I am using the latest version of the plugin.

- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Good work, Thomas!

**Comment by PronkMedia** [comment]
I have tested it yesterday, and it still is (seemingly randomly) failing for me. Especially on first load, after e.g. changing tabs or rotating my phone the styles are applied correctly.

@ildar170975 Did you test the latest version already? Did is solve everything for you? I'm wondering if I'm encountering a bug that is very spicific to my personal configuration right now.

Not sure if it will help, but this one of the configrations where I am encountering it: https://raw.githubusercontent.com/PronkMedia/Home-Assistant-Config/master/lovelace/views/home.yaml
So in this file for example the rotation of the icons is not always applied on first load.

**Comment by ildar170975** [comment]
> Did you test the latest version already?

Yes, right now I rechecked it with HA 2022.6.1 & card-mod 3.1.5.
Win10x64, Chrome.
Works OK.

iPhone 5S, iOS 12.5.5
iPad Air 2, iOS 15.4
**Style is NOT applied after refresh.**

**Comment by PronkMedia** [comment]
Many thanks for your quick reply @ildar170975! That case is indeed still failing for me too. So if a conditional row is/should be displayed on initial page load, the style is not applied for me. I can reproduce it on desktop (latest Chrome) with hard refreshing the page and on Android mobile browser (latest Chrome).

@thomasloven Could you please consider re-opening this issue? As it looks like this is not completely fixed.

**Comment by ildar170975** [comment]
> Did not check it with iOS.

For the record:
1. Still work fine in Win10+Chrome, 2023.8, card-mod 3.2.2.
2. Same with iOS 15.7.7, iPad Air 2 - works fine.

```
type: vertical-stack
title: conditional row (Problem 142)
cards:
  - type: entities
    entities:
      - input_boolean.test_boolean
  - type: entities
    entities:
      - sun.sun
      - type: conditional
        conditions:
          - entity: input_boolean.test_boolean
            state: 'on'
        row:
          entity: sun.sun
          icon: mdi:desk-lamp
          name: Lamp
        card_mod:
          style:
            hui-simple-entity-row $: |
              hui-generic-entity-row {
                text-indent: 45px;
                color: red;
              }
      - entity: sun.sun
```

**Comment by ildar170975** [comment]
Have to reopen.
Still there are issues with a conditional element in Picture elements card (PE):

Here a PE card has 1 conditional element.
Usually it looses its styling after a page refresh.
![изображение](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/4ddb1e71-33e8-4fe7-b903-fd2548451b9a)
```
type: picture-elements
image: /local/images/test/white.jpg
elements:
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'on'
    elements:
      - type: state-label
        entity: sun.sun
        style:
          top: 17%
          left: 75%
    card_mod:
      style:
        hui-state-label-element:
          $: |
            div {
              color: red;
            }
```
Observed in:
-- Win10+Chrome (118.0.5993.118);
-- iOS Companion App (iOS 15.x).

Note that it happens when we need to go into shadowRoot.
If we do not - the style is STABLE (but another problem occurs, will attach a link to it later).

**Comment by curtisbarnard** [comment]
I think I'm see this issue in the entities card as well. Here is the card I have:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/100104319/94f9b521-b852-4937-9244-95d15953c83f)

Here is the DOM structure:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/100104319/340bfe02-2707-4c06-836a-a55441b31b76)

I've tried using `:host`, `hui-conditional-row $` and `hui-sensor-entity-row $` in the below code. Nothing seems to work to change the icon color:
```
          - type: conditional
            conditions:
              - entity: sensor.cph50_charging_cable
                state: "Plugged In"
            row:
              entity: sensor.cph50_charger_state
              name: "Charging Status"
              card_mod:
                style:
                  hui-conditional-row$: |
                    hui-generic-entity-row {
                      --card-mod-icon-color: var(--blue-color);
                    }
```

**Comment by ildar170975** [comment]
1. Here the card-mod code is misplaced, DOM path is wrong, the code is not supposed to work:
```
            row:
              entity: sensor.cph50_charger_state
              name: "Charging Status"
              card_mod:
                style:
                  hui-conditional-row$: |
```
2. There is another issue with `--card-mod-icon-color`.

**Comment by curtisbarnard** [comment]
@ildar170975 you were right, thanks for the help! I'm using this code and getting the results I want:
```
          - type: conditional
            conditions:
              - entity: sensor.cph50_charging_cable
                state: "Plugged In"
            row:
              entity: sensor.cph50_charger_state
              name: "Charging Status"
            card_mod:
              style:
                hui-sensor-entity-row $: |
                  hui-generic-entity-row {
                  {% if is_state('sensor.cph50_charger_state', 'Not Charging') or is_state('sensor.cph50_charger_state', 'In Use') %}
                    --card-mod-icon-color: var(--blue-color);
                  {% elif is_state('sensor.cph50_charger_state', 'Fully Charged') %}
                    --card-mod-icon-color: var(--success-color);
                  {% else %}
                    --card-mod-icon-color: var(--state-unavailable-color);
                  {% endif %};
                  }
```

![image](https://github.com/thomasloven/lovelace-card-mod/assets/100104319/789ad50e-d591-4f60-9956-0745c5cf83ce)

**Comment by ildar170975** [comment]
@curtisbarnard 
Good, but check if that issue with "--card-mod-icon-color" is observed. Hopefully it had been fixed already.

**Comment by ildar170975** [comment]
@Wetzel402 
If you read this thread you could realized that this is not a bug.
The OP was using a wrong card-mod code.
After getting an explanation OP did not close the issue (although it was resolved).
And YOU are also using a wrong code & considering it as a bug.
Suggest to use a Community for asking questions since Github is not a helpdesk.
