### ISSUE TITLE
How to duplicate rules ?

### ISSUE THREAD

**Issue by Navatusein** [thomasloven/lovelace-card-mod#217]
Please tell me how to duplicate css rules for identical elements.
I'll explain with an example.
![image](https://user-images.githubusercontent.com/53920406/183910284-acbc79bb-dfd9-494b-b438-55fd5635f2fc.png)

I have mushroom-template-chip. For the first, the rules were created. How can I make it so that they are also created for the second mushroom-template-chip ?

**Comment by ildar170975** [comment]
My humble advice - ask similar questions in a dedicated card-mod community thread. Leave GitHub for bugs  & FRs only. Otherwise this repo will be full of same questions.
