### ISSUE TITLE
Installation through HACS has bad configuration information.

### ISSUE THREAD

**Issue by Petro31** [thomasloven/lovelace-card-mod#22]
When viewing the page for card-mod in hacs, it claims the configuration process is:

```
- url: /community_plugin/lovelace-card-mod/card-mod.js
  type: null
```

should be
```
- url: /community_plugin/lovelace-card-mod/card-mod.js
  type: module
```

Have had to help a few people on the forums and this was the root cause of their problems.

**Comment by thomasloven** [comment]
Duplicate of #18.
