### ISSUE TITLE
Help with opacity: 92%

### ISSUE THREAD

**Issue by VikeDragon** [thomasloven/lovelace-card-mod#221]
Greetings!
Please help with the card:

              - type: custom:auto-entities
                show_empty: true
                card:
                  type: entities
                filter:
                  include:
                    - group: group.plant_warn_moisture_scale
                      options:
                        secondary_info: last-changed
                        style: |
                          :host {
                            --paper-item-icon-color:rgb(102,0,202);
                          } 

it is necessary to make it opaque by 92%
For example, this code works :

             - type: entities
                style: |
                  ha-card {
                    opacity: 92%;
                  }  
                entities:
                  - entity: input_boolean.warnings_flowers
                state_color: true
                show_header_toggle: false

I tried to insert it in different ways for
style: |
ha-card{
opacity: 92%;
}
but nothing comes out - I ask for help ...

**Comment by ildar170975** [comment]
Earlier I advised you to use card-mod community thread, not GitHub.
This is a question, not a bug or FR.
Go here - https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744
