### ISSUE TITLE
Layout issues on "area" page

### ISSUE THREAD

**Issue by jackwilsdon** [thomasloven/lovelace-card-mod#222]
My Home Assistant version: 2022.9.1

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Viewing an area under "Settings"

What I expected to happen: The layout to not be affected by card-mod

What happened instead: The layout is affected by card-mod:

<table>
<tr>
<th>Without card-mod</th>
<td><img src="https://user-images.githubusercontent.com/1843197/189478857-57bca48f-f0fa-4a0b-bd35-9ec335a9a40a.png" alt="Without card-mod"></td>
</tr>
<tr>
<th>With card-mod</th>
<td><img src="https://user-images.githubusercontent.com/1843197/189478932-73488cdb-7529-407f-8cd0-fa007227899a.png" alt="With card-mod"></td>
</tr>
</table>

This seems to be related to https://github.com/home-assistant/frontend/issues/13624.

**Minimal** steps to reproduce: just install card-mod 3.1.5 (in my case via HACS)

Error messages from the browser console: no errors, just `CARD-MOD 3.1.5 IS INSTALLED`.

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jackwilsdon** [comment]
Just realised my screenshots aren't right, sorting those now...

**Comment by jackwilsdon** [comment]
Looking at the DOM, some elements seem to have been moved out of the shadow root by card-mod which is causing the issue:

<table>
<thead>
<tr>
<th>Without card-mod</th>
<th>With card-mod</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/1843197/189479198-7ea9d984-b5a9-4ced-9292-75a8ff69bfaf.png" alt="Without card-mod"></td>
<td><img src="https://user-images.githubusercontent.com/1843197/189479104-1b43fbf7-6aa6-49e3-8440-a7989ceeb65c.png" alt="With card-mod"></td>
</tr>
</table>

**Comment by ildar170975** [comment]
Do not confirm this issue. 
Win10x64, Chrome

**Comment by Spookster** [comment]
I can confirm removing card-mod fixed the issue, so it seems the issue does occur as above

**Comment by ildar170975** [comment]
Does it happen with a default theme when card-mod is installed?
I mean, some custom themes may cause glitches.

**Comment by jackwilsdon** [comment]
I'm seeing this with both a custom theme (Noctis Grey) and the default theme.

I don't think this is related to the theme - the actual DOM appears to differ when card-mod is installed.

**Comment by Spookster** [comment]
Im using the default theme.

**Comment by ildar170975** [comment]
As I already said, cannot reproduce it.
Shall you test it on a fresh testing HA setup? (only card-mod is installed)

**Comment by lalexdotcom** [comment]
Same here (layout is good when card-mod is removed)
<img width="352" alt="image" src="https://user-images.githubusercontent.com/15171326/199846737-bf728988-bc2f-4843-bdbd-0a81e6a2fcca.png">

I have another layout issue when configured as "panel"... (maybe I should open another issue for this, but maybe it's related: let me know): a padding appears at the bottom of entity-pictures cards when using card_mod (cards are inside a vertical stack)
<img width="100" alt="image" src="https://user-images.githubusercontent.com/15171326/199846560-ba7150e9-5364-4370-b962-c7968f32fd7b.png">

When i remove card-mod from the cards, or configure the view as a regular one (Masonry), no gap appears at the bottom as expected

**Comment by ildar170975** [comment]
After 2022.11 the glitch occurs in my setup too )))))
![изображение](https://user-images.githubusercontent.com/71872483/200080514-2514ae10-5c71-482d-bd41-407370054aee.png)

Have not uninstalled card-mod.

**Comment by jackwilsdon** [comment]
Looks good, thanks @thomasloven!

**Comment by ildar170975** [comment]
thanks a lot, @thomasloven !
