### ISSUE TITLE
Strange flash on initial load

### ISSUE THREAD

**Issue by RefineryX** [thomasloven/lovelace-card-mod#227]
I’m currently building out my dashboard and when using ‘card-mod’ it does an annoying refresh / flash on the initial load of each page.

Is there anything I can do to stop this?

**Demonstration:**

![ezgif-1-b0d97a1b8e](https://user-images.githubusercontent.com/46373533/195194445-0f2756c5-0078-4092-9373-96ac03b47c79.gif)

**Slowed Down**

![ezgif-3-770374844a](https://user-images.githubusercontent.com/46373533/195979576-601d21f1-8c25-41cc-b2ed-26c6985b4509.gif)

In my config.yaml file I also put the following to see if it would prioritise the load but it has not worked.
```
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
```

**Code used in demo:**
```
type: custom:mod-card
style: |
  ha-card {
    padding: 0px 30px 0px 30px!important;
  }
card:
  type: vertical-stack
  cards:
    - type: horizontal-stack
      cards:
        - type: custom:mod-card
          card:
            type: custom:mushroom-title-card
            title: Entertainment
          card_mod:
            style:
              mushroom-title-card$: |
                .header {
                  --title-padding: 23px 0px 40px;
                  letter-spacing: -0.12vw!important;
                }
                .title {
                  font-size: 35px!important;
                  font-weight: 520!important;
        - type: custom:mushroom-chips-card
          chips:
            - type: entity
              entity: sensor.bathroom_temperature
              tap_action:
                action: none
              hold_action:
                action: none
              double_tap_action:
                action: none
          alignment: end
          style: |
            .chip-container {
                padding-top: 0px;
                padding-right: 0px;
              }
            :host {
                --chip-background: none!important;
    - type: horizontal-stack
      cards:
        - type: custom:mushroom-light-card
          entity: light.bedside_lamps
```

**Comment by peter-wroot** [comment]
I'm seeing this behavior as well, it looks to me like the custom CSS is being applied after the dashboard is loaded, with some kind of transition animation. 

I have a few card where I'm removing the background, changing the font size, or changing padding and they all animate the change between their default state and the changes made by card-mod. This seems to only happen on initial page load, after which it won't happen again until the page is refreshed, or some kind of cache expires.

![Animation](https://user-images.githubusercontent.com/39913947/203545223-950293d9-f8d2-4656-b398-d120369d98a2.gif)

The above gif was recorded using firefox, but I'm seeing the same behavior in the Fully Kiosk Browser app too.
