### ISSUE TITLE
Expected a value of type `undefined` for `style` 

### ISSUE THREAD

**Issue by Todilo** [thomasloven/lovelace-card-mod#24]
My Home Assistant version: 0.XX.X

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Trying to add a card with custom style

What I expected to happen:
Custom style to be applied

What happened instead:
ERror showing
Expected a value of type `undefined` for `style` 

**Minimal** steps to reproduce:
Installed lovelace-card-mod through HACS, then pressed "add to lovelace", then restarted HA then used an example code:
type: entity-button
entity: light.malarbord
style: |
  ha-card {
    background: {% if is_state('light.bed_light', 'on') %} green {% endif %};
  }

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by RenzoBeux** [comment]
Hi, wanna know how you solve this.
Thank you

**Comment by Todilo** [comment]
> Hi, wanna know how you solve this.
> Thank you

Sorry I didn't. The limitation of what I could do with the lovelace-card-mod / documentation was too me a bit too much.
