### ISSUE TITLE
Conditional card with markdown card.

### ISSUE THREAD

**Issue by hklages** [thomasloven/lovelace-card-mod#240]
Hi. card-mod works fine with the standard cards such as markdown. I am struggling to use it for a conditional card with markdown card. I use card-mod to make the cards "slimmer". 
Are there any guidelines? 

Conditional cards are good for showing missing entities or updates and dont want to see the card when there are no missing entities or updates. 

```
card_mod:
  style: |
    .card-header {
       padding-bottom: 1px;
       padding-top: 1px
    }
```

**Comment by filmgarage** [comment]
I am having the same problem in an entities card, can't use card-mod on the conditional entities in the list...

**Comment by thomasloven** [comment]
Neither the markdown card not the conditional card has a `.card-header` element.
I don't understand what you are trying to accomplish with your example.
