### ISSUE TITLE
CSS Keyframes

### ISSUE THREAD

**Issue by evasilisin1984** [thomasloven/lovelace-card-mod#241]
I am having an issue where the browser on my device doesn’t support keyframes - any animations.   Is there a way to use JavaScript on this card-mod to animate ?

thanks

**Comment by ildar170975** [comment]
I wonder what browser is it?

**Comment by evasilisin1984** [comment]
Amazon Silk But I loaded chrome and Firefox on it, and still the CSS rotation would not work.   Works on chromium and any browser I’ve ever used.   But wouldn’t work on that device with any browser.  So weird.  On Jan 7, 2023, at 6:36 PM, ildar170975 ***@***.***> wrote:﻿
I wonder what browser is it?

**Comment by thomasloven** [comment]
No. There's no way to inject javascript with card-mod.
