### ISSUE TITLE
card_mod style does not update on image after state change in picture-elements card

### ISSUE THREAD

**Issue by davideickhoff** [thomasloven/lovelace-card-mod#245]
My Home Assistant version: 2023.1.4

My lovelace configuration method (GUI or yaml):

```
title: Floorplan
views:
  - title: Control Rooms
    icon: mdi:floor-plan
    panel: true
    badges: []
    cards:
      - type: picture-elements
        image: /local/ui/floorplan/night.png
        style: |
          ha-card:first-child {
            background: rgba(42, 46, 48, 1)
          }
        elements:

          - type: image
            image: /local/ui/floorplan/lights/hallway_living_on.png
            entity: light.flur_garderobe
            tap_action:
              action: none
            hold_action:
              action: none
            style:
              mix-blend-mode: lighten
              transform: none
              width: 100%
              height: 100%
              top: 0
              left: 0
            card_mod:
              style: |
                :host {
                  opacity: {{ (state_attr(config.entity, 'brightness') / 255) if is_state(config.entity, 'on') else 0.0 }};
                  filter: {{ 'hue-rotate(' + ((state_attr(config.entity, 'hs_color')[0] - 45)|string if state_attr(config.entity, 'hs_color') else 0) + 'deg)' }};
                }

```

What I am doing:
Overlaying images to show the status of a light and its color using CSS filters in a picture-elements card

What I expected to happen:
Color the overlay image according to state attribute, set opacity according to brightness

What happened instead:
After switching the light off and on again, the card_mod styles are not updated anymore.
The image is actually changed due to the state change of the light (default: grayscaled), so dom manipulation through the picture elements component seems to work, only the card_mod stuff is somehow 'disconnected'

**Minimal** steps to reproduce:
check yaml above

Error messages from the browser console:
After turning on the light again
```
Received event for unknown subscription 34. Unsubscribing.
```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by davideickhoff** [comment]
Thanks for the idea @Fizcko! I tried, but this doesn't make a difference. I see the same behaviour - the component is not updating after toggle off/on.

**Comment by davideickhoff** [comment]
Ok, gave it another shot and the issues was in:
```
filter: {{ 'hue-rotate(' + ((state_attr(config.entity, 'hs_color')[0] - 45)|string if state_attr(config.entity, 'hs_color') else 0) + 'deg)' }};
```
the string concatenation with `0` in the _else_ branch... so changing to 
```
filter: {{ 'hue-rotate(' + ((state_attr(config.entity, 'hs_color')[0] - 45)|string if state_attr(config.entity, 'hs_color') else '0') + 'deg)' }};
```
did the trick.

**Comment by didi767** [comment]
Hi,

I have the same issue. it all started when I just upgraded from 2022 to 2024.
I switched moved from template card with picture-elements to just picture-elements.
when I toggle the switch off I can't get the image updated. @davideickhoff  I tried your method but it doesn't work for me:

`title: NEWww
panel: true
icon: 'mdi:floor-plan'
background: center / cover no-repeat url("/local/back.png") fixed
cards:
  - type: vertical-stack
    cards:
      - type: vertical-stack
        cards:
          - type: vertical-stack #--- the two floors
            cards:
            #second floor
            - type: picture-elements #---- change 2nd floor base image according to the position of the sun
              image: /local/new_floorplan/second_floor/2nd_all_off_night.png
              style: |
                ha-card:first-child {
                  background: rgba(42, 46, 48, 1)
                }
              elements:
              - type: image
                action: none
                entity: sun.sun
                hold_action:
                  action: none
                state_image:
                  above_horizon: /local/new_floorplan/second_floor/2nd_all_off_day.png
                  below_horizon: /local/new_floorplan/second_floor/transparent.png
                style:
                  height: 100%
                  left: 50%
                  mix-blend-mode: lighten
                  opacity: '${ states[''sensor.sunlight_opacity''].state }'
                  top: 50%
                  width: 100%
                tap_action:
                  action: none

                #lights

              - type: image
                image: /local/new_floorplan/second_floor/2nd_master_lights_on.png
                entity: switch.sonoff_mini_master_lights
                tap_action:
                  action: none
                hold_action:
                  action: none
                style:
                  mix-blend-mode: lighten
                  transform: none
                  width: 100%
                  height: 100%
                  top: 0
                  left: 0
                card_mod:
                  style: |
                    :host {
                      opacity: {{ (state_attr(config.entity, 'brightness') / 255) if is_state(config.entity, 'on') else 0.0 }};
                      filter: {{ 'hue-rotate(' + ((state_attr(config.entity, 'hs_color')[0] - 45)|string if state_attr(config.entity, 'hs_color') else '0') + 'deg)' }};
                    }
                  ####################################--------master lights--------####################################  
              #icon:
              #Master Bedroom Lights icon
              - type: state-icon
                title: Master Bedroom Lights
                icon: 'mdi:lightbulb-variant-outline'
                tap_action:
                  action: toggle
                entity: switch.sonoff_mini_master_lights
                style:
                  top: 24%
                  left: 55%
                  --mdc-icon-size: 14px
                  --iron-icon-stroke-color: "#00FFFF"
                  # --iron-icon-height: 17px
                  # --iron-icon-width: 17px
`

any suggestions? maybe there is another workaround that I can try?
at this stage after trying to troubleshoot this for days, I'm thinking about reverting back to 2022 (the only reason I upgraded was an integration that told me that I need a newer version of HA, so I gave it a try, but I'm hopeless at this point).

**Comment by raphaeleduardo42** [comment]
> Ok, gave it another shot and the issues was in:
> 
> ```
> filter: {{ 'hue-rotate(' + ((state_attr(config.entity, 'hs_color')[0] - 45)|string if state_attr(config.entity, 'hs_color') else 0) + 'deg)' }};
> ```
> 
> the string concatenation with 0 (int) in the _else_ branch didn't work... so changing to
> 
> ```
> filter: {{ 'hue-rotate(' + ((state_attr(config.entity, 'hs_color')[0] - 45)|string if state_attr(config.entity, 'hs_color') else '0') + 'deg)' }};
> ```
> 
> did the trick.

Thanks for sharing, your code just worked in 2024.7.3
