### ISSUE TITLE
Car mod not found when casting

### ISSUE THREAD

**Issue by ludoluds** [thomasloven/lovelace-card-mod#249]
My Home Assistant version: 2023.1.6

My lovelace configuration method (GUI or yaml): yaml

What I am doing: using custom:car-mod in a dashboard casted to a Google Nest Hub

What I expected to happen: style is applied when casting (here a Google Nest Hub)

What happened instead: Custom element doesn’t exist

OR 
Using a property
    card_mod:
        style: 
            .: |
             :host {
               padding: 10px !important;
             }
Works fine on a computer, style is not applied when casting.

Error messages from the browser console: /

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by nebriv** [comment]
Also having this issue.

**Comment by SomeoneSinister** [comment]
Same issue here. 
A work around for me was to instead change that style in themes, (in my case) 
```Google Dark Theme:```
   ```# Cards``` 
   ```card-background-color: rgba(51, 255, 173, .2)``` 
  and then choose that theme for the entire dashboard.
 Then all the cards would all show the correct style I wanted.

**Comment by Thomsen-79** [comment]
> Same issue here. A work around for me was to instead change that style in themes, (in my case) `Google Dark Theme:` `# Cards` `card-background-color: rgba(51, 255, 173, .2)` and then choose that theme for the entire dashboard. Then all the cards would all show the correct style I wanted.

can you be more specific for a noob ;) do you type that in every cards or in config.yaml? or how are you using those 3 lines?

**Comment by thomasloven** [comment]
Please try version 3.4.0

**Comment by Thomsen-79** [comment]
> Please try version 3.4.0

Im on 3.4.0 and makes no difference
