### ISSUE TITLE
Video fails to full screen because of cardmod

### ISSUE THREAD

**Issue by Daniel-dev22** [thomasloven/lovelace-card-mod#251]
For videos and more context reproducing the issue see the [Android Issue](https://github.com/home-assistant/android/issues/3268)  I started a few days ago. 

If I remove either card mod or mushroom card and leave the other it works and I have a [video](https://github.com/home-assistant/android/issues/3268#issuecomment-1407628011)  of it working as expected.

I have been told by more than one experienced developer that it's probably card mod. I have been on the latest version of card mod since it was released in 2022. I made 0 dashboard configuration updates before this issue appeared and did not update mushroom card before the issue appeared. It happened out of the blue on the s21 and a few weeks later the s22 again with 0 updates that could be attributed either that I made or automatically by webview.

My Home Assistant version: 2023.2.b3 but this started earlier.

My lovelace configuration method (GUI or yaml): YAML

What I am doing: The video is supposed to become full screen on a single tap.

What I expected to happen:

What happened instead: It is blocked from becoming full screen.

**Minimal** steps to reproduce:
Android 13
Not sure if the phone type matters.
Card mod
Mushroom card
Try to make a video full screen though frigate card or webrtc camera card standalone

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

No errors. 
[console_logs_chrome.log](https://github.com/thomasloven/lovelace-card-mod/files/10535331/console_logs_chrome.log)
[console_logs_companion_app.log](https://github.com/thomasloven/lovelace-card-mod/files/10535332/console_logs_companion_app.log)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
> **Minimal** steps to reproduce:
> Android 13
> Not sure if the phone type matters.
> Card mod
> Mushroom card

This is absolutely NOT clear.
Which card? Which card-mod styles? No code is provided...

**Comment by ildar170975** [comment]
Nobody asked for your entire dashboard’s code. 
If you are interested in solving the issue - then you should try to localize the problem, to define a MINIMAL configuration which may be reproduced by people.
