### ISSUE TITLE
Looking for custom:mod-card

### ISSUE THREAD

**Issue by thisisbenwoo** [thomasloven/lovelace-card-mod#261]
Hi, 

I think my question should be straightforward, but I'm not finding the **custom:mod-card** card. One of my cards, the Mushroom Title Card does not have a ha-card element, and in the documentation [here](https://github.com/thomasloven/lovelace-card-mod#styling-cards-without-an-ha-card-element). It suggests that it should be supplied.

I tried type: custom:mod-card in a Manual card, but it gave me an error. Thanks in advance.

b

**Comment by thomasloven** [comment]
"an error"?
