### ISSUE TITLE
`app-drawer-layout` no longer used

### ISSUE THREAD

**Issue by bramkragten** [thomasloven/lovelace-card-mod#263]
https://github.com/thomasloven/lovelace-card-mod/blob/dd85bd1db8908c74f9d971c1912a1b605a329d52/src/patch/hui-root.ts#LL17C41-L17C58

`app-drawer-layout` is no longer used in 2023.4, we use `mwc-drawer` now.

**Comment by thomasloven** [comment]
Thanks!
