### ISSUE TITLE
Yesterday a new version was released but it was not updated in HA

### ISSUE THREAD

**Issue by Creo2005** [thomasloven/lovelace-card-mod#265]
My Home Assistant version: 0.XX.X
Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 - latest
My lovelace configuration method (GUI or yaml):
yaml
What I am doing:
Installed version 3.2.0
What I expected to happen:

I want to update to the new version 3.2.1

Yesterday a new version was released but it was not updated in HA
How can I update it?
Thanks.

**Comment by dreimer1986** [comment]
Installed by HACS or manually by copying over?
HACS updated Card Mod just fine here.
Manually can't: You have to do that by hand then.

**Comment by risozhor** [comment]
Same
But, I think answer is here:
![2023-03-31_185327](https://user-images.githubusercontent.com/12980782/229170094-99729f51-2312-4d1a-bf65-0e1eb8957a44.png)

**Comment by 7ooL** [comment]
same issue, HA versions
<img width="851" alt="image" src="https://user-images.githubusercontent.com/11856305/230182396-e7c981bb-6398-4d1d-90fd-99f60c5d252e.png">
Card-mod error
<img width="440" alt="Screenshot 2023-04-05 151541" src="https://user-images.githubusercontent.com/11856305/230182581-b5e3a1ff-0510-4372-9f94-0f9c022d92df.png">

**Comment by 7ooL** [comment]
> same issue, HA versions <img alt="image" width="851" src="https://user-images.githubusercontent.com/11856305/230182396-e7c981bb-6398-4d1d-90fd-99f60c5d252e.png"> Card-mod error <img alt="Screenshot 2023-04-05 151541" width="440" src="https://user-images.githubusercontent.com/11856305/230182581-b5e3a1ff-0510-4372-9f94-0f9c022d92df.png">

20 minutes later i got the HA update for 2023.4
