### ISSUE TITLE
Remove april fools joke 2023....

### ISSUE THREAD

**Issue by simonepittis** [thomasloven/lovelace-card-mod#266]
My Home Assistant version: 2023.3.6 - Card-mod version 3.2.0

Please remove this Random rotation... it's not funny :-)

![image](https://user-images.githubusercontent.com/92569194/229266594-9faa19ae-0527-4103-93a4-e5c38957ecc3.png)

**Comment by J-o-h-n-M** [comment]
yes, last year it already got a lot of remarks, but its still there!

**Comment by yjamal01** [comment]
im not seeing that this year - are you sure your cards are updated?

**Comment by simonepittis** [comment]
yes.... I'm sure.

![image](https://user-images.githubusercontent.com/92569194/229293043-4ffd6160-7269-4f13-8417-ed5b59ac52d9.png)

**Comment by langestefan** [comment]
this was already removed in #6f918ab6312241823972b0906fb7fcc1d3e846ed

**Comment by arthurEspooner** [comment]
smells like europeans in here
