### ISSUE TITLE
glass effect??

### ISSUE THREAD

**Issue by z3r0l1nk** [thomasloven/lovelace-card-mod#270]
I'm running latest Home Assistant version and card-mod.

After restart all my dashboards have this "glass" effect, if i disable card-mod the effect is gone.

![image](https://user-images.githubusercontent.com/31653632/230361864-e9330c59-ec70-47da-bbd1-fd473d254957.png)

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Sapofeo** [comment]
+1 for what @z3r0l1nk is describing.  Updated card-mod after LCARS sidebar wouldn't render right.  All pages, dashboard, settings, etc., now have this glass  effect (which is admittedly very cool looking but somewhat difficult to read).  Mobile device renders normally.

**Comment by z3r0l1nk** [comment]
Hi @Sapofeo ,
It's good to know that I'm not the only one.
On my S22 Ultra I don't have this issue, but on the Lenoxo X505 tablet it's the same as on the Web Interface.

**Comment by seamansrl** [comment]
[lcars.zip](https://github.com/thomasloven/lovelace-card-mod/files/11172804/lcars.zip)

Copy the content into "config/themes/lcars" and replace the original file. 

This new theme repairs all original fails and add Picard Seasson 3 Theme.

Create a backup of you original file before copy the new.

good look

**Comment by z3r0l1nk** [comment]
Thank you @seamansrl. It worked! I didn't think that lcars was the problem.
