### ISSUE TITLE
HA 2023.4 Hide header not working 

### ISSUE THREAD

**Issue by Salsalove** [thomasloven/lovelace-card-mod#271]
My Home Assistant version: 2023.4

What I am doing:
I updated to HA 2023.4

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Pirol62** [comment]
card-mod-theme: night_mobile
  card-mod-root: |
    app-header {
      display: none;
    }
    ha-button-menu {
        display: none;
      }

this does not work anymore. Very bad for my alarm clock dashboard

**Comment by ildar170975** [comment]
Has anyone checked a presence of a styled element in DOM?
Probably this element does NOT exist anymore. 
Seems that people just took some theme from Internet without having any idea how it is supposed to be used; and when some element was removed from DOM - these people started complaining “wtf this style does not work” and then create issues on Github. Not a smart behavior.

**Comment by Pirol62** [comment]
@ildar170975  ??
If you replied on my post: Where could I have recognized the breaking change?

I knew very well what we've done. But that way is maybe not available anymore.
Ok, but what could be an alternate solution? Any ideas?

**Comment by Pirol62** [comment]
solved it by replacing app-header with .header:

  card-mod-root: |
    .header {
      display: none;
    }

This issue can be closed

**Comment by ildar170975** [comment]
@Pirol62 
Sorry if I offended you , have no intention to insult you. 
The main thing I want to express is - we cannot use solutions mindlessly , we always have to check ourselves first; DOM structure is NOT a breaking change (from a point of view of HA dev team), it changes from time to time (and every time I have to update my tutorials in the Community); so when something stops working - we should check if a solution is still applicable to a possibly changed DOM.
