### ISSUE TITLE
Unable to update card

### ISSUE THREAD

**Issue by jimmyz5150** [thomasloven/lovelace-card-mod#273]
Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest

My lovelace configuration method (GUI or yaml): HACS

What I am doing: HACS will not update card. Uninstalled and redid same effect.

What I expected to happen: update

What happened instead: sits and spins

**Minimal** steps to reproduce: uninstall via HACS and reinstall 

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console: just spinning for 10 minutes plus

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [] Have made sure I am using the latest version of the plugin.

- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jimmyz5150** [comment]
I've tried to install HACS card-tools... like card-mod it sits there and spins ands pins and spins... Other HACS update no prob

**Comment by soeren2k** [comment]
> I've tried to install HACS card-tools... like card-mod it sits there and spins ands pins and spins... Other HACS update no prob

Same here.

**Comment by jimmyz5150** [comment]
Glad I'm not the only one.. Thanks for posting ur issue as well
