### ISSUE TITLE
Adding UI-Editor to custom card results in error

### ISSUE THREAD

**Issue by flixlix** [thomasloven/lovelace-card-mod#275]
My Home Assistant version: 2023.4.0b6

My lovelace configuration method (GUI or yaml):

GUI

What I am doing:

I am developing the [Power Flow Card Plus](https://github.com/flixlix/power-flow-card-plus) and would like to add a UI-Editor.

What I expected to happen:

If Card-Mod is not installed, I can edit the configuration of my card without any issues.

What happened instead:

When Card-Mod is installed, I get the following error:
![Bildschirmfoto 2023-04-12 um 16 16 36](https://user-images.githubusercontent.com/61006057/231486126-91d7d057-1270-4dbb-902b-8dfa45ed76f8.png)

**Minimal** steps to reproduce:

- Install the latest version of Card Mod
- Install [this](https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1b) version of Power Flow Card Plus
- Add a card in Lovelace and select "Power Flow Card Plus"

Error messages from the browser console:
![Bildschirmfoto 2023-04-12 um 16 17 30](https://user-images.githubusercontent.com/61006057/231486315-7a460233-e904-493a-ba3c-936c87f3c51e.png)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by flixlix** [comment]
I did notice this line:
https://github.com/thomasloven/lovelace-card-mod/blob/b8c48b925643389fea5b1c0185ad7e0cbbd2bb76/src/patch/hui-card-element-editor.ts#L24
and this line:
https://github.com/thomasloven/lovelace-card-mod/blob/b8c48b925643389fea5b1c0185ad7e0cbbd2bb76/src/patch/hui-card-element-editor.ts#L33
in the `hui-car-element-editor.ts` file, maybe the issue is coming from that...

**Comment by flixlix** [comment]
Created #277 which in my case solves the issue

**Comment by ildar170975** [comment]
@flixlix 
Can you post a screenshot when you see this error?

**Comment by Yorkie71** [comment]
I just saw overnight that #277 was closed. @flixlix does this mean that the UI in your excellent Power Flow Plus card will now function?

**Comment by flixlix** [comment]
Yes, this was the new version Release Notes
https://github.com/thomasloven/lovelace-card-mod/releases/tag/3.3.0

**Comment by Yorkie71** [comment]
Excellent. I see it in the update list now. I should be more patient. Great work!
