### ISSUE TITLE
Performance warning in console, with frontend extra_module_url

### ISSUE THREAD

**Issue by askpatrickw** [thomasloven/lovelace-card-mod#282]
My Home Assistant version: 0.XX.X

My lovelace configuration method (GUI or yaml):
Installed Card Mod from HACS, Installed LCARS HA theme from HACS.
Added frontend to YAML.

What I am doing:
I'm using the LCARS HA theme which requires card mod.
Its working, but I notice console errors.

What I expected to happen:
No errors

What happened instead:

Error in console

**Minimal** steps to reproduce:

```yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js
```
Also tried:  `- /local/community/lovelace-card-mod/card-mod.js` but I 
don't get the card mod install log entry.

Error messages from the browser console:

```
card-mod.js:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
card-mod.js:5 CARD-MOD 3.2.2 IS INSTALLED

```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [N\A] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Duplicates https://github.com/thomasloven/lovelace-card-mod/issues/267

**Comment by askpatrickw** [comment]
dupe
