### ISSUE TITLE
Lock icon shows in Popup window as BrowserMod with BLUR functions

### ISSUE THREAD

**Issue by Murcin86** [thomasloven/lovelace-card-mod#283]
My Home Assistant version: 2023.5.4, Card-mod =>3.2.2
I report also as BrowserMod issue but also here that could be a problem with Card-Mod:

Not sure when that start to be a problem but when I use LOCK function in custom:button-card with custom:card-mode and pop up windows (as browser_mod) that sign (LOCK signal) is showing on top... but before was OK - please have a look below:
normal view:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/95655881/f3f330f2-3d7e-490d-9e5a-b2742e1ccca1)
with popup window
![image](https://github.com/thomasloven/lovelace-card-mod/assets/95655881/af3c9d11-b8e1-49d1-941a-7034cc10a1f4)

```
tap_action:
      browser_mod:
        data:
          card_mod:
            style:
              ha-dialog$: |
                div.mdc-dialog__scrim {
                  backdrop-filter: blur(15px) !important;
                  -webkit-backdrop-filter: blur(15px) !important; } 
```
to reproduce need to add LOCK in custom:button-card and then card_mod looks like ignore LOCK sign...

```
      - type: custom:button-card
        **lock:
          enabled: true**
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
This is an issue with the button-card. The icon is not behaving well.
