### ISSUE TITLE
Different Styles

### ISSUE THREAD

**Issue by Maddin1684** [thomasloven/lovelace-card-mod#291]
Hey everyone. I have this code:

` card_mod:
        style: |
          :host {
            --label-badge-red: {% if is_state('person.r', 'home') %} #30d158 {% else %} #ff4040 {% endif %};
          }`

How can I „add“ this code on top?

`style:
          ha-state-label-badge:
            $:
              ha-label-badge:
                $: |
                  .badge-container .label-badge .label span {
                    color: blue;
                    font-size: 6px !important;
                  }  `

is this possible?
Both codes together doesn’t work.

**Comment by ildar170975** [comment]
Suggest to ask similar questions in the [card-mod HA community thread](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744) and use Github only for reporting bugs & proposing FRs.
