### ISSUE TITLE
Not really a bug report, just need help installing

### ISSUE THREAD

**Issue by chesterflaps** [thomasloven/lovelace-card-mod#292]
I have tried to add the custom repository in HACS but it tells me that thomasloven/lovelave card mod exists in store.

Not sure where it exists because I have searched everywhere and I cannot find it.

Can anyone help please?

**Comment by NicholasYamamoto** [comment]
Search for `lovelace-card-mod` in HACS and it should pop up. No need to add a custom repository.

**Comment by giobuc** [comment]
The same for me.... 
surely I'm doing something wrong, I'm still not an expert on Home Assistant.

here's what i do:

I click on HACS button (on the left column)
I click on Integrations (on the new page)
I click on "Explore and download repositories" (the blue button on right-bottom)
....I got a popup window with tons of repositories

If a search "lovelace-card-mod" i got "no repository found"
If i search "card-mod"... the same, "no repository found"
if i search "thomas loven" i got 4 results: 
- browser_mod
- fontawesome
- lovelace_gen
- Hass Favicon

but not card-mod 🙁


what am i doing wrong?
thanks 🙂

**Comment by RN-Say** [comment]
Look under Frontend, not Integrations

**Comment by giobuc** [comment]
> Look under Frontend, not Integrations

thank you!!!!!!! 🙂
