### ISSUE TITLE
Combine fold-entity-row and slider-entity-row

### ISSUE THREAD

**Issue by Slaktmaskin** [thomasloven/lovelace-card-mod#293]
Hi!

Would this be possible?

I have this on a card now:

type: entities
entities:
  - type: custom:fold-entity-row
    head: light.pelare
    entities:
      - light.pelare_1
      - light.pelare_2
      - light.pelare_3

I'd like the "head" to have the slider as well :)

**Comment by ildar170975** [comment]
The issue is not related to the card-mod repo.
