### ISSUE TITLE
Icon color change based on entity state with "tabbed.card" mod

### ISSUE THREAD

**Issue by Jese44** [thomasloven/lovelace-card-mod#295]
So, I'm using tabbed card mode (https://github.com/kinghat/tabbed-card) and in my example i have a tab for every room.
i.e. i have kitchen tab and on tab "title" i have icon which color i'd like to change whenever kitchen has lights on.

--> when lights are off let the icon be normal white/grey. 
when any light of the kitchen light group is on change icon color to yellowish.

I tried different approaches based on your and other users comments but with no success. Then i saw in manual that atm the mod doesn't support some custom cards?

**Comment by ildar170975** [comment]
Similar questions better to ask in the Community:
https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744
Go to 1st post -> link at the bottom - examples for tabbed-card

Leave GitHub for reporting bugs & proposing FRs.

**Comment by Jese44** [comment]
Oh wow, this is excactly what i was looking for (I even was on the same site but seems like i used wrong search terms as usual.)... Huge thanks!
