### ISSUE TITLE
CSS elements/style

### ISSUE THREAD

**Issue by mikekenyon99** [thomasloven/lovelace-card-mod#298]
Hi,

Apologies if this is a stupid question but for a given card in my dashboard how do I find out what the name of the CSS elements are that I can then style?  Do you have to use the Inspector in your web browser and then find out the name of the CLASS= in the  DIV tag?

Thanks

Mike

**Comment by ildar170975** [comment]
> Inspector in your web browser and then find out the name of the CLASS= in the DIV tag?

Correct.
Suggest to check Community thread: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744
Also, check a link at the end of the 1st post, it will give examples which you may use as a starting point.

**Comment by mikekenyon99** [comment]
Much appreciated!

**Comment by ildar170975** [comment]
close the issue then if solved
