### ISSUE TITLE
Card_mod broken on HA 2023.10.0b3 because of document.createElement("developer-tools-event")

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#300]
My Home Assistant version: 2023.10.0b3

My lovelace configuration method (GUI or yaml):

yaml
What I am doing:

```
frontend:

  extra_module_url:
#     - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/resources/card-mod/card-mod.js
```

What I expected to happen:

What happened instead:

No card_mod is functional at all
maybe related to https://github.com/home-assistant/frontend/pull/17869 ?

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:
```
Unhandled Promise Rejection: TypeError: document.createElement("developer-tools-event")._computeParsedEventData is not a function. (In 'document.createElement("developer-tools-event")._computeParsedEventData(t)', 'document.create...
```

**Note:**

I am using an updated version of 3.1.4, because after that [card_mod_icons didn't function anymore, and the issue about that](https://github.com/thomasloven/lovelace-card-mod/issues/268) has never been resolved.
Not sure if that worsens the issue at hand, need some testing to excluded that.

**Update**

with the latest version loaded:

<img width="1130" alt="Scherm­afbeelding 2023-09-30 om 16 56 45" src="https://github.com/thomasloven/lovelace-card-mod/assets/33354141/06c3b851-646c-44a7-9066-15111dafe6df">

card_mod still is completely non functional, and the same error shows in the inspector:

<img width="1115" alt="Scherm­afbeelding 2023-09-30 om 16 57 27" src="https://github.com/thomasloven/lovelace-card-mod/assets/33354141/ee84760a-07fa-4239-bd56-883846b5cb50">

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jazzyisj** [comment]
<img width="320" alt="image" src="https://github.com/thomasloven/lovelace-card-mod/assets/44064559/79ab4788-0737-4877-bba8-c2b5f9b82d5e">

Chrome on Windows

**Comment by Mariusthvdb** [comment]
yes it is, card_mod completely stopped functioning.

downgrading HA to 0b2 doesnt really hurt, and brings back all card_mod, hope this can be a small fix in the resource so we can safely update again
