### ISSUE TITLE
Curious if issue or if I am doing something wrong

### ISSUE THREAD

**Issue by lambros414** [thomasloven/lovelace-card-mod#305]
I installed this add-on per the instructions and also added the lines recommended to config.yaml.

After doing so, something happened to some/all of the other themes I had installed previously.  When I restarted HA, all of my Lovelace screens were white.  When I look to check on the theme that is set for any of my Lovelace pages, and select the theme drop-down, no themes show up.

I ended up restoring HA from a backup to get my themes working again until I got to the bottom of this.

Thanks

**Comment by thomasloven** [comment]
If you had themes installed, you obviously already had a `frontend` section in your configuration.yaml.
Did you just paste another in there without combining them?

That, combined with you first sentence makes me think you have some reading to do before trying card-mod again (it's an advanced feature).

> I installed this add-on per the instructions and also added the lines recommended to config.yaml.
- This is **not** an add-on
- It's **not** "config.yaml"
