### ISSUE TITLE
Screen relative scaling?

### ISSUE THREAD

**Issue by jpettitt** [thomasloven/lovelace-card-mod#319]
Here is what I'd like to do - I have `picture-elements` card with a floor plan that looks great at it's design width(1300 px).  On smaller screen it looks like crap because the image scales but the elements within it don't.

Full res: 
![image](https://github.com/thomasloven/lovelace-card-mod/assets/524856/7e093612-3a97-49ca-b02c-5dd9d1e57ec4)

Small screen:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/524856/e402c8a5-a624-4663-a573-6de4d9d1f301)

What I'd like to do is have a `transform: scale()` on the picture element card to cause it and everything inside it to shrink with the screen.  This would keep the layout but make most of the element unreadable. I'd then like to add a `:hover` scale with the inverse of the top level scale to each child to use it to be full size when hovered.

Sort of like this (hacked example by adding CSS in chrome dev tools) to show the hot tub temperature scaled on hover

![image](https://github.com/thomasloven/lovelace-card-mod/assets/524856/af6b9497-875b-412e-8b15-74b03afc4fd6)

I was looking for way of doing this in plain CSS but I can't `scale(calc(<some value in px eg vw>))` becasue the result is in px and scale wants a float.  I could do it with custom JS and may resort to that but I though I'd ask here if there was a way of doing it that I was missing.

**Comment by ildar170975** [comment]
Answers were provided.
Not a bug / FR.
