### ISSUE TITLE
Uncaught error from Edge 120.0.0.0 on Windows 10 TypeError: Illegal constructor new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144)...

### ISSUE THREAD

**Issue by danielbrunt57** [thomasloven/lovelace-card-mod#324]
My Home Assistant version: 2023.12.3

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Updated card-mod to latest version 3.3.1

What I expected to happen: No errors!

What happened instead: This...
```
Logger: frontend.js.latest.202312082
Source: components/system_log/__init__.py:300
First occurred: 1:03:08 AM (14 occurrences)
Last logged: 1:03:42 AM

Uncaught error from Edge 120.0.0.0 on Windows 10 TypeError: Illegal constructor new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566) C (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) /hacsfiles/lovelace-card-mod/card-mod.js:1:39893
Uncaught error from Edge 120.0.0.0 on Windows 10 TypeError: Illegal constructor new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566) C (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) /hacsfiles/lovelace-card-mod/card-mod.js:1:39893
```
**Minimal** steps to reproduce:
Update to lastest version of card-mod (3.3.1)
---

**By putting an X in the boxes ([]) below, I indicate that I:**
- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Same as https://github.com/thomasloven/lovelace-card-mod/issues/323

**Comment by danielbrunt57** [comment]
See #323
