### ISSUE TITLE
bottom resize

### ISSUE THREAD

**Issue by sp2003** [thomasloven/lovelace-card-mod#325]
Hello, I resized my card using these parameters, but how do I also resize the bottom part? In fact, the cards do not come closer horizontally but remain distant.

```
card_mod:
  style: |
    ha-card {
      width: 230px;
      height: 150px;
    }
```

![Immagine 2023-12-26 120427](https://github.com/thomasloven/lovelace-card-mod/assets/34820831/ccacdf79-91c1-4bd4-8a5c-ff3b538a219f)
![Immagine 2023-12-26 121403](https://github.com/thomasloven/lovelace-card-mod/assets/34820831/eb52b7ec-414e-4f00-9da2-5be285ece196)
![Immagine 2023-12-26 121524](https://github.com/thomasloven/lovelace-card-mod/assets/34820831/12594ed8-b963-4333-ba0d-57d3d106eb93)

**Comment by thomasloven** [comment]
The dashboard is laid out in columns that have a set minimum width.
Layout-card can be used to tweak this.
