### ISSUE TITLE
3.4.0: Style issues with for example background

### ISSUE THREAD

**Issue by pergolafabio** [thomasloven/lovelace-card-mod#329]
My Home Assistant version: 2023.12.4

My lovelace configuration method (GUI or yaml): Yaml

What I am doing: Applying s style

What I expected to happen: Transparant color

What happened instead: uses the theme background, and is not transparant
Rolling back to 3.3.0 fixes it...

```yaml
  style: |
    ha-card {
      box-shadow: none;
      height: 33px;
      background-color: transparent;
      padding: 0px 10px;
      color: var(--header-color);
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by SmarterHomeLife** [comment]
I have similar issues, none of the styling is applied to cards with 3.4.0 but rolling back to 3.3.1 and clearing cache fixed the issue for now.
```
  type: custom:button-card
  style: |
    ha-card {
        background: var(--button-background-color);
        border-radius: var(--border-radius);
        border: var(--border);
        font-family: var(--font-family);
        box-shadow: var(--box-shadow-static);
    }
```

**Comment by Johnyboy1984** [comment]
Good morning,

I am also a user of the Card Mod in Home Assistant and I can confirm that installing the latest update simply deactivates many of my design adjustments or that they are no longer visible and the sometimes ugly frames become visible again.

**Comment by LucasHokerberg** [comment]
I'm also having issues applying customizations.
I'm only using one card-mod card, and all styles are gone.

`card_mod: null
style: |
  ha-card {
    --ha-card-background: red;
    color: white;
  }`

Unfortunately, I updated both card-mod and Home Assistant to the lastest versions at the same time, so I'm not sure which one caused the issues. However, I can confirm reverting back to card-mod 3.3.1 (but keep HA 2023.12.4) gave me back the styling.

**Comment by Mariusthvdb** [comment]
> I have similar issues, none of the styling is applied to cards with 3.4.0 but rolling back to 3.3.1 and clearing cache fixed the issue for now.
> 
> ```
>   type: custom:button-card
>   style: |
>     ha-card {
>         background: var(--button-background-color);
>         border-radius: var(--border-radius);
>         border: var(--border);
>         font-family: var(--font-family);
>         box-shadow: var(--box-shadow-static);
>     }
> ```

no need to use card-mod there, simplynuse the native button-card styling options

**Comment by Mariusthvdb** [comment]
how odd, I have all of my backgrounds all over...

my issue is with styling/modding the sidebar. But thats another topic, so wont pollute here

**Comment by reprogerman** [comment]
Good morning, I have the same problems, style does not work, and there are many things that are not adjusted now

**Comment by Mariusthvdb** [comment]
just experienced something unexpected in the other 3.4.0 issue I opened (and closed just now):

date logging out and back in again, my issues were gone.
might be worth the trouble for your issues here too?

**Comment by Johnyboy1984** [comment]
Good day,

I was hoping you were right. I did everything that could have affected this:
- Restart HA
- Deregistration app
- Logging out of the PC using the browser
- Cache cleared from browser
- Browser closed and then reopened

However, the problem is back and I will go back a version again.

**Comment by reprogerman** [comment]
Does Style have anything to do with card mod? I have style on other cards without card mod, to modify other parameters and it does not work, before it worked, maybe what fails is the style function. Forgive my little knowledge on the subject

**Comment by Mariusthvdb** [comment]
> Does Style have anything to do with card mod? I have style on other cards without card mod, to modify other parameters and it does not work, before it worked, maybe what fails is the style function. Forgive my little knowledge on the subject

always read the documentation....
https://github.com/thomasloven/lovelace-card-mod#quick-start

**Comment by reprogerman** [comment]
![style](https://github.com/thomasloven/lovelace-card-mod/assets/111611057/3d5f778c-3288-46c2-8d68-961ff8a201e9)
This structure has always worked for me.

**Comment by Mariusthvdb** [comment]
That’s because it is backward compatible with how it worked before. 
you should update .

**Comment by pickonedev** [comment]
Same

**Comment by Johnyboy1984** [comment]
I'm fixing the problem. Thank you for the useful tips

**Comment by Mariusthvdb** [comment]
> I have everything updated, card-mod, home assistant, etc., I have everything up to date on updates, I guess that's what you're referring to?

no.
I meant you should update your config using the prescribed keywords and hierarchy, as I showed you, and as is in the documentation.

**Comment by RobertoCravallo** [comment]
Same thing with my HA, but: My fault!!! Bad coding and up to 3.4 it just worked.

Lot of the above examples are missing "card_mod:" before the " style: |" argument, that was my problem. PLUS, faulty indentation. Worked fine till the update, but now that I have corrected my code, all is well.

So check for "card_mod" and faulty indentation. It will work, if you fix that.

**Comment by RobertoCravallo** [comment]
card_mod: null
style: |
  ha-card {
    --ha-card-background: red;
    color: white;
  }

No good!!! Loose the null and correct the indentation. Then it should work.

card_mod:
  style: |
    ha-card {
      --ha-card-background: red;
      color: white;
    }

This should work...

**Comment by Mariusthvdb** [comment]
yep, as I hoped it would..

please format your code with code block <> in the editor

**Comment by RobertoCravallo** [comment]
> code block <> in the editor

But that formats the code differently from the way I want it to show!!!

**Comment by reprogerman** [comment]
> > Tengo todo actualizado, card-mod, asistente de casa, etc, tengo todo al día en actualizaciones, ¿supongo que a eso te refieres?
> 
> No. Quise decir que deberías actualizar tu configuración usando las palabras clave y la jerarquía prescritas, como te mostré y como está en la documentación. `custom: bar-card `Utiliza el formato antiguo de hace más de 3 años, también debería actualizarse, pero parece que ya no se mantiene.
> 
> Probablemente esto sea todo además de cualquier problema aquí, así que si no lo hace, haga lo que quiera, solo intentará ayudar a reducir cualquier motivo de error.

Thank you very much, what's wrong is that, now you have to put card_mod: in all the styles where you didn't have it before. Thank you very much mate!!

**Comment by LucasHokerberg** [comment]
I can confirm removing the "null" part and making sure the intendation is correct. solved the issue.
Thanks for the help!

**Comment by pergolafabio** [comment]
Hmm, i believe it doesnt fix my issue, i use declutter cards as example below, intendation is correct?

```
card:
  type: markdown
  style: |
    ha-card {
      box-shadow: none;
      height: 33px;
      background-color: transparent;
      padding: 0px 10px;
      color: var(--header-color);
    }
  content: '[[content]]'
```

```
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Some text...'   
```

I have a transparant background with card mod 3.3.0 , when i update to 3.4.0 , there is no transparant anymore?

**Comment by LucasHokerberg** [comment]
> Hmm, i believe it doesnt fix my issue, i use declutter cards as example below, intendation is correct?
> 
> ```
> card:
>   type: markdown
>   style: |
>     ha-card {
>       box-shadow: none;
>       height: 33px;
>       background-color: transparent;
>       padding: 0px 10px;
>       color: var(--header-color);
>     }
>   content: '[[content]]'
> ```
> 
> ```
>       - type: custom:decluttering-card
>         template: header
>         variables:
>           - content: '##### Some text...'   
> ```
> 
> I have a transparant background with card mod 3.3.0 , when i update to 3.4.0 , there is no transparant anymore?

Nope, that's not right. Remove two spaces before everything within {}.

```
style: |
  ha-card {
  box-shadow: none;
  height: 33px;
  background-color: transparent;
  padding: 0px 10px;
  color: var(--header-color);
    }
```

**Comment by pergolafabio** [comment]
Hmm, same issue, i have it now like:

```
card:
  type: markdown
  style: |
    ha-card {
    box-shadow: none;
    height: 33px;
    background-color: transparent;
    padding: 0px 10px;
    color: var(--header-color);
    }
  content: '[[content]]'
```

**Comment by Mariusthvdb** [comment]
Still missing card_mod:

**Comment by pergolafabio** [comment]
yeah, but thats strange, i dont use card_mod: there, but card_mod breaks it?

now tested with below, but same issue

```
card:
  type: markdown
  card_mod:
  style: |
    ha-card {
    box-shadow: none;
    height: 33px;
    background-color: transparent;
    padding: 0px 10px;
    color: var(--header-color);
    }
  content: '[[content]]'
```

**Comment by Mariusthvdb** [comment]
Cmon…
That mod Is card_mod, where else did you think it came from.

and you need correct yaml….

**Comment by pergolafabio** [comment]
```
yeah, sorry, its a bit new to me

but whyats wrong then with this yaml? i removed the 2 spaces under ha-card ...

card:
  type: markdown
  card_mod:
  style: |
    ha-card {
    box-shadow: none;
    height: 33px;
    background-color: transparent;
    padding: 0px 10px;
    color: var(--header-color);
    }
  content: '[[content]]'
```

**Comment by FancyNerd92** [comment]
Problem with 3.4.0 and bar-card. As you see not working at all.

v3.3.1 working like a charm:
![Screenshot 2023-12-28 185845](https://github.com/thomasloven/lovelace-card-mod/assets/76796004/97997263-393c-4e2d-9cd5-ce4082e22c13)

v.3.4.0 broken....:
![Screenshot 2023-12-28 184746](https://github.com/thomasloven/lovelace-card-mod/assets/76796004/21dca89d-1d68-4562-9991-c647a646b530)

**Comment by ildar170975** [comment]
So, instead of discussing bugs people have to sort out a wrongly written card-mod styles.

**Comment by Mariusthvdb** [comment]
> ```
> yeah, sorry, its a bit new to me
> 

…. please don’t , you’ve been around for years now ,-)

see https://github.com/thomasloven/lovelace-card-mod/issues/329#issuecomment-1871107636 again

**Comment by pergolafabio** [comment]
> > ```
> > yeah, sorry, its a bit new to me
> > ```
> 
> …. please don’t , you’ve been around for years now ,-)
> 
> see [#329 (comment)](https://github.com/thomasloven/lovelace-card-mod/issues/329#issuecomment-1871107636) again

But , I was never good with styling:-)

**Comment by LucasHokerberg** [comment]
> ```
> yeah, sorry, its a bit new to me
> 
> but whyats wrong then with this yaml? i removed the 2 spaces under ha-card ...
> 
> card:
>   type: markdown
>   card_mod:
>   style: |
>     ha-card {
>     box-shadow: none;
>     height: 33px;
>     background-color: transparent;
>     padding: 0px 10px;
>     color: var(--header-color);
>     }
>   content: '[[content]]'
> ```

The whole "style:" must be intended under card_mod.

**Comment by pergolafabio** [comment]
ok, fixing yaml now works

But seems the behaviour is still different, on every page view or refresh i see the card mod applying the card, i dont notice that on 3.3.0
On 3.3.3 my cards are immediately transparant
on 3.4.0 my card first have a background color,  and it goes away in less then a second, its a flickr only, but i see it evenrytime

**Comment by Mariusthvdb** [comment]
> ok, fixing yaml now works
> 


As expected. Good to hear you finally got it ;/)

Please close
