### ISSUE TITLE
Reoccurrence of issue #327 in Home Assistant Android app

### ISSUE THREAD

**Issue by dd310** [thomasloven/lovelace-card-mod#336]
My Home Assistant version: 2024.1.0b2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: 

Even after updating card_mod to version 3.4.0, the error described in issue #327 keeps appearing:

![photo_2023-12-30_21-42-04](https://github.com/thomasloven/lovelace-card-mod/assets/17815448/0eb47e55-676d-4ca4-a159-3d18d3c5dc12)

Home Assistant Android app is updated to the latest version. It is not a consistent behaviour: sometimes it gives this error, sometimes (rarely) it loads correctly.

The issue never occurs using Chrome (desktop or mobile).

```
Logger: frontend.js.latest.202312280
Source: components/system_log/__init__.py:300
First occurred: 20:19:53 (48 occurrences)
Last logged: 20:20:15

Uncaught error from Chrome WebView 120.0.6099.144 on Android 13 TypeError: Illegal constructor new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566) E (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) /hacsfiles/lovelace-card-mod/card-mod.js:1:39893
Uncaught error from Chrome WebView 120.0.6099.144 on Android 13 TypeError: Illegal constructor new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733) o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566) E (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) /hacsfiles/lovelace-card-mod/card-mod.js:1:45196
Uncaught error from Chrome WebView 120.0.6099.144 on Android 13 TypeError: Illegal constructor new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144) r.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236) r.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733) r.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380) new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:64046) E (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) createErrorCardConfig (src/panels/lovelace/create-element/create-element-base.ts:91:27)
```

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by dd310** [comment]
Thanks for the fix, it worked.
To anyone that was having the same issue, remember that you may have to manually clear the cache for the companion app.

**Comment by thomasloven** [comment]
Thanks for the feedback!
