### ISSUE TITLE
Failed to resolve module

### ISSUE THREAD

**Issue by antivirus68** [thomasloven/lovelace-card-mod#34]
My Home Assistant version: 0.105.4

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

Try to use it.

What I expected to happen:

To load correctly

What happened instead:

I get an error.

**Minimal** steps to reproduce:

Just install it and add this to ui-lovelace.yaml

```
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module  

  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module

```
Error messages from the browser console:

```
(anonymous) @ bootstrap:83
(anonymous) @ calendar-card.js:1
index.js:21   CALENDAR-CARD     Version 3.108.2 
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.9.2 
button-card.js:1430   BUTTON-CARD   Version 3.1.0 
card-tools.js:1 CARD-TOOLS 2 IS INSTALLED  DeviceID: 0beeac99-09d49201
0:1 Uncaught TypeError: Failed to resolve module specifier "card-tools/src/templates.js". Relative references must start with either "/", "./", or "../".
simple-thermostat.js:1 simple-thermostat: 0.34.0
custom-header.js:145   CUSTOM-HEADER    Version 1.3.2  
banner-card.js:4 banner-card: 0.9.0
atomic_calendar.js:1 atomic_calendar v0.8.9 loaded

```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by i00** [comment]
Try using the other card-mod.js ... I suspect you are using the un-compiled one.

**Comment by jghaanstra** [comment]
I can confirm this issue. Lastest version completely broke down.

**Comment by tommyjlong** [comment]
I have been getting the same error for sometime, but have ignored.  However since moving lovelace resources to configuration.yaml in .107 these are now appearing in the homeassistant logs.

This appears to be coming from card-mod.js line 1
`import {subscribeRenderTemplate} from "card-tools/src/templates.js";`

**Comment by thomasloven** [comment]
This was a problem with HACS that should have been fixed.
If it's still a problem, please try reinstalling the card.
