### ISSUE TITLE
Card_mod in Entities disappears

### ISSUE THREAD

**Issue by duczz** [thomasloven/lovelace-card-mod#344]
My Home Assistant version: 2024.1.0

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
when i add these code snipped in an entities yaml, it is away and not be saved when i change something else in the entities, is that normal?
`card_mod:
  style: |
    ha-card {
    --ha-card-border-width: 0;
    --card-primary-font-weight: normal;
    margin-left: -13px;
    mushroom-shape-icon 
      {
      --shape-color: none;
      --icon-color: #44739e;
      }
    }`

What I expected to happen:
i add a card_mod to remove the boarder

What happened instead:
card_mod is working, but when i add a new entitie card_mod is away in the other entitie

![tracklist](https://github.com/thomasloven/lovelace-card-mod/assets/25475385/eff736c3-a232-4aab-ab09-a362c8ce586c)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
seems to same as https://github.com/thomasloven/lovelace-card-mod/issues/337

**Comment by duczz** [comment]
Info: This problem is only when i use card_mod in entities

example:
```type: entities
entities:
  - entity: input_boolean.heizperiode
    name: Heizperiode
    icon: mdi:thermostat-box-auto
  - type: custom:mushroom-select-card
    entity: input_select.advanced_heating_control_wohnzimmer_scheduler
    name: Scheduler
    icon: mdi:calendar-month-outline
    layout: horizontal
    secondary_info: none
    card_mod:
      style: |
        ha-card {
        --ha-card-border-width: 0;
        --card-primary-font-weight: normal;
        margin-left: -13px;
        mushroom-shape-icon 
          {
          --shape-color: none;
          --icon-color: #44739e;
          }
        }
```

**Comment by ildar170975** [comment]
Read 1 post above.
Besides, your card-mod code is wrong. Suggest to ask in Community first.

**Comment by duczz** [comment]
Update in my post: With correct Card-mod style the same result:

'''
card_mod:
  style: |
    ha-card {
      --ha-card-border-width: 0;
      --card-primary-font-weight: normal;
      margin-left: -12px;
    }
    mushroom-shaped-icon {
      --shape-color: none;
      --icon-color: #44739e;
    }
'''

**Comment by ildar170975** [comment]
Very persistent man. Two time you were told that the issue was already registered and yet you keep posting here.

**Comment by duczz** [comment]
yep, **you** said, and **it looks** like.
My oppinion is a different one.

**Comment by duczz** [comment]
i find out that the card_mod code will be removed only when card_mod is not fully loaded (in my case)

here card_mod is not fully loaded 1: (see border below the blue background)
when i remove something in UI mode the code will be remvoed, but when card_mod is fully loaded picture 2, the code will be there, its hard to see when card_mod is loaded when you have for example entities card...
1:
![image](https://github.com/user-attachments/assets/e99b5d1d-7023-4048-90b7-e92198405afa)
2: 
![image](https://github.com/user-attachments/assets/e0d88b42-ba1b-47fb-bd3a-418d1966fb7b)
