### ISSUE TITLE
Card-mod Popup Impacts Subview Back Button

### ISSUE THREAD

**Issue by jmillnik** [thomasloven/lovelace-card-mod#362]
My Home Assistant version: 2024.2.5

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Opening card-mod Popup with a button on a Subview.

What I expected to happen:
After closing the card-mod Popup, the back button should take me to the dashboard page I navigated to the Subview from.

What happened instead:
The back button requires n+1 presses to navigate to the previous dashboard page where n is the number of times the card mod popup was opened.

**Minimal** steps to reproduce:
1. Create main view with navigation button to subview
2. Create Subview
3. Create button on Subview with a card-mod pop up
4. Navigate to subview, open card mod, close card mod, press Subview back button. No navigation happens. Press again. Navigation works as expected.

Error messages from the browser console:
No console error
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
> Opening card-mod Popup with a button on a Subview.

What is this?
Post a code & a picture.

**Comment by ildar170975** [comment]
> * Create button on Subview with a card-mod pop up
> 
> * Navigate to subview, open card mod, close card mod, press Subview back button. No navigation happens. Press again. Navigation works as expected.

This has no sense.
Are you sure you are posting in a correct repo?

**Comment by jmillnik** [comment]
Sorry - wrong thomasloven repo - was supposed to be for browser_mod. Moving and closing.
