### ISSUE TITLE
Error update from 0.106

### ISSUE THREAD

**Issue by tantararin** [thomasloven/lovelace-card-mod#37]
My Home Assistant version:0.106

My lovelace configuration method (GUI or yaml): Yaml

Hello, in my configuration I wrote this code and it worked fine before 105.5, but the 106 update gives me errors. You can help?
  I previously worked with card-modder and I am changing everything to this card.

In Google Chrome, I cleared the cache and it works, in Firefox too, ... but in the Android app it's still happening.
  Thank you for your work, it is very good !!!!!!!

This is the code:

     - type: custom:mod-card

       style: |  
         ha-card {                
           background-repeat: no-repeat;
           background-size: 100% 68px;
           background-image: url("/local/lovelace/cardbackK.png");
           border-radius: 10px;
           border: solid 1px rgba(100,100,100,0.3);
           box-shadow: 3px 3px rgba(0,0,0,0.4);     
           overflow: hidden;
           --ha-card-background: rgba(0,0,0,0) 
         }  
       card:                                

         type: entities
         title: Comedor Sur         
         show_header_toggle: false
         entities:
           - type: custom:vertical-stack-in-card
             cards:
               - type: custom:mod-card
                 card:
                    type: glance
                    show_header_toggle: false
                    entities: 
                     - entity: binary_sensor.puerta_sur
                       name: Puerta
                     - entity: binary_sensor.ventana_cocina
                       name: Cocina 
                     - entity: binary_sensor.balcon_comedor_sur
                       name: Balcón
                     - entity: binary_sensor.ventana_escaleras
                       name: Escalera
                     - entity: binary_sensor.ventana_mesa  
                       name: Mesa

                 style: |  
                   ha-card {
                     margin: 0px !important;
                     background: transparent;
                   }
               - type: custom:mod-card
                 card:
                   type: thermostat
                   entity: climate.kuc0000725  

                 style: |  
                   ha-card {      
                     margin: 0px !important;
                     background: transparent;    
                   }             
               - type: custom:mod-card
                 card:
                    type: glance
                    show_header_toggle: false
                    entities: 
                     - switch.rele_1         
                     - sensor.temperatura_actual_sur
                     - sensor.temperatura_fijada_sur
                     - sensor.valvula_sur
                     - entity: binary_sensor.kuc0000725_lowbat
                       name: Batería
                 style: |  
                   ha-card {
                     margin: 0px !important;
                     color: transparent;
                  }

# End of code

Error messages from the browser console:

Cannot assign to read only property 'style' of object '#<Object>'
type: 'custom:mod-card'
style: |
  ha-card {                
    background-repeat: no-repeat;
    background-size: 100% 68px;
    background-image: url("/local/lovelace/cardbackK.png");
    border-radius: 10px;
    border: solid 1px rgba(100,100,100,0.3);
    box-shadow: 3px 3px rgba(0,0,0,0.4);     
    overflow: hidden;
    --ha-card-background: rgba(0,0,0,0)     
card:
  type: entities
  title: Comedor Sur
  show_header_toggle: false
  entities:
    - type: 'custom:vertical-stack-in-card'
      cards:
        - type: 'custom:mod-card'
          card:
            type: glance
            show_header_toggle: false
            entities:
              - entity: binary_sensor.puerta_sur
                name: Puerta
              - entity: binary_sensor.ventana_cocina
                name: Cocina
              - entity: binary_sensor.balcon_comedor_sur
                name: Balcón
              - entity: binary_sensor.ventana_escaleras
                name: Escalera
              - entity: binary_sensor.ventana_mesa
                name: Mesa
          style: |
            ha-card {
              margin: 0px !important;
              background: transparent;
            }
        - type: 'custom:mod-card'
          card:
            type: thermostat
            entity: climate.kuc0000725
          style: |
            ha-card {      
              margin: 0px !important;
              background: transparent;    
            }             
        - type: 'custom:mod-card'
          card:
            type: glance
            show_header_toggle: false
            entities:
              - switch.rele_1
              - sensor.temperatura_actual_sur
              - sensor.temperatura_fijada_sur
              - sensor.valvula_sur
              - entity: binary_sensor.kuc0000725_lowbat
                name: Batería
          style: |
            ha-card {
              margin: 0px !important;
              color: transparent;
            }

---
![mod_card](https://user-images.githubusercontent.com/46560835/75430783-1dc41e00-594c-11ea-9288-f61cf53bd93a.png)

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ ] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by rpitera** [comment]
Also having issues with mod-card in combination with vertical-stack-card and horizontal stack.  Seems to be something in the styling because once I removed card-mod and the style related to it, the cards loaded properly.

```
  - type: custom:mod-card
    style: |
      ha-card {
        color: cyan;
        background-image: url("/local/bg/laserBlack.png");
        background-size: cover;
        background-color: rgba(255,255,255,0.1);
        background-blend-mode: overlay;
      }
      ha-card .card-header {
        text-shadow: 2px 2px 3px black;
      }
    card:
      type: custom:vertical-stack-in-card
      title: Brother Laser MFC-L3770CDW
      cards:
        - type: glance
          columns: 4
          style: |
            ha-card {
              color: cyan;
              --paper-item-icon-color: cyan;
            }
          entities:
            - entity: sensor.mfc_l3770cdw_status
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: Status
            - entity: sensor.mfc_l3770cdw_uptime
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: Uptime
            - entity: sensor.mfc_l3770cdw_belt_unit_remaining_life
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: Belt Unit
            - entity: sensor.mfc_l3770cdw_fuser_remaining_life
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: Fuser
            - entity: sensor.mfc_l3770cdw_b_w_counter
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: B&W Pages
            - entity: sensor.mfc_l3770cdw_color_counter
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: Color Pages
            - entity: sensor.mfc_l3770cdw_page_counter
              style: |
                :host {
                  color: cyan;
                  background-color: rgba(60, 60, 60, 0.5);
                  border-radius: 15px;
                  border: 1px solid cyan;    
                }
              name: Total Pages
              

        - type: horizontal-stack
          cards:  
            - type: custom:bar-card
              entity: sensor.mfc_l3770cdw_cyan_toner_remaining
              align: center-split
              height: 80px
              direction: up
              color: cyan
              title: Cyan
              title_position: bottom
              value_style:
                text-shadow: "2px 2px 3px #000000"

            - type: custom:bar-card
              entity: sensor.mfc_l3770cdw_magenta_toner_remaining
              align: center-split
              height: 80px
              direction: up
              color: magenta
              title: Magenta
              title_position: bottom
              value_style:
                text-shadow: "2px 2px 3px #000000"

            - type: custom:bar-card
              entity: sensor.mfc_l3770cdw_yellow_toner_remaining
              align: center-split
              height: 80px
              direction: up
              color: yellow
              title: Yellow
              title_position: bottom
              value_style:
                text-shadow: "2px 2px 3px #000000"

            - type: custom:bar-card
              entity: sensor.mfc_l3770cdw_black_toner_remaining
              align: center-split
              height: 80px
              direction: up
              color: '#1C2833'
              title: Black
              title_position: bottom
              value_style:
                text-shadow: "2px 2px 3px #000000"
```

The problem seems to be in this block (all the other style statements work fine):

  ```
- type: custom:mod-card
    style: |
      ha-card {
        color: cyan;
        background-image: url("/local/bg/laserBlack.png");
        background-size: cover;
        background-color: rgba(255,255,255,0.1);
        background-blend-mode: overlay;
      }
      ha-card .card-header {
        text-shadow: 2px 2px 3px black;
      }
```
I tried removing each one separately to see if I could determine whether it was ha-card or ha-card .card-header causing the problem but either one seems to cause it to 'red-box'.

HomeAssistant 0.106.1 - tested in Chrome and FF with same results.  For now, just removing the custom:mod-card block and correcting the indents, I can load the cards without issue and the styling contained within the elements works fine.  Seems to be confined to mod-card.

Let me know if I can provide any more information.

**Comment by tantararin** [comment]
It works well for me with that code in chrome, firefox and explorer.
It only gives me problems in the Android application GooglePlay.

**Comment by shreram** [comment]
I am in the same boat. 

```
          - type: 'custom:mod-card'
            <<: *card_style_anchor
            card:
              type: custom:weather-card
              entity: weather.dark_sky
              # current: true
              details: true
              forecast: true
```

```
  card_style: &card_style_anchor
      style:
        .: |
          ha-card {
            border-radius: 20px;
            overflow: hidden;
            width: 89%;
            margin: 0 auto;
            padding-top: 0px;
          }
```

> create-element-base.ts:64 mod-card TypeError: Cannot assign to read only property '.' of object '#<Object>'
>     at HTMLElement.setConfig (card-mod.js:1)
>     at o (create-element-base.ts:61)
>     at a (create-element-base.ts:80)
>     at l (create-element-base.ts:131)
>     at Module.Hi (create-card-element.ts:88)
>     at layout-card.js:1
>     at HTMLElement.build_card (layout-card.js:1)
>     at layout-card.js:1
>     at Array.map (<anonymous>)

**Another card:**

```
                  - type: 'custom:mod-card'
                    <<: *headertext
                    card:
                      content: "## Control Panel"
                      type: markdown
```

```
  header_text: &headertext
    style:
      border-radius: 12px
      --paper-card-background-color: 'rgba(0, 0, 0, 0.0)'
      box-shadow: 2px 2px rgba(0,0,0,0.0)
      padding: 0px 10px
      height: 33px
```

> create-element-base.ts:64 mod-card TypeError: Cannot add property ., object is not extensible
>     at HTMLElement.setConfig (card-mod.js:1)
>     at o (create-element-base.ts:61)
>     at a (create-element-base.ts:80)
>     at l (create-element-base.ts:131)
>     at Hi (create-card-element.ts:88)
>     at HTMLElement._createCardElement (hui-stack-card.ts:77)
>     at hui-stack-card.ts:39
>     at Array.map (<anonymous>)
>     at HTMLElement.setConfig (hui-stack-card.ts:38)
>     at state-switch.js:1

**Comment by tantararin** [comment]
Solution:  Update Supervisor 209

**Comment by damiano75** [comment]
```yaml
type: 'custom:mod-card'
style: |
  ha-card {
    border: 1px solid green;
  }
card:
  type: vertical-stack
  cards:
    - type: light
      entity: light.comodino
    - type: light
      entity: light.damiano
```
Supervisor 209
HassOS 3.12
Home Assistant 0.106.6

![image](https://user-images.githubusercontent.com/47896789/76436371-6ce06900-63b8-11ea-806a-622adbdc88b7.png)

**Comment by damiano75** [comment]
Any news?

**Comment by shreram** [comment]
@damiano75  There is no need to mention type: 'custom:mod-card'

Try this way.

```
      - type: vertical-stack
        cards:
          - type: light
            style: |
              ha-card {
                font-variant: small-caps;
              }
            entity: light.comodino
          - type: light
            style: |
              ha-card {
                border: 1px solid green;
              }
            entity: light.damiano
```

**Comment by damiano75** [comment]
This is not what I need.
I want the green border around all the vertical stack, not only around one
card in the vertical stack

Ciao

Damiano


Il giorno gio 16 apr 2020 alle ore 19:26 Ravi K <notifications@github.com>
ha scritto:

**Comment by thomasloven** [comment]
Please try relase 14, and please stop abusing mod-card. See https://github.com/thomasloven/lovelace-card-mod#mod-card
