### ISSUE TITLE
Position: Sticky not working in mobile app

### ISSUE THREAD

**Issue by UberDudePL** [thomasloven/lovelace-card-mod#379]
My Home Assistant version: 2024.6.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Adding a footer as posistion: sticky to have it float in my dashboard

What I expected to happen:
Footer is floating
![image](https://github.com/thomasloven/lovelace-card-mod/assets/91315950/ac94d9a5-0729-4cf7-afe3-6c46549c8a78)

What happened instead:
PC it is working fine, in mobile app it does not
![WhatsApp Image 2024-06-12 at 19 33 10_938b97b9](https://github.com/thomasloven/lovelace-card-mod/assets/91315950/053b404f-d2e2-418b-ad0b-3a9308427bda)

**Minimal** steps to reproduce:

```
card_mod:
  style: |
    :host {
      position: sticky !important;
      bottom: 26px;
      margin-bottom: 10px !important;
      animation: 1.2s position ease-in-out;
    }
    @keyframes position {
      0% { bottom: -80px; }
      20% { bottom: -80px; }
      70% { bottom: 26px; }
      90% { bottom: 24px; }
      100% { bottom: 26px; }
    }
    ha-card { 
      background: none;
      border-radius: 26px !important;
    }
    :host:before {
      content: '';
      display: block;
      position: absolute;
      bottom: -26px;
      left: -8px;
      padding-right: 16px;
      height: 130px;
      width: 100%; 
      background: linear-gradient(180deg, rgba(45, 56, 76, 0) 0%, rgba(35, 46, 66, 0.85) 50%);
      pointer-events: none;
      animation: 1.2s opacity ease-in-out;
    }
    @keyframes opacity {
      0% { opacity: 0; }
      20% { opacity: 0; }
      100% { opacity: 1; }
    }
```
Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by UberDudePL** [comment]
When I reverted back to 2024.5.X, it stared to work correctly. I've updated test VM to 2024.6.2 and it stopped working

**Comment by ildar170975** [comment]
Post a properly formatted code.
Use triple "`".

**Comment by UberDudePL** [comment]
Apologies, corrected the code.

**Comment by UberDudePL** [comment]
I didn't do anything with HA but sticky position stopped working on PC as well. It is at the bottom of dashboard

**Comment by ildar170975** [comment]
2024.6 does have some changes.
But this is most probably not a "card-mod bug" - you just need to ADAPT your code.
Suggest to close the issue & ask in Community.
And when asking in Community - do not forget to add some more details: you posted a card-mod code but missed a card to which you wish to apply this code.

**Comment by UberDudePL** [comment]
I will close it, looks like there is someelse with the same problem but they did not create reply in community of card_mod. I just did
