### ISSUE TITLE
Dynamic title for card?

### ISSUE THREAD

**Issue by ultimate-tester** [thomasloven/lovelace-card-mod#382]
I'm trying to create a translation of my dashboard based on the language set in the user's profile settings.
What I want to achieve is something like the following:

```
type: custom:mod-card
        view_layout:
          grid-area: first_floor
        card:
          type: grid
          title: |
            [[[
              if (user.language === 'nl') return '1e Verdieping';
              return 'First Floor';
            ]]]
```

Unfortunately this just displays the raw code as the title, it's not executed. Would it be possible to have a dynamic title for a card?

**Comment by Mariusthvdb** [comment]
use `custom:button-card `for that probably easiest
style it like the header in an entities card and you're set.
I do that all over and have it use dynamic titles and colors

also, **this is not an issue**, so please close and hop over to the community thread where all of this can be discussed
