### ISSUE TITLE
Fade Animation on Page Load

### ISSUE THREAD

**Issue by NeptunePy** [thomasloven/lovelace-card-mod#388]
Hi,

I'm currently using Home Assistant version 2024.7.4.

**What I'm Trying to Achieve:**
I am attempting to add a fade animation to `ha-card` elements on page load, so that the cards gradually appear with a fade effect.

**Issue:**
When the page loads, I notice that the Lovelace cards momentarily flash before the fade animation takes effect. This flash occurs prior to the intended fade transition.

**Expected Behavior:**
The cards should seamlessly transition into view with the fade animation without any visible flashing.

**Steps to Reproduce:**
1. Implement fade animation on `ha-card` elements.
2. Reload the page.

**Additional Information:**
I’m not sure if this is a real issue, and I apologize if I’m wasting your time. However, if there are any recommended approaches or solutions to prevent the cards from flashing before the fade effect, I would greatly appreciate your guidance!

Thank you!

Here is an example yaml : 
```
card_mod:
    style: |
        ha-card {
          opacity: 0;
          animation: fadeIn 2s ease-in-out forwards;
        }

        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }
```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Mariusthvdb** [comment]
this is a support question, and an interesting one ;-)

please close here, and hop over to the community as the first item you ticked above suggests.

css animation can be tricky and opening/joining a post there can be helpful to others too.
Maybe search the particular issue first, others may already have reported an effect like it
thanks

**Comment by NeptunePy** [comment]
Understood, sorry for the inconvenience. Have a great day!
