### ISSUE TITLE
Card mod not working in new section view?

### ISSUE THREAD

**Issue by xteaun** [thomasloven/lovelace-card-mod#389]
I am trying to get card-mod to work with a new Home Assistant instance. It works in the standard dashboard layout, but not in the new sections view. Am I doing something wrong?

Christian

**Comment by Maxcodesthings** [comment]
Duplicate #383

**Comment by Mariusthvdb** [comment]
please close. this is for bug issues, not for questions or configuration discussions. go to the community and check what's been said there

**Comment by xteaun** [comment]
Since I have no problems using Card mod on my other HA installation, I believe this may be a bug.

**Comment by ildar170975** [comment]
@xteaun 
1. You told nothing about a particular card-mod code you failed to use - and keep insisting that this is a bug. It could be a bug, could be not - it only may be investigated after some analysis. That is why you were advised to ask in Community first.
2. Sections are still EXPERIMENTAL - i.e. many stuff (cards/plugins/etc) may not work there.

**Comment by xteaun** [comment]
I did not mention any particular code because none of it works. But nevermind. I will get it sorted out without your help. I do not quite get what the problem is. I was actually trying to help improve the add on. But I guess that is not appreciated by some.

**Comment by ildar170975** [comment]
Guess you understood my intentions in an absolutely wrong way.
Did not mean to offend you, wished only to help; congratulations.

**Comment by xteaun** [comment]
Well that was of great help... thx a lot.

**Comment by Mariusthvdb** [comment]
> But I cannot find any mistake

neither can we if you dont post anything you did

post in the card-mod thread in the community and people can at least have a look.
