### ISSUE TITLE
Allow Home Assistant to Automatically Extract Entities from Jinja Templates.

### ISSUE THREAD

**Issue by jcwillox** [thomasloven/lovelace-card-mod#39]
I guess this is kinda a feature request.

I've been working quite a bit lately with the `subscribeRenderTemplate` method and rendering Jinja from the frontend. With reference to `card-mod.js`. I noticed that HA will extract entities from the template automatically and update the template as needed, but once you define `entity_ids` it will no longer extract entities. And as I'm pretty sure your aware of based on your code in `card-mod.js`, HA won't extract an entity from `config.entity`, so you have to manually specify it in `entity_ids`.

I did a bit of testing and found that it will extract an entity_id from non-nested variables. 
For example if your variables are
```json
{
  "config": {
    "entity": "myid"
  },
  "entity": "myid"
}
```
and you use a template such as `"{{ states(entity) }} {{ states("anotherid") }}"`,
HA will be able to extract "myid" and "anotherid".

Having people use `entity` instead of `config.entity` would remove the need for `entity_ids` (naturally excluding templates that don't use an entity).

It's a little quirky but I thought I'd just mention it.

HA's extract entities method [here](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/template.py#L76).

**Comment by thomasloven** [comment]
Hi. I held off on this one because I knew there were some changes to the template processing coming up.

That turned out to take quite a bit longer than I expected, but now since 0.115, `entity_id` is not used anymore since the entity extraction has become significantly more intelligent.

Thanks!
