### ISSUE TITLE
Card-mod right justified text failing on HA 2024.8

### ISSUE THREAD

**Issue by scargill** [thomasloven/lovelace-card-mod#390]
Hi
HA (Docker) 2024.8

Yaml code in a tile....

I've been using this same code for moist of my tiles... 

card_mod:
  style: |
    ha-card {
      border: 1px solid darkcyan;
      background-color: #004466;
      text-align: right;
    }

and it has produced nicely right-justified text since HA 2024.6 until yesterday - the HA update to 2024.8

So, simple tile card turning something on or off.. above code added in YAML... see result since yesterday - right-justified but no longer clinging to the right side of the tiles....

HELP...
![Screenshot 2024-08-08 072408](https://github.com/user-attachments/assets/b220741b-d0c7-44cf-8944-c4ae34ca5ea9)

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Mariusthvdb** [comment]
<img width="732" alt="Scherm­afbeelding 2024-08-08 om 09 50 53" src="https://github.com/user-attachments/assets/10aaa824-0f1b-4dd1-87e8-6d799de5d7fc">
