### ISSUE TITLE
Support for font-weight

### ISSUE THREAD

**Issue by petrij98** [thomasloven/lovelace-card-mod#394]
I'm looking to add bold text into my Mushroom Title cards. However, font-weight does not appear to be supported on the frontend presently. I would love to see this be implemented, as I would like to utilize it in my configuration. I'm unsure if this is an ongoing issue, but it's not something I've seen a lot of traction on recently.

Example code:
```
card_mod:
  style: |
    ha-card {
      text-decoration: underline;
      font-style: italic;
      font-family: "Arial";
      font-weight: 950;
    }
```

**Comment by ildar170975** [comment]
Not a card-mod bug. Suggest to close the issue and continue researching in Community.

**Comment by petrij98** [comment]
My research in Community is what brought me here. I haven't been able to find a solution.

**Comment by ildar170975** [comment]
I see.
As it was already noted by another Community member, you ticked this:
```
- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
```
and agreed that Community must be used for a support.

Cannot be a FR - card-mod merely adds a css property `font-weight`, it may be called like you wish (`super-font-weight`), card-mod does not care.

**Comment by petrij98** [comment]
Understood. Given that there is an entire section dedicated solely to requesting features when creating a request, along with the enhancement label, this was not made clear to me. I did not tick any box nor agreed that Community was to be used solely for support. There may be something broken, because this was never prompted for me. Thank you for your replies.

**Comment by ildar170975** [comment]
Well, this was not a feature request.
Ask [here](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/) - the main card-mod thread.
Actually, for mushrooms it is better to ask in the main mushroom thread, but I have no idea where it is (not using mushrooms).
