### ISSUE TITLE
Options to match Mushroom Cards to Tile cards in terms of effects on click / hover + options to match Mushroom Title Card to Sections title

### ISSUE THREAD

**Issue by circa1665** [thomasloven/lovelace-card-mod#399]
Hi realise that some people will be using only mushroom cards on their dashboards. I use a mixture of tile cards and mushroom cards where mushroom cards enable functionality that tile cards don't have.

Could we have additional features so that when tile and mushroom cards are used together we can optionally have no visual differences to the user in terms appearance and behaviour?

### Hover and click effects

E.g. Tile cards have hover effects (a colour wash), the icon on a tile card enlarges when clicked, there's a stronger colour wash over the tile card when it is clicked.

Mushroom cards don't have these - would it be possible to add options to enable this?:
![ScreenRecording2024-08-23at14 52 10-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/a7388ff6-c6af-447e-8417-1f4ac01fab35)

↑ The bottom card is a tile card, the top two are Mushroom Template cards.

### Mushroom title card

Currently if the Mushroom Title card is used in place of a Section title on a Sections dashboard it throws the grid out of alignment and card-mod must be used to make everything appear seamless:

<img width="920" alt="Screenshot 2024-08-23 at 14 54 42" src="https://github.com/user-attachments/assets/18c58245-0dc3-40a6-8397-aa9ffbf6f148">
<img width="685" alt="Screenshot 2024-08-23 at 15 19 40" src="https://github.com/user-attachments/assets/9fa4a105-e4d1-452e-a73a-05f447fb57c7">

↑ Mushroom Title card without card-mod overrides.

<img width="690" alt="Screenshot 2024-08-23 at 14 55 45" src="https://github.com/user-attachments/assets/bcdad164-79a5-40f5-806c-4565b74a0e9e">
<img width="687" alt="Screenshot 2024-08-23 at 15 19 10" src="https://github.com/user-attachments/assets/f691164b-ca4c-4619-9bb4-265cff10adc2">

↑ Mushroom Title card with card-mod overrides.

Would it be possible to add options to match the Sections title? In terms of padding, positioning, font-size etc.?

**Comment by ildar170975** [comment]
Card-mod should not care about a particular card - it just injects styles.
Suggest to go to Community & ask there.

**Comment by ildar170975** [comment]
https://github.com/thomasloven/lovelace-card-mod/issues/332 is only about making a "card_mod" keyword obligatory.

**Comment by circa1665** [comment]
Sorry I realise I've posted this in completely the wrong place meant to post this here https://github.com/piitaya/lovelace-mushroom and this was the issue I was referring to: https://github.com/piitaya/lovelace-mushroom/issues/1366
Anyway closing!
