### ISSUE TITLE
issue with --paper-item-icon-color with HA108

### ISSUE THREAD

**Issue by chinezbrun** [thomasloven/lovelace-card-mod#43]
My Home Assistant version: 0.108.1
My lovelace configuration method (GUI or yaml): GUI
What I am doing: change icon color by sensor state
What I expected to happen: 
What happened instead: nothing after update to 0.108, previous was ok
**Minimal** steps to reproduce:

entity: sensor.solar_grid_status
name: GRID
style: |
  ha-card {
    background:
    {% if states('sensor.solar_ac_input')|int > 200%}
    {% else %}
    red
    {% endif %};
    --paper-item-icon-color:
    {% if is_state('sensor.solar_grid_status', 'AC Use' ) %}
    rgb(80, 171, 48)
    {% endif %};
  }
theme: default
type: sensor

[ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x ] Have made sure I am using the latest version of the plugin.

[ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The variable for the icon color has changed in Home Assistant.

**Comment by DanielTerletzkiy** [comment]
> The variable for the icon color has changed in Home Assistant.
And..? What is it?
I really need to know

Thanks

**Comment by thomasloven** [comment]
I don't know. Find it the same way you found the old one, I guess. Use the element inspector? Ask whoever made the change?

**Comment by chinezbrun** [comment]
thanks, but any suggestion to move forward or subject is closed?

**Comment by broyuken** [comment]
Guess not

**Comment by baronrustamov** [comment]
Help please
