### ISSUE TITLE
Style is flicking on page refresh

### ISSUE THREAD

**Issue by tuga49** [thomasloven/lovelace-card-mod#45]
HA version: 0.108.5 | Lovelace: yaml | HACS: 0.24.0 | card-mod: 13

Hey guys, 
I'm testing this card mod. I get it to work, but every time I refresh the page, it makes a flick (show the normal card and then after miliseconds, apply the css. It seems to load the default and then apply css). It gives a very bad user experience when refresh the page.

I installed it trought HACS and then added this to resources:
- url: /hacsfiles/lovelace-card-mod/card-mod.js
  type: module

![gravacao](https://user-images.githubusercontent.com/17064445/79520427-ba529480-804e-11ea-9657-3ff4f196b06c.gif)

Here is my yaml:
```
title: Home
icon: 'mdi:home'
path: home

cards:
  - type: vertical-stack
    cards:
      - type: entities
        style: |
          ha-card {
            border-radius: 15px;
            border: 1px solid green;
            background-color: yellow;
          }
        entities:
          - entity: binary_sensor.xxxxxxxxxxxxxxxxxxxxxxxxx
          - entity: binary_sensor.xxxxxxxxxxxxxxxxxxxxxxxxx
```

Thanks for any help

**Comment by tuga49** [comment]
If I do this way, it dont flick and loads css instantlly. In docs it says to avoid this. If followed some examples here: https://github.com/thomasloven/lovelace-card-mod/blob/master/src/example.yaml and it flicks. The only way I find is this way. Any one can explain what i'm doing wrong? 
```
title: Home
icon: 'mdi:home'
path: home

cards:
  - type: custom:mod-card
    card:
      type: vertical-stack
      cards:
        - type: entities
          style: |
            ha-card {
              border-radius: 15px;
              border: 1px solid green;
              background-color: yellow;
            }
          entities:
            - entity: binary_sensor.xxxxxxxxxxxxxxxxxxxxxxxxx
            - entity: binary_sensor.xxxxxxxxxxxxxxxxxxxxxxxxx
```

Thank's

**Comment by migo-dev** [comment]
Did you find another solution or is the custom:mod-card the way to go (for now hopefully)?

**Comment by tuga49** [comment]
> Did you find another solution or is the custom:mod-card the way to go (for now hopefully)?

I use some custom cards but ot continue flicking. I can't find any solution. I tried use custom cards locally but it happens, so I think it should be normal :(
