### ISSUE TITLE
getting custom element does not exist

### ISSUE THREAD

**Issue by codycato** [thomasloven/lovelace-card-mod#5]
Cant get any of them to work card-mod or card- modder
i copied the raw code and made a .js file in www folder. i also added type an url to resources raw  edit.

i keep getting custom element doesn't exist

**Comment by Dino-Tech** [comment]
@
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

**Comment by Dino-Tech** [comment]
@
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

**Comment by Dino-Tech** [comment]
> Cant get any of them to work card-mod or card- modder
> i copied the raw code and made a .js file in www folder. i also added type an url to resources raw edit.
> 
> i keep getting custom element doesn't exist

https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins
@codycato

**Comment by codycato** [comment]
@Dino-Tech Someone just told me I have to use the url path that's specified for each plugin

**Comment by thomasloven** [comment]
Does that mean this issue is solved?
