### ISSUE TITLE
Custom font styling is not applied to markdown card

### ISSUE THREAD

**Issue by Knapoc** [thomasloven/lovelace-card-mod#52]
My Home Assistant version: 0.111.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing: applying custom styling to a markdown-card

What I expected to happen: font styling is applied to element h1

What happened instead: no styling is applied. Safari reports `User Agent Style Sheet`. Issue is present in Firefox too.

**Minimal** steps to reproduce:
Use the aforementioned yaml in a view.

```yaml
- type: markdown
   content: |
     # Vacuum automation
   style: |
     ha-card {
       height: 50px;
       --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
       box-shadow: 2px 2px rgba(0,0,0,0.0);
     }
     h1 {
       font-size: 14px;
       font-weight: thin;
       font-family: Helvetica;
       letter-spacing: '-0.01em';
     }
```

Error messages from the browser console: (I don't think these are related)
```
[Error] hui-thermostat-card – Error: Specify an entity from within the climate domain.
Error: Specify an entity from within the climate domain.
	s (chunk.6dbb65acb727c33dd251.js:2144:318438)
	value (chunk.ab96942901cd9a8d7754.js:146:46870)
	(anonymous function) (chunk.ab96942901cd9a8d7754.js:146:47612)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] hui-alarm-panel-card – Error: Invalid card configuration
Error: Invalid card configuration
	s (chunk.6dbb65acb727c33dd251.js:2144:318438)
	value (chunk.ab96942901cd9a8d7754.js:146:46870)
	(anonymous function) (chunk.ab96942901cd9a8d7754.js:146:47612)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (index.m.js.map, line 0)
```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by filikun** [comment]
I might have this problem as well. From 110 to 111 I can no longer customise font size on markdown and all my cards now have massive font size. Easy to read but not as nice looking ^^

**Comment by DevMighty** [comment]
I have recreated this exact same issue on 3 different instances.

**Comment by joaofl** [comment]
Same here...

**Comment by hmmbob** [comment]
As I've got a feeling it is HA frontend related, I've created an issue there.

**Comment by joaofl** [comment]
Indeed. There were many changes to the frontend meant to speed up the loading, as mentioned in the release notes of version 111.

**Comment by warwickofthegh** [comment]
the same styling no longer applies to any element targeted below ha-card and ha-markdown, I figure as others have suggested it due to the front-end changes in 0.111

**Comment by jsilva72** [comment]
I have the sSame problem after Upgrading to 111

**Comment by ASNNetworks** [comment]
Came here to confirm the styling CSS does not stick anymore. When using inspect element I see different CSS stylings than I have written/applied.

**Comment by ijustlikeit** [comment]
Same style within markdown is ignored.  Worked in 110.

**Comment by MijnGedacht** [comment]
CSS style applied to <ha-icon> under markdown not working anymore since 0.111

**Comment by tomlut** [comment]
Hi @thomasloven is this likely to be fixed?

It's the only thing stopping me updating to 0.111

If not, I guess I'll just have to find a different method of displaying a large clock using the markdown card on my homepage.

**Comment by Knapoc** [comment]
You can style markdown by applying styles to `ha-card`. That’s what I did to solve this issue.

**Comment by tomlut** [comment]
No I cant. The card does not contain the Heading1 and Heading2 html tags.
```
  - card_type: markdown
    content: |
      ## <br>
      # {{states("sensor.time")}}
      ## <br>
      ## {{states('sensor.simple_time_date')}}
    style: |
      ha-card {
        --ha-card-background: 'rgba(0, 0, 0, 0)';
        --ha-card-box-shadow: 'none'
      }
      h1 {
        text-align: center;
        font-size: 6em;
        margin-bottom:12px;
        margin-top: 12px;
      }
      h2 {
        text-align: center;
      }
...etc
```
![Screenshot_2020-06-16 Overview - Home Assistant](https://user-images.githubusercontent.com/10679300/84736974-6a496d00-afc0-11ea-9240-5884c2dbd42a.png)

**Comment by Knapoc** [comment]
You’re right. In your use case it wouldn’t work because you want to style date, time, etc differently.
If you want to apply only one style to the whole markdown card, you’re able to do so by setting text size, alignment in ha-card.

**Comment by tomlut** [comment]
I guess I could split the sections into separate vertically stacked markdown cards.

**Comment by tomlut** [comment]
Done and pretty happy with the result.
```
entities:
  - card_type: markdown
    content: |
      <br>
      <br>
      <br>
      <b>
      {{states("sensor.time")}}
      </b>
    style: |

      ha-card {
        --ha-card-background: 'rgba(0, 0, 0, 0)';
        --ha-card-box-shadow: 'none';
        font-size: 84px;
        text-align: center;
      }
    type: 'custom:hui-element'
  - card_type: markdown
    content: |
      <b>
      {{states('sensor.simple_time_date')}}
      </b>
    style: |
      ha-card {
        --ha-card-background: 'rgba(0, 0, 0, 0)';
        --ha-card-box-shadow: 'none';
        font-size: 22px;
        text-align: center;
      }
    type: 'custom:hui-element'
```
![Screenshot_2020-06-16 Overview - Home Assistant(1)](https://user-images.githubusercontent.com/10679300/84764071-9841a800-afe6-11ea-9eed-0829fd891cb4.png)

**Comment by hmmbob** [comment]
Looks great, but in the end is more a workaround than it is the solution :)

**Comment by tomlut** [comment]
Not if the frontend changes are permanent :/

**Comment by gadgetchnnel** [comment]
The markdown card now has the following structure

ha-card
|__ shadow-root
     |__ha-markdown
          |__shadow-root
               |__ha-markdown-element

So, you need to follow the [advanced usage](https://github.com/thomasloven/lovelace-card-mod#advanced-usage) instructions and do something like:

```
type: markdown
content: |
  ## <br>
  # {{states("sensor.time")}}
  ## <br>
  ## {{ states("sensor.date_time") }}
style:
  ha-markdown:
    $: |
      h1 {
        text-align: center;
        font-size: 6em;
        margin-bottom:12px;
        margin-top: 12px;
      }
      h2 {
        text-align: center;
      }
```

That appears to work and gives me:

![image](https://user-images.githubusercontent.com/2099542/84780619-b2c35380-afdd-11ea-95ab-f26ba100e8cc.png)

**Comment by ASNNetworks** [comment]
@gadgetchnnel 

Is it possible to use both ha-card and ha-markdown together? I need ha-card to remove the background of the markdown card, but when using that, ha-markdown gets ignored (pretty much like what happens to h1 now). 

This was my styling prior to the changes,.
```
style:  |
  ha-card {
    --paper-card-background-color: none !important;
    box-shadow: none !important;
    height: 30px;
    font-size: 8px;
    font-weight: thin;
    font-family: Helvetica;
    letter-spacing: '-0.01em';    
  }
  h1 {
    font-size: 15px;
    font-weight: thin;
    font-family: Helvetica;
    letter-spacing: '-0.01em';
  }
```

When putting the font-sizes in ha-card it does work, but the sizes are different so I have to see what font-size is the same as before. But when I copy your ha-markdown, it does work but then I can't change ha-card. Using ha-card and ha-markdown seems to ignore the ha-markdown and only sees ha-card (same as now with h1). 

This is what I tried but seems to ignore ha-markdown (unless I remove ha-card)

```
type: markdown
content: >
  # {% if is_state('sensor.lights_on', '0')%} Alle lampen
  staan uit. {% elif is_state('sensor.lights_on', '1')%} Er
  staat 1 lamp aan.  {% else %}  Er staan
  {{states('sensor.lights_on')}}  lampen aan.  {% endif%}
style: |
  ha-card {
    --paper-card-background-color: none !important;
    box-shadow: none !important;
    height: 30px;    
  }
  ha-markdown: |
      h1 {
        font-size: 10px;
        font-weight: thin;
        font-family: Helvetica;
        letter-spacing: '-0.01em';
      }
```

**Comment by gadgetchnnel** [comment]
@ASNNetworks 

I think it would be like this:

```
style:
  .: |
    ha-card {
      --paper-card-background-color: none !important;
      box-shadow: none !important;
      height: 30px; 
    }
  ha-markdown:
    $: |
      h1 {
        font-size: 10px;
        font-weight: thin;
        font-family: Helvetica;
        letter-spacing: '-0.01em';
      }
```

**Comment by ASNNetworks** [comment]
> @ASNNetworks
> 
> I think it would be like this:
> 
> ```
> style:
>   .: |
>     ha-card {
>       --paper-card-background-color: none !important;
>       box-shadow: none !important;
>       height: 30px; 
>     }
>   ha-markdown:
>     $: |
>       h1 {
>         font-size: 10px;
>         font-weight: thin;
>         font-family: Helvetica;
>         letter-spacing: '-0.01em';
>       }
> ```

YES! That works excellent! Thanks alot, you have saved me a lot of testing and headaches!

**Comment by hmmbob** [comment]
Works great - except for H2 headers? Seems there is some fixed styling somewhere that doesn't get overridden.

I change the exact same lines to H1 (and #) and then it works, but styling h2 and using ## doesn't work.

Non working code:
```
      - type: markdown
        content: |
         ## Thermostaat
        style:
          .: |
            ha-card {
             margin: 12px 14px -5px 14px;
             box-shadow: none;
             --paper-card-background-color: rgba(0, 0, 0, 0.0)
            }
          ha-markdown:
            $: |
             h2 { 
              font-size: 18px !important;
              font-weight: 400 !important;
              padding-left: 10px !important;
              border-left: 3px solid rgba(81, 134, 236);
             }

```
Change the ## to # and h2 to h1 to get a working styling.

**Comment by warwickofthegh** [comment]
could someone please give me a quick run down on .: and $: or links to documentation for their usage

**Comment by warwickofthegh** [comment]
Thanks @gadgetchnnel - all it takes is for one person to RTFM and we're back in business, haha :)

**Comment by joaofl** [comment]
@tomlut @Knapoc 
Actually, if you use and customize the h3 style along with the h1. The problem seems to be only with the h2.
Mine looks like this:

![image](https://user-images.githubusercontent.com/8092452/84920343-4fabec80-b0c3-11ea-98aa-b71294683441.png)

**Comment by hmmbob** [comment]
Yeah, I found the offending code here:

https://github.com/home-assistant/frontend/blob/9ff2eece3aafe6e7ba26075aed2f981e12dbee1a/src/components/ha-markdown.ts#L72-L75

I've added that info to the (closed) issue I had created, asking Bram to review if this is as intended.

https://github.com/home-assistant/frontend/issues/6147

**Comment by thomasloven** [comment]
@gadgetchnnel has the correct solution [here](https://github.com/thomasloven/lovelace-card-mod/issues/52#issuecomment-644767155).

**Comment by thomasloven** [comment]
The problem with h2 can be solved by using a more specific selector than the built in one, such as
```
ha-markdown-element:first-of-type h2 {
  font-size: 50px !important;
}```

**Comment by tomlut** [comment]
Why do this though?

Why make it more complicated?

**Comment by thomasloven** [comment]
Because it makes Home Assistant and it's core functionality work better and more pretty.
You can't expect the core to accommodate for dirty hacks like card-mod.

**Comment by hmmbob** [comment]
Thanks Thomas, much appreciated.

**Comment by KTibow** [comment]
Just saying: You might need to change `style: |` to `style:` to make it work, if that wasn't already clear.
