### ISSUE TITLE
Modify cards using JavaScript

### ISSUE THREAD

**Issue by davidjb** [thomasloven/lovelace-card-mod#53]
I've got a couple of situations within cards where I'd like to tweak the resulting HTML (for example, to adjust the HTML structure/layout beyond what CSS can do; and separately create/modify output not supported by the Markdown renderer/sanitizer).  In this case, being able to run a script on the card content, much like the `applyStyle` functionality does, would solve this, allowing one to tweak the DOM arbitrarily in the context of a given card.

The existing style application functionality (config lookup, card wrappers, etc) are all there and running a script would sit alongside that.  If you think this would be a useful inclusion in this project, I could create a PR.

Thoughts?

**Comment by thomasloven** [comment]
I do not feel this is within the scope of card-mod.
