### ISSUE TITLE
Incompatible with other plugins

### ISSUE THREAD

**Issue by jcwillox** [thomasloven/lovelace-card-mod#55]
Currently, card-mod overrides the `firstUpdated` method of an elements prototype, this causes an issue when other Lovelace plugins also attempt to override this method, the last plugin to load will be the only one that works (i.e. if card-mod is loaded last it breaks other plugins).
This could also cause issues if the Home Assistant frontend ever wants to override these prototype methods.

The solution as it has been implemented in a few plugins is to copy the current `firstUpdated` method, then override it and call the original `firstUpdated` inside the new one.

Below is an example implementation.

```js
customElements.whenDefined("ha-card").then(() => {
    const HaCard= customElements.get("ha-card");
    // grab the original first updated
    const oFirstUpdated = HaCard.prototype.firstUpdated;

    HaCard.prototype.firstUpdated = function (changedProperties) {
      // call the original first updated
      oFirstUpdated.call(this, changedProperties);
      // the rest of your code ...
    };

    fireEvent("ll-rebuild", {});
  });
```

This is the implementation I used, 
https://github.com/jcwillox/lovelace-canary/blob/master/src/module.js

Related issue: jcwillox/lovelace-canary#1

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
You're right. I've been alone in this field so long I haven't had to worry about this.

**Comment by jcwillox** [comment]
Hey, so I got a chance to test this fix and its still not properly compatible with other plugins, currently when card-mod is installed I get `Cannot read property 'config' of undefined` errors. I believe this is because you're not passing the `this` context to the function. Using `call(this, changedProperties)` should ensure `firstUpdated` gets called as if it was the original function.

```js
const Element = customElements.get(element);
const oFirstUpdated = Element.prototype.firstUpdated;

Element.prototype.firstUpdated = function (changedProperties) {
  oFirstUpdated.call(this, changedProperties);
  ...
};
```

**Comment by thomasloven** [comment]
Sorry. Fixed!

**Comment by jcwillox** [comment]
Just checked and everything working together perfectly now, thanks!
