### ISSUE TITLE
Styling using config.entity requires an entity state change to take effect

### ISSUE THREAD

**Issue by rccoleman** [thomasloven/lovelace-card-mod#56]
**My Home Assistant version:** 0.113.b1

**My lovelace configuration method (GUI or yaml):** YAML

**What I am doing:** Coloring icons (typically in Glance cards) using templates via card_mod

Here's a test view:
```
  - title: Test
    panel: true
    cards:
      - type: glance
        entities:
          - entity: group.fr
            name: Family Room
            style: |
              :host {
                --paper-item-icon-color:
                  {% if states(config.entity) == 'on' %} red;
                  {% else %} green;
                  {% endif %}
                --paper-item-icon-active-color: red;
              }
```

And here's what it looks like on my iPhone:

![IMG_1062](https://user-images.githubusercontent.com/860888/87860228-8f4b3b80-c8f0-11ea-9ac5-abbc44e87072.jpg)

Note the white icon, despite the styling.

**What I expected to happen:** Colors reliably show up without the need to change the state of an entity

**What happened instead:** In Safari on the desktop or a webview on iOS, icons often just show up with their default colors (white for off, yellow for on).  If I change the state of the entity, the colors display properly, and the colors will continue to display until the screen reloads (either manually, or when bringing the browser back into focus).  Then they go back to white/yellow.  On Chrome on my Mac, the view works fine and the colors display properly at all times.

Here's that same screen on my iPhone after I turn the group on:

![IMG_1063](https://user-images.githubusercontent.com/860888/87860455-7774b700-c8f2-11ea-8735-84e6d39d0edd.jpg)

**Minimal** steps to reproduce:

Add the view that I created above and test it in Safari on a Mac or on iOS.  If you see a white or black icon (depending on the theme), you're seeing the issue.  Change the state of the entity and see the color come through properly.

If I change the view to this, with just a static color and not a template, it works on all browsers and platforms:

```
  - title: Test
    panel: true
    cards:
      - type: glance
        entities:
          - entity: group.fr
            name: Family Room
            style: |
              :host {
                --paper-item-icon-color: green;
              }
```

I wonder if we need something like the "trigger" functionality of the custom button card to indicate which entities need to trigger styling.  I have a set of custom button cards with conditional styling that always display the proper colors on all platforms.

I'm running iOS 13.6 on my iPhone and MacOS Catalina.

**Error messages from the browser console:**

Console errors are difficult to retrieve on mobile, but I don't see anything on Safari on the desktop when I reproduce this issue.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin. **(2.0.0)**

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by kmorris81** [comment]
+1 on this issue...

**Comment by thomasloven** [comment]
Please try with version 3.0.0
