### ISSUE TITLE
Expected a value of type undefined` for style but received hacard

### ISSUE THREAD

**Issue by Uniwatcher** [thomasloven/lovelace-card-mod#59]
Sinds HA 0.113.0 I get the following error:

> Expected a value of type `undefined` for `style` but received `"hacard {\n --paper-card-background-color: rgba(0,0,0,.9);\n --paper-input-container-color: rgba(255,255,255,1);\n --paper-item-icon-color: rgba(255,255,255,1);\n --paper-input-color: rgba(255,255,255,1);\n color: white\n }\n"`

Example of my config:
```
style: |
  hacard {
    --paper-card-background-color: rgba(0,0,0,.9);
    --paper-input-container-color: rgba(255,255,255,1);
    --paper-item-icon-color: rgba(255,255,255,1);
    --paper-input-color: rgba(255,255,255,1);
    color: white
    }
```

**Comment by wThomas84** [comment]
Hello,

I see the same behavior with the same HA version.

**Comment by stephenmetts** [comment]
Check 0.113.0 release notes to remove the 'paper' in the config.

**Comment by Uniwatcher** [comment]
Thanks, that solved the problem!
