### ISSUE TITLE
Styling stack cards

### ISSUE THREAD

**Issue by darkkatarsis** [thomasloven/lovelace-card-mod#6]
Is there any plans to add styling options for horizontal/vertical-stack card or custom:vertical-stack-in-card? I can not figure out how to change the background for these elements...

If it works now, I will be grateful for the tip of how to do it

**Comment by darkkatarsis** [comment]
I know that lovelace-card-modder has everything that I wrote but on the add-on page is the is information that it will no longer be developed further

**Comment by thomasloven** [comment]
I've added a description about this behavior to the readme.
https://github.com/thomasloven/lovelace-card-mod#why-wont-this-work-for-some-cards
