### ISSUE TITLE
113.0 Upgrade querySelectorAll Error

### ISSUE THREAD

**Issue by stephenmetts** [thomasloven/lovelace-card-mod#62]
My Home Assistant version: 0.113.0

My lovelace configuration method (GUI or yaml): YAML

What I am doing: Inspired dashboard from https://github.com/matt8707/hass-config page load of dashboard.

What I expected to happen: Page loads without console errors

What happened instead: Console error occurring after 0.113.0 upgrade 

Error messages from the browser console:

`card-mod.js:1 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Element': '0' is not a valid selector.
    at HTMLElement.setStyle (http://solheimajokull.premedia.home:8123/local/community/lovelace-card-mod/card-mod.js:1:5754)
    at async HTMLElement._setTemplate (http://solheimajokull.premedia.home:8123/local/community/lovelace-card-mod/card-mod.js:1:4264)`

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ X] Have made sure I am using the latest version of the plugin.

[X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by stephenmetts** [comment]
![Screen Shot 2020-07-24 at 3 23 21 PM](https://user-images.githubusercontent.com/45015305/88432682-4f89c580-cdc2-11ea-9139-d13c835121bf.png)
![Screen Shot 2020-07-24 at 3 23 08 PM](https://user-images.githubusercontent.com/45015305/88432693-531d4c80-cdc2-11ea-8e49-0921795ec492.png)

**Comment by thomasloven** [comment]
Please supply a minimal configuration which illustrates the problem.

**Comment by zibous** [comment]
Same Problem (**Home Assistant 0.117.0b3**) here:
```
Home Assistant 0.117.0b3
Frontend-Version: 20201021.2 - latest
Browser: Chrome Version 86.0.4240.111 (Offizieller Build) (x86_64)
Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Element': '0' is not a valid selector.
    at u (http://hp.local:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:3231)
    at async HTMLElement.setStyle (http://hp.local:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:6385)
    at async HTMLElement._setTemplate (http://hp.local:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:4949)
```

```javascript
async function u(e, t, o=!1) {
        let n = e;
        "string" == typeof t && (t = t.split(/(\$| )/)),
        "" === t[t.length - 1] && t.pop();
        for (const [e,r] of t.entries())
            if (r.trim().length) {
                if (!n)
                    return null;
                n.localName && n.localName.includes("-") && await customElements.whenDefined(n.localName),
                n.updateComplete && await n.updateComplete,
                n = "$" === r ? o && e == t.length - 1 ? 
                       [n.shadowRoot] : n.shadowRoot : o && e == t.length - 1 ? 
                        n.querySelectorAll(r) : n.querySelector(r) // ### ERROR HERE
            }
        return n
    }
```
Home Assistant **0.116.4** works w/o any error.

**Comment by KTibow** [comment]
What version of card-mod are you running?

**Comment by zibous** [comment]
Latest from HACS 2.0.3
![Bildschirmfoto 2020-10-24 um 16 16 05](https://user-images.githubusercontent.com/30198737/97084025-608de100-1614-11eb-9ef9-cf37d77fa1ac.png)

**Comment by hristo-atanasov** [comment]
Any news about this issue? I'm following for a while, and still no fix. I have the same problem. As of today everything is updated to the latest version - Home Asistant and card-mod (2.0.3)..

**Comment by KTibow** [comment]
Looks like this is an error with the minifier.

**Comment by hristo-atanasov** [comment]
> Looks like this is an error with the minifier.

So if we use not minified version it will work?

**Comment by KTibow** [comment]
I don't know how you would compile without minfification.

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-card-mod/issues/62#issuecomment-705388838
