### ISSUE TITLE
How to CSS #root from card-mod??

### ISSUE THREAD

**Issue by MarsWarrior** [thomasloven/lovelace-card-mod#7]
This is not actually a bug I think, but I can't get it working. Might also have to do with my CSS knowledge.

In the chrome inspector I see the following hierarchy:
![image](https://user-images.githubusercontent.com/1220775/63169486-323b6b80-c037-11e9-83d4-c4610c2eb477.png)
A vertical-stack-in-card with two cards: circle and decluttering-card.

As you can see, I did change some settings in the inspector which I can't get to work from the yaml `style |` configuration:
- I set an `align-items: center;` on the `<div id="root" style="` to center both cards.
- I set a `flex: 1` on the `circle-sensor-card`
- I set a `flex: 2` on the `decluttering-card`

How do I do that with styling?
```
- type: vertical-stack-in-card
  style |
    ?????
```
If I use #root { xxx }, I don't see any result for instance.

**Comment by thomasloven** [comment]
See the rows that say `#shadow-root (open)`?
Those are blocking css from passing through.
[This section](https://github.com/thomasloven/lovelace-card-mod#advanced-usage) explains how to get past that.

**Comment by MarsWarrior** [comment]
Ah! Thanx.

Was that already in the documentation, because I totally missed that part then 😄 

Will try to get my head around that approach and see what I can accomplish in that case.

**Comment by redd-bbeard** [comment]
@MarsWarrior, Were you able to figure out how to get into the "DIV" I am attempting to do the same thing. I actually want to inject some co into the "div#root" style and I cannot for the life of me get it to work. I can see the injection into the "#root" in the web inspector but it gets overridden by something else.
