### ISSUE TITLE
Applying globally

### ISSUE THREAD

**Issue by marktillo** [thomasloven/lovelace-card-mod#72]
Is it possible to apply the styles globally rather than doing every card individually?

**Comment by fusionstream** [comment]
Is this not supported?

I tried adding a css via lovelace resources and instead of defining the animation keyframes in each card, put it there for a global source, But it seems to not run those frames

**Comment by fusionstream** [comment]
> Is this not supported?
> 
> I tried adding a css via lovelace resources and instead of defining the animation keyframes in each card, put it there for a global source, But it seems to not run those frames

https://shadow-dom-css.adobe.com/features/at-keyframes/

Seems to be a browser issue
