### ISSUE TITLE
0.116.4 - Failed to resolve module specifier "card-tools/src/lit-element".

### ISSUE THREAD

**Issue by buentead** [thomasloven/lovelace-card-mod#79]
My Home Assistant version: 0.116.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
- I installed the Javascript Module `card-mod.js` according to the description [Lovelace Plugins](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins)
- Then I changed the Entities Card Configuration in the Lovelace UI as follows:
```
type: entities
style: |
  .card-header .name { 
    color: red;
  }
entities:
  - entity: input_select.radio_station
  - entity: input_select.dlna_render
  - type: divider
  - entity: script.local_radio
title: Radio Stationen
```

What I expected to happen:
- The title "Radio Stationen" be in red

What happened instead:
- The title color remains black
- The log (log level `info`) shows the following entry:
```
2020-10-27 13:57:08 ERROR (MainThread) [frontend.js.latest.202010012] https://homeassistant.local:8123/lovelace-prod/default_view:0:0 Uncaught TypeError: Failed to resolve module specifier "card-tools/src/lit-element". Relative references must start with either "/", "./", or "../".
```

**Minimal** steps to reproduce:
- Update Home Assistant to version 0.116.4
- Install `card-mod-js` according to the description
- Create a new Entities Card in Lovelace with a title

```yaml
# The least amount of code possible to reproduce my error
type: entities
style: |
  .card-header .name { 
    color: red;
  }
entities: []
title: Hallo World
# End of code
```

Error messages from the browser console:
`Uncaught TypeError: Failed to resolve module specifier "card-tools/src/lit-element". Relative references must start with either "/", "./", or "../". (default_view:1)`

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by hyperant** [comment]
Had the same issue, make sure you get the correct card-mod.js file. The file I got was from src/card-mod.js

I then noticed there is a card-mod.js file in the root of the project, looked at the source code for that and noticed it was different. Updated my card-mod.js file to that one instead and it all just started to work.

https://github.com/thomasloven/lovelace-card-mod/blob/master/card-mod.js

**Comment by KTibow** [comment]
Consider closing? I'm *not so sure* you read https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

**Comment by Dielee** [comment]
@hyperant  thank you very much! This solved my issue.

**Comment by buentead** [comment]
> Had the same issue, make sure you get the correct card-mod.js file. The file I got was from src/card-mod.js
> 
> I then noticed there is a card-mod.js file in the root of the project, looked at the source code for that and noticed it was different. Updated my card-mod.js file to that one instead and it all just started to work.
> 
> https://github.com/thomasloven/lovelace-card-mod/blob/master/card-mod.js

Thank you, @hyperant , for your hint. This also fixed the issue on my side. The card-mod.js within the 'src' directory doesn't work.

**Comment by buentead** [comment]
The solution of @hyperant fixes this issue.
