### ISSUE TITLE
Question about styling

### ISSUE THREAD

**Issue by paddenstoeltje** [thomasloven/lovelace-card-mod#80]
Hello,

since the one of the latest updates I have a porblem with my background. It is not stretched to the bottom. I still have a margin of 8px, which is really annoying. I found that with the browser inspector removing the margin-top:-8px  in the "#colums" style makes the problem disappear. However, I tried to apply the fix in a style, but I just can't get it to work...

Any help would be appreciated!

Wouter
![Capture](https://user-images.githubusercontent.com/65397048/97356851-2d0fb880-1899-11eb-8b84-25aa31d6f47f.jpg)

**Comment by KTibow** [comment]
You probably need to use shadow-root styling and mod-card.
