### ISSUE TITLE
card-mod Not Loaded 

### ISSUE THREAD

**Issue by aladin2000** [thomasloven/lovelace-card-mod#83]
in HA Release 117.6 
using HACS 
Integration version: 	1.6.2
Frontend version: 	202009091732
Repositories: 	654
Installed repositories: 	43

plugin card-mod  is not loaded by hacs  'Not loaded' is the error

any help ?

**Comment by KTibow** [comment]
This is a problem with HACS, not card-mod. It probably will be resolved by uninstalling it, and reinstalling it, and force reloading.

**Comment by aladin2000** [comment]
here is the HACS response...
https://github.com/hacs/integration/issues/1666 

can you help ?

**Comment by KTibow** [comment]
There is no such card as
```
type: 'custom:card-mod'
```
Why didn't you tell me here as well that it sometimes loaded but errored? Also can you actually read the docs, instead of trying to teach yourself?

**Comment by aladin2000** [comment]
> There is no such card as
> 
> ```
> type: 'custom:card-mod'
> ```
> 
> Why didn't you tell me here as well that it sometimes loaded but errored? Also can you actually read the docs, instead of trying to teach yourself?

Sorry, but i was trying to use your complete code ( very long to copu it in case of case resolution) Si I succeeded to reproduce the erro by using a simple declaration in a custom card using the only one line 'type: card-mod' or 'type: mod-card' 
the error occurs  immediatly with my sample, , with your code the error arrive lately after the save of the card

**Comment by KTibow** [comment]
Try this example, and swap out the entities:
```
type: entities
style: |
  ha-card {
    color: red;
  }
entities:
  - light.infinity_mirror
  - light.ceiling_lights
  - light.kitchen_lights
```

**Comment by aladin2000** [comment]
type: entities
style: |
  ha-card {
    color: red;
  }
entities:
  - light.salon

no error

**Comment by KTibow** [comment]
So the text shows up red? Consider closing then, as that means card-mod is working?

**Comment by aladin2000** [comment]
yes , the light is red 

 but in your firmal  code , the card is 'type: mod-card'  and that is not working  
So how to fix the error  ?

**Comment by KTibow** [comment]
> firmal code

I think your translator is malfunctioning. What do you mean? Which code that I posted?

**Comment by aladin2000** [comment]
> > firmal code
> 
> I think your translator is malfunctioning. What do you mean? Which code that I posted?

sorry it is not yours....

**Comment by KTibow** [comment]
Can you close this issue, and then open a new issue?
