### ISSUE TITLE
Help with Advanced usage and native Calendar card, full screen height

### ISSUE THREAD

**Issue by capttrousers** [thomasloven/lovelace-card-mod#85]
Hello,

I'm trying to make the native Calendar card full screen. I have a basic yaml dashboard, with a single card, with the view set to Panel Mode to get full width. For full height I'm using the card-mod add on, installed via HACS. 

Calendar card: https://www.home-assistant.io/lovelace/calendar/

I've tried various ways of hacking together of the style: attribute in the yaml using the special `$` or `.` characters but I can't get the styling to apply. 

Here's an image of the HTML element inspectors. I notice the card-mod element inside the ha-card but not wrapping the ha-full-calendar.

![image](https://user-images.githubusercontent.com/11598657/99913832-78ae5a00-2cbf-11eb-8b44-4e8d1e95327c.png)

```
    cards:
      - type: calendar
        entities:
          - calendar.cal_entity
        initial_view: dayGridMonth
        debug_cardmod: true
        style: 
          .: 
            ha-card:
              $: | 
                ha-full-calendar {
                  height: calc(100%);
                }

```

Note I've tried a ton of variations of the style snippet above. So this is kind of a FR for improved docs around the Advanced mode. 

Thanks!

**Comment by capttrousers** [comment]
So I was able to get this to work with this style snippet:

```
style: |
          .type-calendar > ha-full-calendar {
            height: calc(100%);
          }
```

I'm not really sure why that works and something like `ha-card > ha-full-calendar` didnt work. Happy to learn more since Im sure I'll be using this great card-mod helper a ton.

**Comment by KTibow** [comment]
Consider closing?
