### ISSUE TITLE
 the padding-top of the markdown card is not overwritten, how do I fix it?

### ISSUE THREAD

**Issue by RssFra97** [thomasloven/lovelace-card-mod#86]
Hi,
the padding-top of the markdown card is not overwritten, how do I fix it?

I wrote this, but the padding-top always remains at 16px:

```
          - type: markdown
             content: >
              ## Camera
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
                ha-markdown.no-header {
                  padding: 0px;
                  padding-top: 0px;
                }
              ha-markdown:
                $: |
                  h1 {
                    font-size: 25px;
                    font-weight: bold;
                    font-family: Helvetica;
                    letter-pacing: '0.01em';
                  }
```

Photo: [https://ibb.co/2S2qm8s](https://ibb.co/2S2qm8s)

**Comment by KTibow** [comment]
Usually GitHub isn't a place for questions. Mind closing this and putting it on the HA forums?

**Comment by RssFra97** [comment]
> Usually GitHub isn't a place for questions. Mind closing this and putting it on the HA forums?

I think it is a bug, because if I enable it on a single card the css works, but on several cards it gives this error and the card is always of the same type

**Comment by thomasloven** [comment]
You have the answer exactly four lines above the problem in your code sample.
