### ISSUE TITLE
Badge with filter and with custom style

### ISSUE THREAD

**Issue by matata86** [thomasloven/lovelace-card-mod#90]
Is possible styling badge with filter?
I try this... but not working.

- type: entity-filter
        entities:
          - binary_sensor.updater
        style: |
          :host {
            --label-badge-blue: 
            {% if is_state('binary_sensor.updater', 'on') %}
              var(--warning-color)
            {% else %}
              var(--primary-color)
            {% endif %}
            ;
          }
        state_filter:
          - 'on'

**Comment by KTibow** [comment]
Please ask on the HA forums.
