### ISSUE TITLE
Question: How I can rotate a stream camera image?

### ISSUE THREAD

**Issue by gigios** [thomasloven/lovelace-card-mod#92]
I'm using for the first time this mod, and for me it's the first time that I'm using the CSS (sorry if this is a trivial question).
I have a picture-entity used to show an image (Octoprint mpeg image).
The problem is that the camera is rotated of 180 degree, for this reason I need to rotate the image in the Home Assistant.
I'm able to apply the rotation directly in the picture-entity in this way:

   ```- entity: camera.octoprint
      aspect_ratio: 50%
      camera_image: camera.octoprint
      #camera_view: live
      image: 'http://octopi.local/webcam/?action=snapshot'
      show_name: false
      show_state: false
      type: picture-entity
      style: |
        ha-card {
          transform: rotate(180deg);
        }
```

When I try to open the ha-dialog to show the live image (I think it's a 'more-info' panel) the image shown is correctly in live but with the original rotation.

How I can rotate also the image shown in this panel?

**Comment by KTibow** [comment]
Using card-mod themes more-info

**Comment by KTibow** [comment]
And try asking on the forums.

**Comment by gigios** [comment]
Ok, I will investigate also the management of the themes but I don't want to implement a specific theme (if the solution is this 😊)
I'm waiting some answer on the forum 😊

Thanks

**Comment by KTibow** [comment]
I'm willing to help if you post in https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744

**Comment by gigios** [comment]
No, my post was directly in the thread related the rotation of the image with octoprint (https://community.home-assistant.io/t/rotate-webcam-feed-mjpeg-in-a-lovelace/164418/9).
I will post the same question in the 'official' thread, thanks.

**Comment by gigios** [comment]
I haven't found a solution. I took a USB extension cable and rotated the camera.
