### ISSUE TITLE
Manipulating CSS from an iframe

### ISSUE THREAD

**Issue by kongo09** [thomasloven/lovelace-card-mod#94]
Does this work manipulating CSS loaded from an iframe as part of the `type: iframe` card? I cannot seem to get it right 

```
type: iframe
url: >-
  https://radar.wo-cloud.com/desktop/rr/compact?wrx=53.550,9.983&wrm=7&wry=53.550,9.983&wro=true
aspect_ratio: 50%
style: |
  wo-ripple {
    visibility: hidden;
  }

```
Idea is to remove the controls from the view, which are all inside the element `wo-ripple`. Upon inspection I see this inside a `#shadow-root` but no matter what I try, the card-mod doesn't seem to take effect.

**Comment by KTibow** [comment]
No matter whether a website is Home Assistant or not, it can't access inside of an iframe.

**Comment by kongo09** [comment]
Apologies for my ignorant question and thanks for the swift clarification.
