### ISSUE TITLE
Unhandled exception Promise Rejection

### ISSUE THREAD

**Issue by val-christopher** [thomasloven/lovelace-card-mod#95]
My Home Assistant version: 2020.12.12

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Using card-mod

What I expected to happen:
Ability to change CSS for cards

What happened instead:
No CSS is being applied. When I inspect browser, it mentions n unhandled exception of promise rejection. 
I am using card-mod.js released 3 months back. 
Platform tested - safari and chrome on MacBook Pro; android based tablet 
**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
You didn't complete the issue template. Please add the exact error messages.

**Comment by val-christopher** [comment]
### Code:
<img width="477" alt="Screen Shot 2021-01-10 at 9 31 00 AM" src="https://user-images.githubusercontent.com/53314774/104127507-13beca00-5328-11eb-970d-df609c1bb146.png">

### Chrome Browser:
<img width="1461" alt="Screen Shot 2021-01-10 at 9 30 30 AM" src="https://user-images.githubusercontent.com/53314774/104127512-1d483200-5328-11eb-9c23-7f940256c6f1.png">

### Safari Browser:
<img width="1471" alt="Screen Shot 2021-01-10 at 9 28 43 AM" src="https://user-images.githubusercontent.com/53314774/104127515-220ce600-5328-11eb-865b-c11cd59fe337.png">

**Comment by val-christopher** [comment]
Also - I only copied "card-mod.js" to my home assistant folder.  Do I need to get any other supporting files?

**Comment by KTibow** [comment]
I don't think you put it in the right place. What's the content of `card-mod.js`?

**Comment by val-christopher** [comment]
I downloaded it from here - and did what the install document said (click the file, click on Raw, save as, and copied to my home assistant folder):
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/53314774/104128381-dc9ee780-532c-11eb-9b6f-335b0e42302c.png">

**Comment by val-christopher** [comment]
Then I created the resource to point to the js file, restarted HA etc.,
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/53314774/104128414-03f5b480-532d-11eb-8fcf-6f55f03b0ad1.png">

**Comment by KTibow** [comment]
That's not the right URL. Where did you place it in HA?

**Comment by val-christopher** [comment]
/config is my HA installation folder. I created a sub folder for plugins me copied it in there.

**Comment by KTibow** [comment]
It needs to go into `/config/www/` in order to access it. Once you do that, the external URL would be `/local/card-mod.js`.

**Comment by val-christopher** [comment]
Awesome.  It is working now.  I still do not understand how it is recognizing /local when my installation setup is /config.  that may be beyond my level of understanding.  I am happy that it is working now.
Thank you so much for your time in helping me.
