### ISSUE TITLE
Usage with grid cards nested in a layout-card (aim: apply borders)

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-card-mod#97]
Hi,

I tried everything to get some borders in a `custom:layout-card` which nests several grid cards.

What I have is:
![grafik](https://user-images.githubusercontent.com/13799156/105617901-92187300-5de2-11eb-942e-40129f9a2cfa.png)
I want to have some borders around the grid cards. **How to accomplish this?**

It just doesn´t work (doesn´t apply the style):
![grafik](https://user-images.githubusercontent.com/13799156/105617878-51205e80-5de2-11eb-9460-04ce07897997.png)

Even mod-card did not work (looks like it isn´t installed?):
![grafik](https://user-images.githubusercontent.com/13799156/105617865-32ba6300-5de2-11eb-8856-bdb841c1ae69.png)

What did I miss?

**Comment by KTibow** [comment]
How did you try to install it?
You'll need to apply the border styling to every single card individually.

**Comment by bcutter** [comment]
> 
> 
> How did you try to install it?

I installed card-mod using HACS. Isn´t "mod-card" part of card-mod?

> You'll need to apply the border styling to every single card individually.

So it´s not possible to apply it to a grid card containing several other cards?

**Comment by KTibow** [comment]
> I installed card-mod using HACS. Isn´t "mod-card" part of card-mod?

If you go to HACS, does it say not loaded?

> So it´s not possible to apply it to a grid card containing several other cards?

Well you would need to shadow-root. You can still apply it to the cards.

**Comment by thomasloven** [comment]
Did you try clicking save when you got the error about mod-card?
Please try version 3.0.0.
With that you should be able to see a message in your browser console if card-mod is installed properly.

**Comment by bcutter** [comment]
> 
> 
> Did you try clicking save when you got the error about mod-card?
> Please try version 3.0.0.
> With that you should be able to see a message in your browser console if card-mod is installed properly.

With new version using `custom:mod-card` worked. Unfortunately it´s not perfect because

a) either I have a good looking mobile view (smartphone) with clearly visible boarders when NOT using panel mode while at the same time on desktops it looks bad because being aligned vertically (`custom:layout-card` with horizontal setting seems to only work in panel mode):

- mobile:
![grafik](https://user-images.githubusercontent.com/13799156/109363560-2d42b380-788d-11eb-83c1-13c7b80cc896.png)

- desktop:
![grafik](https://user-images.githubusercontent.com/13799156/109362524-772a9a00-788b-11eb-816b-09919642d37e.png)

or b) I have with panel mode enabled a good looking desktop view but missing boarders on the mobile view (smartphone) at least in portrait mode, landscape is looking great:

- mobile (portrait - **have a look at the missing left boarder line**):
![grafik](https://user-images.githubusercontent.com/13799156/109363581-36cc1b80-788d-11eb-91e1-ac6635410d11.png)

- mobile (landscape):
![grafik](https://user-images.githubusercontent.com/13799156/109363592-3c296600-788d-11eb-858a-9257fb2d153d.png)

- desktop:
![grafik](https://user-images.githubusercontent.com/13799156/109362781-0637b200-788c-11eb-8f10-4e53ba713f0e.png)

I would need to find a way to add some space to the outer area (only left part) of the `custom:layout-card` so the boarder will be shown on the mobile, so option b) would be the one to choose.

Maybe I´ll find an appropriate HTML code for adding a bit of blank space to the left part...

**Comment by bcutter** [comment]
Update: Oh it was so easy... added another mod-card (outer area, embedded in panel mode) and set padding.


```
type: 'custom:mod-card'
style: |
  ha-card {
    padding: 5px;
  }
card:
  type: 'custom:layout-card'
  layout: horizontal
  ...
```

As this was more a specific "issue" with `custom:layout-card` related to my scenario and this initial issue has been solved I close this issue.

I only wonder why I need to use mod-card instead of lovelace just accepting `style` definition... but anyway, a bit more complex yaml code seems to be the prize for a good looking UI :-)
